'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Asegurable
    Public Property IDModulo As Integer
    Public Property IDAsegurable As Integer
    Public Property IDAsegurablePadre As Nullable(Of Integer)
    Public Property IDEmpresa As String
    Public Property IDEstablecimiento As Nullable(Of Integer)
    Public Property CodAsegurable As String
    Public Property Nombre As String
    Public Property Descripcion As String
    Public Property CodRef As String
    Public Property orden As Nullable(Of Integer)
    Public Property UsuarioActualizacion As String
    Public Property FechaActualizacion As Date

    Public Overridable Property AutorizacionRol As ICollection(Of AutorizacionRol) = New HashSet(Of AutorizacionRol)

End Class
