'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Producto
    Public Property IDProducto As Integer
    Public Property nombre As String
    Public Property descripcion As String
    Public Property UsuarioActualizacion As String
    Public Property FechaActualizacion As Date

    Public Overridable Property ProductoDetalle As ICollection(Of ProductoDetalle) = New HashSet(Of ProductoDetalle)

End Class
