'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Rol
    Public Property IDRol As Integer
    Public Property idPadre As Nullable(Of Integer)
    Public Property idEmpresa As String
    Public Property Nombre As String
    Public Property Descripcion As String
    Public Property tipo As String
    Public Property UsuarioActualizacion As String
    Public Property FechaActualizacion As Date
    Public Property control As String
    Public Property tipoEF As String

    Public Overridable Property UsuarioRol As ICollection(Of UsuarioRol) = New HashSet(Of UsuarioRol)

End Class
