'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Afp
    Public Property IDAFP As Integer
    Public Property DescripcionCorta As String
    Public Property DescripcionLarga As String
    Public Property AporteObligatorio As Nullable(Of Decimal)
    Public Property PrimaSeguro As Nullable(Of Decimal)
    Public Property ComisionPorcentual As Nullable(Of Decimal)
    Public Property AporteVoluntario As Nullable(Of Decimal)
    Public Property LimitedeSueldo As Nullable(Of Decimal)
    Public Property UsuarioModificacion As String
    Public Property FechaModificacion As Nullable(Of Date)

End Class
