'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cargos
    Public Property IDCargo As Integer
    Public Property DescripcionCorta As String
    Public Property DescripcionLargo As String
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property UsuarioModificacion As String
    Public Property TipoPlanilla As String
    Public Property Importe As Nullable(Of Decimal)

    Public Overridable Property PersonalCargo As ICollection(Of PersonalCargo) = New HashSet(Of PersonalCargo)

End Class
