'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Concepto
    Public Property IDConcepto As Integer
    Public Property Orden As String
    Public Property DescripcionCorta As String
    Public Property DescripcionLarga As String
    Public Property IDSunat As Integer
    Public Property IDContable As Integer
    Public Property TipoConcepto As String
    Public Property Moneda As String
    Public Property TipoCalculo As String
    Public Property ValorCalculo As Nullable(Of Decimal)
    Public Property Formula As String
    Public Property Activo As Nullable(Of Boolean)
    Public Property TipoPlanilla As String
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property UsuarioModificacion As String
    Public Property SeleccionarRegistro As Nullable(Of Boolean)

End Class
