'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ControlDeAsistencia
    Public Property IDAsistencia As Integer
    Public Property IDPersonal As Integer
    Public Property iddocumentoref As Nullable(Of Integer)
    Public Property tipoPersona As String
    Public Property TipoAcesso As String
    Public Property FechaAsistencia As Nullable(Of Date)
    Public Property HoraIngreso As Nullable(Of System.TimeSpan)
    Public Property Tardanza As Nullable(Of System.TimeSpan)
    Public Property HorasTotales As Nullable(Of System.TimeSpan)
    Public Property HorasExtras As Nullable(Of System.TimeSpan)
    Public Property Faltas As Nullable(Of Integer)
    Public Property MesAsistencia As Nullable(Of Integer)
    Public Property AñoAsistencia As Nullable(Of Integer)
    Public Property DiaAsistencia As Nullable(Of Integer)
    Public Property status As Nullable(Of Short)
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property UsuarioModificacion As String

End Class
