'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Periodos
    Public Property IDPeriodo As Integer
    Public Property Mes As String
    Public Property FechaInicio As Nullable(Of Date)
    Public Property fechafin As Nullable(Of Date)

End Class
