'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Personal
    Public Property IDPersonal As Integer
    Public Property idEstablecimiento As Nullable(Of Integer)
    Public Property ApellidoPaterno As String
    Public Property ApellidoMaterno As String
    Public Property Nombre As String
    Public Property Telefono As String
    Public Property Celular As String
    Public Property Sexo As String
    Public Property FechaNacimiento As Nullable(Of Date)
    Public Property Estadocivil As String
    Public Property Email As String
    Public Property paisEmisorComprobante As String
    Public Property Fotografia As String
    Public Property Tipodocumento As String
    Public Property Numerodocumento As String
    Public Property codigoLargaDistancia As String
    Public Property regimenLaboral As String
    Public Property CategoriaOcupacional As String
    Public Property tipoContrato As String
    Public Property JornadaTrabajoMaximo As Nullable(Of Boolean)
    Public Property JornadaTrabajoAtipica As Nullable(Of Boolean)
    Public Property JornadaTrabajoNocturno As Nullable(Of Boolean)
    Public Property SituacionEspecial As String
    Public Property Discapacidad As Nullable(Of Boolean)
    Public Property Sindicalizado As Nullable(Of Boolean)
    Public Property RegimenSalud As String
    Public Property RegimenSalud_Inicio As Nullable(Of Date)
    Public Property RegimenSalud_Fin As Nullable(Of Date)
    Public Property PrimeraDireccion As String
    Public Property SegundaDireccion As Nullable(Of Integer)
    Public Property Estado As String
    Public Property ViaTipo As String
    Public Property ViaNombre As String
    Public Property ViaNumero As String
    Public Property ViaDpto As String
    Public Property ViaInterior As String
    Public Property ViaManzana As String
    Public Property ViaLote As String
    Public Property Zonatipo As String
    Public Property Zonanombre As String
    Public Property Referencia As String
    Public Property Departamneto As String
    Public Property Provincia As String
    Public Property Distrito As String
    Public Property Nacionalidad As String
    Public Property CondicionDomiciliado As String
    Public Property Area As String
    Public Property TipoTrabajador As String
    Public Property LocalizacionTrabajador As Nullable(Of Integer)
    Public Property FormadePago As String
    Public Property periodicidadpago As String
    Public Property FechaIngreso As Nullable(Of Date)
    Public Property FechaCese As Nullable(Of Date)
    Public Property Situacion As String
    Public Property NivelEducacion As String
    Public Property RegimenPension As String
    Public Property InicioPension As Nullable(Of Date)
    Public Property FinalizaPension As Nullable(Of Date)
    Public Property IDAfp As Nullable(Of Integer)
    Public Property CoberturaPension As String
    Public Property CoberturaSalud As String
    Public Property SCRT As String
    Public Property AsignacionFamiliar As Nullable(Of Boolean)
    Public Property CoberturaSaludInicio As Nullable(Of Date)
    Public Property CoberturaSaludFinaliza As Nullable(Of Date)
    Public Property Banco As String
    Public Property BancoCuenta As String
    Public Property CTS As String
    Public Property CTSCuenta As String
    Public Property LIR As Nullable(Of Boolean)
    Public Property EvitaDobleImposicion As Nullable(Of Boolean)
    Public Property HoraInicio As Nullable(Of System.TimeSpan)
    Public Property HoraFinal As Nullable(Of System.TimeSpan)
    Public Property RefrigerioInicio As Nullable(Of System.TimeSpan)
    Public Property RefrigerioFin As Nullable(Of System.TimeSpan)
    Public Property DiasLaborables As Nullable(Of Integer)
    Public Property SueldoBasico As Nullable(Of Decimal)
    Public Property tipoHorario As String
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property UsuarioModificacion As String

    Public Overridable Property DerechoHabientes As ICollection(Of DerechoHabientes) = New HashSet(Of DerechoHabientes)
    Public Overridable Property PersonalCargo As ICollection(Of PersonalCargo) = New HashSet(Of PersonalCargo)
    Public Overridable Property PersonalProyecto As ICollection(Of PersonalProyecto) = New HashSet(Of PersonalProyecto)

End Class
