'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PersonalHorarios
    Public Property IDHorario As Integer
    Public Property IDPersonal As Nullable(Of Integer)
    Public Property IDCargo As Nullable(Of Integer)
    Public Property detalle As String
    Public Property DiaNumero As Nullable(Of Integer)
    Public Property DiaSemana As String
    Public Property HoraIngreso As Nullable(Of System.TimeSpan)
    Public Property HoraSalida As Nullable(Of System.TimeSpan)
    Public Property Refrigerio As Nullable(Of System.TimeSpan)
    Public Property Reingreso As Nullable(Of System.TimeSpan)
    Public Property fechamodificacion As Nullable(Of Date)
    Public Property usuariomodificacion As String

    Public Overridable Property PersonalCargo As PersonalCargo

End Class
