'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PersonalCargo
    Public Property IDCargo As Integer
    Public Property IDPersonal As Integer
    Public Property DescripcionCorta As String
    Public Property DescripcionLarga As String
    Public Property DiasLaborales As String
    Public Property Totalhoras As Nullable(Of Decimal)
    Public Property status As Nullable(Of Short)

    Public Overridable Property Cargos As Cargos
    Public Overridable Property Personal As Personal
    Public Overridable Property PersonalConceptos As ICollection(Of PersonalConceptos) = New HashSet(Of PersonalConceptos)
    Public Overridable Property PersonalHorarios As ICollection(Of PersonalHorarios) = New HashSet(Of PersonalHorarios)

End Class
