'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PersonalProyecto
    Public Property IDCosto As Integer
    Public Property IDPersonal As Integer
    Public Property IDCargo As Integer

    Public Overridable Property Personal As Personal

End Class
