'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PlanillaGeneral
    Public Property IDPlanilla As Integer
    Public Property IDAsistencia As Integer
    Public Property IDPersonal As Integer
    Public Property IDCargo As Integer
    Public Property TipoConcepto As String
    Public Property IDConcepto As Nullable(Of Integer)
    Public Property MesPlanilla As Integer
    Public Property AnioPlanilla As Integer
    Public Property FechaPlanilla As Nullable(Of Date)
    Public Property TipoPlanilla As String
    Public Property DescripcionCorta As String
    Public Property DescripcionLarga As String
    Public Property Importe As Nullable(Of Decimal)
    Public Property statusPago As Nullable(Of Integer)
    Public Property Fechamodificacion As Nullable(Of Date)
    Public Property UsuarioModificacion As String

    Public Overridable Property ControlAsistencia As ControlAsistencia

End Class
