'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Sunat_statements
    Public Property id As Integer
    Public Property IDSunat As String
    Public Property anio As Nullable(Of Integer)
    Public Property mes As Nullable(Of Integer)
    Public Property importe As Nullable(Of Decimal)
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property UsuarioModificacion As String

End Class
