<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class frmReporteEEF
    Inherits frmMaster

    'Form overrides dispose to clean up the component list.
    <System.Diagnostics.DebuggerNonUserCode()> _
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        Try
            If disposing AndAlso components IsNot Nothing Then
                components.Dispose()
            End If
        Finally
            MyBase.Dispose(disposing)
        End Try
    End Sub

    'Required by the Windows Form Designer
    Private components As System.ComponentModel.IContainer

    'NOTE: The following procedure is required by the Windows Form Designer
    'It can be modified using the Windows Form Designer.  
    'Do not modify it using the code editor.
    <System.Diagnostics.DebuggerStepThrough()> _
    Private Sub InitializeComponent()
        Dim GridBaseStyle1 As Syncfusion.Windows.Forms.Grid.GridBaseStyle = New Syncfusion.Windows.Forms.Grid.GridBaseStyle()
        Dim GridBaseStyle2 As Syncfusion.Windows.Forms.Grid.GridBaseStyle = New Syncfusion.Windows.Forms.Grid.GridBaseStyle()
        Dim GridBaseStyle3 As Syncfusion.Windows.Forms.Grid.GridBaseStyle = New Syncfusion.Windows.Forms.Grid.GridBaseStyle()
        Dim GridBaseStyle4 As Syncfusion.Windows.Forms.Grid.GridBaseStyle = New Syncfusion.Windows.Forms.Grid.GridBaseStyle()
        Dim GridRangeStyle1 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle2 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle3 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle4 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle5 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle6 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle7 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle8 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle9 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle10 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle11 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle12 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle13 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle14 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle15 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle16 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle17 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle18 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle19 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle20 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle21 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle22 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle23 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle24 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle25 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle26 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle27 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle28 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle29 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle30 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle31 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle32 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle33 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle34 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle35 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle36 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle37 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle38 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle39 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle40 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle41 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle42 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle43 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle44 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle45 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle46 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle47 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle48 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle49 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle50 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle51 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle52 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle53 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle54 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle55 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle56 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle57 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle58 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle59 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle60 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle61 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle62 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle63 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle64 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle65 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle66 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle67 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle68 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle69 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle70 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle71 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle72 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle73 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle74 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle75 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle76 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle77 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle78 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle79 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle80 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle81 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle82 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle83 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle84 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle85 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle86 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle87 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle88 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle89 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle90 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle91 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle92 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle93 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle94 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle95 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle96 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle97 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle98 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle99 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle100 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle101 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle102 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle103 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle104 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle105 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle106 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle107 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle108 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle109 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle110 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle111 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle112 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle113 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle114 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle115 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle116 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle117 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle118 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle119 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle120 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle121 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle122 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle123 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle124 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle125 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle126 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle127 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle128 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle129 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle130 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle131 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle132 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle133 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle134 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle135 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle136 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle137 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle138 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle139 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle140 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle141 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle142 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle143 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle144 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle145 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle146 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridBaseStyle5 As Syncfusion.Windows.Forms.Grid.GridBaseStyle = New Syncfusion.Windows.Forms.Grid.GridBaseStyle()
        Dim GridBaseStyle6 As Syncfusion.Windows.Forms.Grid.GridBaseStyle = New Syncfusion.Windows.Forms.Grid.GridBaseStyle()
        Dim GridBaseStyle7 As Syncfusion.Windows.Forms.Grid.GridBaseStyle = New Syncfusion.Windows.Forms.Grid.GridBaseStyle()
        Dim GridBaseStyle8 As Syncfusion.Windows.Forms.Grid.GridBaseStyle = New Syncfusion.Windows.Forms.Grid.GridBaseStyle()
        Dim GridRangeStyle147 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle148 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle149 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle150 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle151 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle152 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle153 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle154 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle155 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle156 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle157 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle158 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle159 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle160 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle161 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle162 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle163 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle164 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle165 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle166 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle167 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle168 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle169 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle170 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle171 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle172 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle173 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle174 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle175 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle176 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle177 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle178 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle179 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle180 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle181 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle182 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle183 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle184 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle185 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle186 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle187 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle188 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle189 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle190 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle191 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle192 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle193 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle194 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle195 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle196 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle197 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle198 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle199 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle200 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle201 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle202 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle203 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle204 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle205 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle206 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle207 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle208 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle209 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle210 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle211 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle212 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle213 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle214 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle215 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle216 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle217 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Me.TabControlAdv1 = New Syncfusion.Windows.Forms.Tools.TabControlAdv()
        Me.TabPageAdv1 = New Syncfusion.Windows.Forms.Tools.TabPageAdv()
        Me.GridControl1 = New Syncfusion.Windows.Forms.Grid.GridControl()
        Me.TabPageAdv2 = New Syncfusion.Windows.Forms.Tools.TabPageAdv()
        Me.GridControl2 = New Syncfusion.Windows.Forms.Grid.GridControl()
        CType(Me.TabControlAdv1, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.TabControlAdv1.SuspendLayout()
        Me.TabPageAdv1.SuspendLayout()
        CType(Me.GridControl1, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.TabPageAdv2.SuspendLayout()
        CType(Me.GridControl2, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.SuspendLayout()
        '
        'TabControlAdv1
        '
        Me.TabControlAdv1.BeforeTouchSize = New System.Drawing.Size(878, 402)
        Me.TabControlAdv1.Controls.Add(Me.TabPageAdv1)
        Me.TabControlAdv1.Controls.Add(Me.TabPageAdv2)
        Me.TabControlAdv1.Dock = System.Windows.Forms.DockStyle.Fill
        Me.TabControlAdv1.FocusOnTabClick = False
        Me.TabControlAdv1.Location = New System.Drawing.Point(0, 0)
        Me.TabControlAdv1.Name = "TabControlAdv1"
        Me.TabControlAdv1.Size = New System.Drawing.Size(878, 402)
        Me.TabControlAdv1.TabIndex = 0
        Me.TabControlAdv1.TabStyle = GetType(Syncfusion.Windows.Forms.Tools.TabRendererMetro)
        '
        'TabPageAdv1
        '
        Me.TabPageAdv1.Controls.Add(Me.GridControl1)
        Me.TabPageAdv1.Image = Nothing
        Me.TabPageAdv1.ImageSize = New System.Drawing.Size(16, 16)
        Me.TabPageAdv1.Location = New System.Drawing.Point(1, 22)
        Me.TabPageAdv1.Name = "TabPageAdv1"
        Me.TabPageAdv1.ShowCloseButton = True
        Me.TabPageAdv1.Size = New System.Drawing.Size(875, 378)
        Me.TabPageAdv1.TabIndex = 1
        Me.TabPageAdv1.Text = "TabPageAdv1"
        Me.TabPageAdv1.ThemesEnabled = False
        '
        'GridControl1
        '
        Me.GridControl1.AlphaBlendSelectionColor = System.Drawing.Color.FromArgb(CType(CType(64, Byte), Integer), CType(CType(94, Byte), Integer), CType(CType(171, Byte), Integer), CType(CType(222, Byte), Integer))
        GridBaseStyle1.Name = "Header"
        GridBaseStyle1.StyleInfo.Borders.Bottom = New Syncfusion.Windows.Forms.Grid.GridBorder(Syncfusion.Windows.Forms.Grid.GridBorderStyle.None)
        GridBaseStyle1.StyleInfo.Borders.Left = New Syncfusion.Windows.Forms.Grid.GridBorder(Syncfusion.Windows.Forms.Grid.GridBorderStyle.None)
        GridBaseStyle1.StyleInfo.Borders.Right = New Syncfusion.Windows.Forms.Grid.GridBorder(Syncfusion.Windows.Forms.Grid.GridBorderStyle.None)
        GridBaseStyle1.StyleInfo.Borders.Top = New Syncfusion.Windows.Forms.Grid.GridBorder(Syncfusion.Windows.Forms.Grid.GridBorderStyle.None)
        GridBaseStyle1.StyleInfo.CellType = "Header"
        GridBaseStyle1.StyleInfo.Font.Bold = True
        GridBaseStyle1.StyleInfo.Interior = New Syncfusion.Drawing.BrushInfo(Syncfusion.Drawing.GradientStyle.Vertical, System.Drawing.Color.FromArgb(CType(CType(203, Byte), Integer), CType(CType(199, Byte), Integer), CType(CType(184, Byte), Integer)), System.Drawing.Color.FromArgb(CType(CType(238, Byte), Integer), CType(CType(234, Byte), Integer), CType(CType(216, Byte), Integer)))
        GridBaseStyle1.StyleInfo.VerticalAlignment = Syncfusion.Windows.Forms.Grid.GridVerticalAlignment.Middle
        GridBaseStyle2.Name = "Standard"
        GridBaseStyle2.StyleInfo.Font.Facename = "Tahoma"
        GridBaseStyle2.StyleInfo.Interior = New Syncfusion.Drawing.BrushInfo(System.Drawing.SystemColors.Window)
        GridBaseStyle3.Name = "Column Header"
        GridBaseStyle3.StyleInfo.BaseStyle = "Header"
        GridBaseStyle3.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Center
        GridBaseStyle4.Name = "Row Header"
        GridBaseStyle4.StyleInfo.BaseStyle = "Header"
        GridBaseStyle4.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Left
        GridBaseStyle4.StyleInfo.Interior = New Syncfusion.Drawing.BrushInfo(Syncfusion.Drawing.GradientStyle.Horizontal, System.Drawing.Color.FromArgb(CType(CType(203, Byte), Integer), CType(CType(199, Byte), Integer), CType(CType(184, Byte), Integer)), System.Drawing.Color.FromArgb(CType(CType(238, Byte), Integer), CType(CType(234, Byte), Integer), CType(CType(216, Byte), Integer)))
        Me.GridControl1.BaseStylesMap.AddRange(New Syncfusion.Windows.Forms.Grid.GridBaseStyle() {GridBaseStyle1, GridBaseStyle2, GridBaseStyle3, GridBaseStyle4})
        Me.GridControl1.ColCount = 14
        Me.GridControl1.ColWidthEntries.AddRange(New Syncfusion.Windows.Forms.Grid.GridColWidth() {New Syncfusion.Windows.Forms.Grid.GridColWidth(0, 35), New Syncfusion.Windows.Forms.Grid.GridColWidth(1, 162), New Syncfusion.Windows.Forms.Grid.GridColWidth(2, 40), New Syncfusion.Windows.Forms.Grid.GridColWidth(3, 39), New Syncfusion.Windows.Forms.Grid.GridColWidth(4, 336), New Syncfusion.Windows.Forms.Grid.GridColWidth(6, 34), New Syncfusion.Windows.Forms.Grid.GridColWidth(13, 72), New Syncfusion.Windows.Forms.Grid.GridColWidth(14, 22)})
        Me.GridControl1.CoveredRanges.AddRange(New Syncfusion.Windows.Forms.Grid.GridRangeInfo() {Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(1, 2, 1, 14), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(2, 2, 2, 14), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(3, 2, 3, 14), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(4, 2, 4, 3), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(6, 2, 6, 3), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(10, 2, 10, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(12, 2, 12, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(13, 3, 13, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(16, 2, 16, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(17, 2, 17, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(18, 2, 18, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(19, 2, 19, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(20, 2, 20, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(21, 2, 21, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(23, 2, 23, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(24, 2, 24, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(25, 2, 25, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(26, 2, 26, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(27, 2, 27, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(28, 2, 28, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(29, 2, 29, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(30, 2, 30, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(32, 3, 32, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(34, 2, 34, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(35, 2, 35, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(36, 2, 36, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(37, 2, 37, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(38, 2, 38, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(39, 2, 39, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(40, 2, 40, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(41, 2, 41, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(42, 2, 42, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(43, 2, 43, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(44, 2, 44, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(48, 3, 48, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(63, 3, 63, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(8, 8, 8, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(10, 8, 10, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(11, 8, 11, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(12, 8, 12, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(13, 8, 13, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(15, 8, 15, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(16, 8, 16, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(17, 8, 17, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(18, 8, 18, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(19, 8, 19, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(20, 8, 20, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(21, 8, 21, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(22, 8, 22, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(23, 8, 23, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(24, 8, 24, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(25, 8, 25, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(28, 9, 28, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(32, 8, 32, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(33, 8, 33, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(41, 9, 41, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(45, 10, 45, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(49, 8, 49, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(51, 8, 51, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(52, 8, 52, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(53, 8, 53, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(57, 8, 57, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(58, 8, 58, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(59, 8, 59, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(60, 8, 60, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(62, 9, 62, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(61, 9, 61, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(63, 9, 63, 12)})
        Me.GridControl1.DefaultGridBorderStyle = Syncfusion.Windows.Forms.Grid.GridBorderStyle.Solid
        Me.GridControl1.DefaultRowHeight = 20
        Me.GridControl1.Dock = System.Windows.Forms.DockStyle.Fill
        Me.GridControl1.Font = New System.Drawing.Font("Segoe UI", 8.25!)
        Me.GridControl1.ForeColor = System.Drawing.Color.Black
        Me.GridControl1.GridOfficeScrollBars = Syncfusion.Windows.Forms.OfficeScrollBars.Metro
        Me.GridControl1.GridVisualStyles = Syncfusion.Windows.Forms.GridVisualStyles.Metro
        'Me.GridControl1.IsSpreadsheetFillSeries = False
        Me.GridControl1.Location = New System.Drawing.Point(0, 0)
        Me.GridControl1.MetroScrollBars = True
        Me.GridControl1.Name = "GridControl1"
        Me.GridControl1.Properties.ForceImmediateRepaint = False
        Me.GridControl1.Properties.GridLineColor = System.Drawing.Color.FromArgb(CType(CType(212, Byte), Integer), CType(CType(212, Byte), Integer), CType(CType(212, Byte), Integer))
        Me.GridControl1.Properties.MarkColHeader = False
        Me.GridControl1.Properties.MarkRowHeader = False
        GridRangeStyle1.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Table
        GridRangeStyle1.StyleInfo.Font.Bold = False
        GridRangeStyle1.StyleInfo.Font.Facename = "Segoe UI"
        GridRangeStyle1.StyleInfo.Font.Italic = False
        GridRangeStyle1.StyleInfo.Font.Size = 8.25!
        GridRangeStyle1.StyleInfo.Font.Strikeout = False
        GridRangeStyle1.StyleInfo.Font.Underline = False
        GridRangeStyle1.StyleInfo.Font.Unit = System.Drawing.GraphicsUnit.Point
        GridRangeStyle1.StyleInfo.TextColor = System.Drawing.Color.Black
        GridRangeStyle2.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(1, 2)
        GridRangeStyle2.StyleInfo.Font.Bold = True
        GridRangeStyle2.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Center
        GridRangeStyle2.StyleInfo.Text = "ESTADO DE SITUACIÓN FINANCIERA "
        GridRangeStyle3.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(2, 2)
        GridRangeStyle3.StyleInfo.Font.Bold = True
        GridRangeStyle3.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Center
        GridRangeStyle3.StyleInfo.Text = "Del 01 de enero Al 31 de diciembre del 2011"
        GridRangeStyle4.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(3, 2)
        GridRangeStyle4.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Center
        GridRangeStyle4.StyleInfo.Text = "(Expresado en Nuevos Soles)"
        GridRangeStyle5.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(4, 2)
        GridRangeStyle5.StyleInfo.Text = "EJERCICIO:"
        GridRangeStyle6.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(4, 4)
        GridRangeStyle6.StyleInfo.Text = "2011"
        GridRangeStyle7.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(5, 2)
        GridRangeStyle7.StyleInfo.Text = "RUC:"
        GridRangeStyle8.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(5, 4)
        GridRangeStyle8.StyleInfo.Text = "20541581813"
        GridRangeStyle9.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(6, 2)
        GridRangeStyle9.StyleInfo.Text = "RAZÓN SOCIAL:"
        GridRangeStyle10.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(6, 4)
        GridRangeStyle10.StyleInfo.Text = "CESAL CONSTRUCTORES EIRL "
        GridRangeStyle11.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(7, 5)
        GridRangeStyle11.StyleInfo.Text = ""
        GridRangeStyle12.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(8, 2)
        GridRangeStyle12.StyleInfo.Text = "ACTIVO "
        GridRangeStyle13.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(8, 8)
        GridRangeStyle13.StyleInfo.Text = "PASIVO Y PATRIMONIO "
        GridRangeStyle14.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(8, 13)
        GridRangeStyle14.StyleInfo.Text = "HISTORICO"
        GridRangeStyle15.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(10, 2)
        GridRangeStyle15.StyleInfo.Text = "ACTIVO CORRIENTE"
        GridRangeStyle16.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(10, 8)
        GridRangeStyle16.StyleInfo.Text = "PASIVO CORRIENTE"
        GridRangeStyle17.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(11, 7)
        GridRangeStyle17.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle17.StyleInfo.Text = "40"
        GridRangeStyle18.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(11, 8)
        GridRangeStyle18.StyleInfo.Text = "Tributos, aportes al sistema de pensiones y de salud por pagar"
        GridRangeStyle19.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(11, 13, 25, 13)
        GridRangeStyle19.StyleInfo.CellType = "Currency"
        GridRangeStyle19.StyleInfo.Text = "0.00"
        GridRangeStyle20.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(12, 1)
        GridRangeStyle20.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle20.StyleInfo.Text = "10"
        GridRangeStyle21.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(12, 2)
        GridRangeStyle21.StyleInfo.Text = "efectvo y equivalentes de efectivo "
        GridRangeStyle22.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(12, 5, 29, 5)
        GridRangeStyle22.StyleInfo.CellType = "Currency"
        GridRangeStyle22.StyleInfo.Text = "0.00"
        GridRangeStyle23.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(12, 8)
        GridRangeStyle23.StyleInfo.Text = "Puede tener saldos positivos o negativos, pero se muestra el saldo final "
        GridRangeStyle24.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(13, 2)
        GridRangeStyle24.StyleInfo.Text = "104"
        GridRangeStyle25.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(13, 3)
        GridRangeStyle25.StyleInfo.Text = "Cuentas corrientes en instituciones financieras"
        GridRangeStyle26.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(13, 8)
        GridRangeStyle26.StyleInfo.Text = "Activo/Pasivo"
        GridRangeStyle27.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(14, 3)
        GridRangeStyle27.StyleInfo.Text = "1041"
        GridRangeStyle28.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(14, 4)
        GridRangeStyle28.StyleInfo.Text = "Cuentas corrientes operativas"
        GridRangeStyle29.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(15, 3)
        GridRangeStyle29.StyleInfo.Text = "1042"
        GridRangeStyle30.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(15, 4)
        GridRangeStyle30.StyleInfo.Text = "cuentas corrientes para fines específicos"
        GridRangeStyle31.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(15, 7)
        GridRangeStyle31.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle31.StyleInfo.Text = "41"
        GridRangeStyle32.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(15, 8)
        GridRangeStyle32.StyleInfo.Text = "Remuneraciones y particicipaciones por pagar "
        GridRangeStyle33.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(16, 1)
        GridRangeStyle33.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle33.StyleInfo.Text = "11"
        GridRangeStyle34.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(16, 2)
        GridRangeStyle34.StyleInfo.Text = "Inversiones financieras"
        GridRangeStyle35.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(16, 7)
        GridRangeStyle35.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle35.StyleInfo.Text = "42"
        GridRangeStyle36.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(16, 8)
        GridRangeStyle36.StyleInfo.Text = "Cuentas por pagar comerciales - Terceros"
        GridRangeStyle37.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(17, 1)
        GridRangeStyle37.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle37.StyleInfo.Text = "12"
        GridRangeStyle38.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(17, 2)
        GridRangeStyle38.StyleInfo.Text = "Cuentas por cobrar comerciales - terceros"
        GridRangeStyle39.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(17, 7)
        GridRangeStyle39.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle39.StyleInfo.Text = "122"
        GridRangeStyle40.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(17, 8)
        GridRangeStyle40.StyleInfo.Text = "Anticipos de clientes "
        GridRangeStyle41.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(18, 1)
        GridRangeStyle41.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle41.StyleInfo.Text = "422"
        GridRangeStyle42.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(18, 2)
        GridRangeStyle42.StyleInfo.Text = "Anticipos a proveedores "
        GridRangeStyle43.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(18, 7)
        GridRangeStyle43.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle43.StyleInfo.Text = "43"
        GridRangeStyle44.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(18, 8)
        GridRangeStyle44.StyleInfo.Text = "Cuentas por pagar comerciales - Relacionadas"
        GridRangeStyle45.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(19, 1)
        GridRangeStyle45.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle45.StyleInfo.Text = "432"
        GridRangeStyle46.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(19, 2)
        GridRangeStyle46.StyleInfo.Text = "Anticipos otorgados"
        GridRangeStyle47.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(19, 7)
        GridRangeStyle47.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle47.StyleInfo.Text = "132"
        GridRangeStyle48.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(19, 8)
        GridRangeStyle48.StyleInfo.Text = "Anticipos recibidos "
        GridRangeStyle49.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(20, 1)
        GridRangeStyle49.StyleInfo.Font.Underline = False
        GridRangeStyle49.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle49.StyleInfo.Text = "13"
        GridRangeStyle50.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(20, 2)
        GridRangeStyle50.StyleInfo.Text = "Cuentas por cobrar comerciales - relacionadas"
        GridRangeStyle51.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(20, 7)
        GridRangeStyle51.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle51.StyleInfo.Text = "44"
        GridRangeStyle52.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(20, 8)
        GridRangeStyle52.StyleInfo.Text = "Cuentas por pagar a los accionistas (socios), directores y gerentes"
        GridRangeStyle53.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(21, 1)
        GridRangeStyle53.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle53.StyleInfo.Text = "14"
        GridRangeStyle54.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(21, 2)
        GridRangeStyle54.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Left
        GridRangeStyle54.StyleInfo.Text = "Cuentas por cobrar al personal, a los accionistas (socios), directores y gerentes" & _
    ""
        GridRangeStyle55.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(21, 3, 21, 4)
        GridRangeStyle55.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Left
        GridRangeStyle56.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(21, 7)
        GridRangeStyle56.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle56.StyleInfo.Text = "45"
        GridRangeStyle57.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(21, 8)
        GridRangeStyle57.StyleInfo.Text = "Obligaciones financieras"
        GridRangeStyle58.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(22, 1)
        GridRangeStyle58.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle58.StyleInfo.Text = "15"
        GridRangeStyle59.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(22, 7)
        GridRangeStyle59.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle59.StyleInfo.Text = "46"
        GridRangeStyle60.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(22, 8)
        GridRangeStyle60.StyleInfo.Text = "Cuentas por pagar diversas-terceros "
        GridRangeStyle61.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(23, 1)
        GridRangeStyle61.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle61.StyleInfo.Text = "16"
        GridRangeStyle62.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(23, 2)
        GridRangeStyle62.StyleInfo.Text = "Cuentas por cobrar diversas - terceros"
        GridRangeStyle63.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(23, 7)
        GridRangeStyle63.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle63.StyleInfo.Text = "47"
        GridRangeStyle64.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(23, 8)
        GridRangeStyle64.StyleInfo.Text = "Cuentas por pagar diversas-relacionadas "
        GridRangeStyle65.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(24, 1)
        GridRangeStyle65.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle65.StyleInfo.Text = "17"
        GridRangeStyle66.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(24, 2)
        GridRangeStyle66.StyleInfo.Text = "Cuentas por cobrar diversas - relacionadas"
        GridRangeStyle67.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(24, 7)
        GridRangeStyle67.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle67.StyleInfo.Text = "48"
        GridRangeStyle68.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(24, 8)
        GridRangeStyle68.StyleInfo.Text = "Provisiones"
        GridRangeStyle69.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(25, 1)
        GridRangeStyle69.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle69.StyleInfo.Text = "18"
        GridRangeStyle70.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(25, 2)
        GridRangeStyle70.StyleInfo.Text = "Servicios y otros contratados por anticipado"
        GridRangeStyle71.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(25, 7)
        GridRangeStyle71.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle71.StyleInfo.Text = "49"
        GridRangeStyle72.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(25, 8)
        GridRangeStyle72.StyleInfo.Text = "Pasivo diferido "
        GridRangeStyle73.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(26, 1)
        GridRangeStyle73.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle73.StyleInfo.Text = "19"
        GridRangeStyle74.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(26, 2)
        GridRangeStyle74.StyleInfo.Text = "Estimación de cuentas de cobranza dudosa (pendiente)"
        GridRangeStyle75.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(27, 1)
        GridRangeStyle75.StyleInfo.Text = "20,21,22,23,24,25,26,27,28 y 29"
        GridRangeStyle76.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(27, 2)
        GridRangeStyle76.StyleInfo.Text = "Inventarios "
        GridRangeStyle77.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(28, 1)
        GridRangeStyle77.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle77.StyleInfo.Text = "40"
        GridRangeStyle78.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(28, 2)
        GridRangeStyle78.StyleInfo.Text = "Tributos, aportes al sistema de pensiones y de salud por pagar"
        GridRangeStyle79.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(28, 9)
        GridRangeStyle79.StyleInfo.Text = "TOTAL PASIVO CORRIENTE"
        GridRangeStyle80.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(28, 13)
        GridRangeStyle80.StyleInfo.CellType = "Currency"
        GridRangeStyle80.StyleInfo.Text = "0.00"
        GridRangeStyle81.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(29, 2)
        GridRangeStyle81.StyleInfo.Text = "Puede tener saldos positivos o negativos, pero se muestra el saldo final "
        GridRangeStyle82.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(30, 2)
        GridRangeStyle82.StyleInfo.Text = "Activo/Pasivo"
        GridRangeStyle83.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(32, 3)
        GridRangeStyle83.StyleInfo.Text = "TOTAL ACTVO CORRIENTE"
        GridRangeStyle84.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(32, 5)
        GridRangeStyle84.StyleInfo.CellType = "Currency"
        GridRangeStyle84.StyleInfo.Text = "0"
        GridRangeStyle85.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(32, 8)
        GridRangeStyle85.StyleInfo.Text = "PASIVO NO CORRIENTE"
        GridRangeStyle86.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(33, 7)
        GridRangeStyle86.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle86.StyleInfo.Text = "47"
        GridRangeStyle87.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(33, 8)
        GridRangeStyle87.StyleInfo.Text = "Cuentas por pagar diversas-relacionadas "
        GridRangeStyle88.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(33, 13)
        GridRangeStyle88.StyleInfo.CellType = "Currency"
        GridRangeStyle88.StyleInfo.Text = "0.00"
        GridRangeStyle89.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(34, 2)
        GridRangeStyle89.StyleInfo.Text = "ACTIVO NO CORRIENTE"
        GridRangeStyle90.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(35, 1)
        GridRangeStyle90.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle90.StyleInfo.Text = "30"
        GridRangeStyle91.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(35, 2)
        GridRangeStyle91.StyleInfo.Text = "Inversiones mobiliarias"
        GridRangeStyle92.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(35, 5, 44, 5)
        GridRangeStyle92.StyleInfo.CellType = "Currency"
        GridRangeStyle92.StyleInfo.Text = "0.00"
        GridRangeStyle93.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(36, 1)
        GridRangeStyle93.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle93.StyleInfo.Text = "31"
        GridRangeStyle94.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(36, 2)
        GridRangeStyle94.StyleInfo.Text = "Inversiones inmobiliarias"
        GridRangeStyle95.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(37, 1)
        GridRangeStyle95.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle95.StyleInfo.Text = "32"
        GridRangeStyle96.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(37, 2)
        GridRangeStyle96.StyleInfo.Text = "Activos adquiridos en arrendamiento financiero "
        GridRangeStyle97.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(38, 1)
        GridRangeStyle97.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle97.StyleInfo.Text = "33"
        GridRangeStyle98.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(38, 2)
        GridRangeStyle98.StyleInfo.Text = "Inmuebles, maquinaria y equipo"
        GridRangeStyle99.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(39, 1)
        GridRangeStyle99.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle99.StyleInfo.Text = "34"
        GridRangeStyle100.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(39, 2)
        GridRangeStyle100.StyleInfo.Text = "Intangibles "
        GridRangeStyle101.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(40, 1)
        GridRangeStyle101.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle101.StyleInfo.Text = "35"
        GridRangeStyle102.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(40, 2)
        GridRangeStyle102.StyleInfo.Text = "Activos biológicos "
        GridRangeStyle103.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(41, 1)
        GridRangeStyle103.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle103.StyleInfo.Text = "36"
        GridRangeStyle104.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(41, 2)
        GridRangeStyle104.StyleInfo.Text = "Desvalorización de activo inmovilizado "
        GridRangeStyle105.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(41, 9)
        GridRangeStyle105.StyleInfo.Text = "TOTAL PASIVO NO CORRIENTE"
        GridRangeStyle106.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(41, 13)
        GridRangeStyle106.StyleInfo.CellType = "Currency"
        GridRangeStyle106.StyleInfo.Text = "0.00"
        GridRangeStyle107.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(42, 1)
        GridRangeStyle107.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle107.StyleInfo.Text = "37"
        GridRangeStyle108.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(42, 2)
        GridRangeStyle108.StyleInfo.Text = "Activo diferido "
        GridRangeStyle109.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(43, 1)
        GridRangeStyle109.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle109.StyleInfo.Text = "38"
        GridRangeStyle110.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(43, 2)
        GridRangeStyle110.StyleInfo.Text = "Otros activos "
        GridRangeStyle111.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(44, 1)
        GridRangeStyle111.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle111.StyleInfo.Text = "39"
        GridRangeStyle112.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(44, 2)
        GridRangeStyle112.StyleInfo.Text = "Depreciación, amortización y agotamiento acumulados (pendiente)"
        GridRangeStyle113.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(45, 10)
        GridRangeStyle113.StyleInfo.Text = "TOTAL PASIVO "
        GridRangeStyle114.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(45, 13)
        GridRangeStyle114.StyleInfo.CellType = "Currency"
        GridRangeStyle114.StyleInfo.Text = "0.00"
        GridRangeStyle115.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(48, 3)
        GridRangeStyle115.StyleInfo.Text = "TOTAL ACTIVO NO CORRIENTE"
        GridRangeStyle116.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(48, 5)
        GridRangeStyle116.StyleInfo.CellType = "Currency"
        GridRangeStyle116.StyleInfo.Text = "0.00"
        GridRangeStyle117.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(49, 8)
        GridRangeStyle117.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Left
        GridRangeStyle117.StyleInfo.Text = "PATRIMONIO NETO "
        GridRangeStyle118.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(49, 9, 49, 12)
        GridRangeStyle118.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Left
        GridRangeStyle119.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(50, 7)
        GridRangeStyle119.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle119.StyleInfo.Text = "50"
        GridRangeStyle120.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(50, 8)
        GridRangeStyle120.StyleInfo.Text = "Capital"
        GridRangeStyle121.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(50, 13, 61, 13)
        GridRangeStyle121.StyleInfo.CellType = "Currency"
        GridRangeStyle121.StyleInfo.Text = "0.00"
        GridRangeStyle122.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(51, 7)
        GridRangeStyle122.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle122.StyleInfo.Text = "51"
        GridRangeStyle123.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(51, 8)
        GridRangeStyle123.StyleInfo.Text = "Acciones de Inversión"
        GridRangeStyle124.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(52, 7)
        GridRangeStyle124.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle124.StyleInfo.Text = "52"
        GridRangeStyle125.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(52, 8)
        GridRangeStyle125.StyleInfo.Text = "Capital adicional "
        GridRangeStyle126.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(53, 7)
        GridRangeStyle126.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle126.StyleInfo.Text = "53"
        GridRangeStyle127.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(53, 8)
        GridRangeStyle127.StyleInfo.Text = ""
        GridRangeStyle128.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(54, 7)
        GridRangeStyle128.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle128.StyleInfo.Text = "54"
        GridRangeStyle129.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(55, 7)
        GridRangeStyle129.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle129.StyleInfo.Text = "55"
        GridRangeStyle130.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(56, 7)
        GridRangeStyle130.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle130.StyleInfo.Text = "56"
        GridRangeStyle131.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(56, 8)
        GridRangeStyle131.StyleInfo.Text = "Resultados no realizados"
        GridRangeStyle132.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(57, 7)
        GridRangeStyle132.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle132.StyleInfo.Text = "57"
        GridRangeStyle133.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(57, 8)
        GridRangeStyle133.StyleInfo.Text = "Excedente de revaluación "
        GridRangeStyle134.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(58, 7)
        GridRangeStyle134.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle134.StyleInfo.Text = "58"
        GridRangeStyle135.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(58, 8)
        GridRangeStyle135.StyleInfo.Text = "Reservas"
        GridRangeStyle136.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(59, 7, 60, 7)
        GridRangeStyle136.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle136.StyleInfo.Text = "59"
        GridRangeStyle137.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(59, 8)
        GridRangeStyle137.StyleInfo.Text = "Resultados acumulados "
        GridRangeStyle138.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(60, 8)
        GridRangeStyle138.StyleInfo.Text = "Resultado del periodo"
        GridRangeStyle139.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(61, 7)
        GridRangeStyle139.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle139.StyleInfo.Text = ""
        GridRangeStyle140.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(61, 8)
        GridRangeStyle140.StyleInfo.Text = ""
        GridRangeStyle141.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(61, 9)
        GridRangeStyle141.StyleInfo.Text = "TOTAL PATRIMONIO NETO"
        GridRangeStyle142.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(62, 9)
        GridRangeStyle142.StyleInfo.Text = ""
        GridRangeStyle143.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(63, 3)
        GridRangeStyle143.StyleInfo.Text = "TOTAL ACTIVO "
        GridRangeStyle144.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(63, 5)
        GridRangeStyle144.StyleInfo.CellType = "Currency"
        GridRangeStyle144.StyleInfo.Text = "0.00"
        GridRangeStyle145.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(63, 9)
        GridRangeStyle145.StyleInfo.Text = "TOTAL PASIVO Y PATRIMONIO NETO "
        GridRangeStyle146.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(63, 13)
        GridRangeStyle146.StyleInfo.CellType = "Currency"
        GridRangeStyle146.StyleInfo.Text = "0.00"
        Me.GridControl1.RangeStyles.AddRange(New Syncfusion.Windows.Forms.Grid.GridRangeStyle() {GridRangeStyle1, GridRangeStyle2, GridRangeStyle3, GridRangeStyle4, GridRangeStyle5, GridRangeStyle6, GridRangeStyle7, GridRangeStyle8, GridRangeStyle9, GridRangeStyle10, GridRangeStyle11, GridRangeStyle12, GridRangeStyle13, GridRangeStyle14, GridRangeStyle15, GridRangeStyle16, GridRangeStyle17, GridRangeStyle18, GridRangeStyle19, GridRangeStyle20, GridRangeStyle21, GridRangeStyle22, GridRangeStyle23, GridRangeStyle24, GridRangeStyle25, GridRangeStyle26, GridRangeStyle27, GridRangeStyle28, GridRangeStyle29, GridRangeStyle30, GridRangeStyle31, GridRangeStyle32, GridRangeStyle33, GridRangeStyle34, GridRangeStyle35, GridRangeStyle36, GridRangeStyle37, GridRangeStyle38, GridRangeStyle39, GridRangeStyle40, GridRangeStyle41, GridRangeStyle42, GridRangeStyle43, GridRangeStyle44, GridRangeStyle45, GridRangeStyle46, GridRangeStyle47, GridRangeStyle48, GridRangeStyle49, GridRangeStyle50, GridRangeStyle51, GridRangeStyle52, GridRangeStyle53, GridRangeStyle54, GridRangeStyle55, GridRangeStyle56, GridRangeStyle57, GridRangeStyle58, GridRangeStyle59, GridRangeStyle60, GridRangeStyle61, GridRangeStyle62, GridRangeStyle63, GridRangeStyle64, GridRangeStyle65, GridRangeStyle66, GridRangeStyle67, GridRangeStyle68, GridRangeStyle69, GridRangeStyle70, GridRangeStyle71, GridRangeStyle72, GridRangeStyle73, GridRangeStyle74, GridRangeStyle75, GridRangeStyle76, GridRangeStyle77, GridRangeStyle78, GridRangeStyle79, GridRangeStyle80, GridRangeStyle81, GridRangeStyle82, GridRangeStyle83, GridRangeStyle84, GridRangeStyle85, GridRangeStyle86, GridRangeStyle87, GridRangeStyle88, GridRangeStyle89, GridRangeStyle90, GridRangeStyle91, GridRangeStyle92, GridRangeStyle93, GridRangeStyle94, GridRangeStyle95, GridRangeStyle96, GridRangeStyle97, GridRangeStyle98, GridRangeStyle99, GridRangeStyle100, GridRangeStyle101, GridRangeStyle102, GridRangeStyle103, GridRangeStyle104, GridRangeStyle105, GridRangeStyle106, GridRangeStyle107, GridRangeStyle108, GridRangeStyle109, GridRangeStyle110, GridRangeStyle111, GridRangeStyle112, GridRangeStyle113, GridRangeStyle114, GridRangeStyle115, GridRangeStyle116, GridRangeStyle117, GridRangeStyle118, GridRangeStyle119, GridRangeStyle120, GridRangeStyle121, GridRangeStyle122, GridRangeStyle123, GridRangeStyle124, GridRangeStyle125, GridRangeStyle126, GridRangeStyle127, GridRangeStyle128, GridRangeStyle129, GridRangeStyle130, GridRangeStyle131, GridRangeStyle132, GridRangeStyle133, GridRangeStyle134, GridRangeStyle135, GridRangeStyle136, GridRangeStyle137, GridRangeStyle138, GridRangeStyle139, GridRangeStyle140, GridRangeStyle141, GridRangeStyle142, GridRangeStyle143, GridRangeStyle144, GridRangeStyle145, GridRangeStyle146})
        Me.GridControl1.RightToLeft = System.Windows.Forms.RightToLeft.No
        Me.GridControl1.RowCount = 63
        Me.GridControl1.RowHeightEntries.AddRange(New Syncfusion.Windows.Forms.Grid.GridRowHeight() {New Syncfusion.Windows.Forms.Grid.GridRowHeight(0, 25)})
        Me.GridControl1.SerializeCellsBehavior = Syncfusion.Windows.Forms.Grid.GridSerializeCellsBehavior.SerializeAsRangeStylesIntoCode
        Me.GridControl1.Size = New System.Drawing.Size(875, 378)
        Me.GridControl1.SmartSizeBox = False
        'Me.GridControl1.SpreadsheetLikeSelection = False
        Me.GridControl1.TabIndex = 0
        Me.GridControl1.ThemesEnabled = True
        Me.GridControl1.UseRightToLeftCompatibleTextBox = True
        '
        'TabPageAdv2
        '
        Me.TabPageAdv2.Controls.Add(Me.GridControl2)
        Me.TabPageAdv2.Image = Nothing
        Me.TabPageAdv2.ImageSize = New System.Drawing.Size(16, 16)
        Me.TabPageAdv2.Location = New System.Drawing.Point(1, 22)
        Me.TabPageAdv2.Name = "TabPageAdv2"
        Me.TabPageAdv2.ShowCloseButton = True
        Me.TabPageAdv2.Size = New System.Drawing.Size(875, 378)
        Me.TabPageAdv2.TabIndex = 2
        Me.TabPageAdv2.Text = "TabPageAdv2"
        Me.TabPageAdv2.ThemesEnabled = False
        '
        'GridControl2
        '
        Me.GridControl2.AlphaBlendSelectionColor = System.Drawing.Color.FromArgb(CType(CType(64, Byte), Integer), CType(CType(94, Byte), Integer), CType(CType(171, Byte), Integer), CType(CType(222, Byte), Integer))
        GridBaseStyle5.Name = "Header"
        GridBaseStyle5.StyleInfo.Borders.Bottom = New Syncfusion.Windows.Forms.Grid.GridBorder(Syncfusion.Windows.Forms.Grid.GridBorderStyle.None)
        GridBaseStyle5.StyleInfo.Borders.Left = New Syncfusion.Windows.Forms.Grid.GridBorder(Syncfusion.Windows.Forms.Grid.GridBorderStyle.None)
        GridBaseStyle5.StyleInfo.Borders.Right = New Syncfusion.Windows.Forms.Grid.GridBorder(Syncfusion.Windows.Forms.Grid.GridBorderStyle.None)
        GridBaseStyle5.StyleInfo.Borders.Top = New Syncfusion.Windows.Forms.Grid.GridBorder(Syncfusion.Windows.Forms.Grid.GridBorderStyle.None)
        GridBaseStyle5.StyleInfo.CellType = "Header"
        GridBaseStyle5.StyleInfo.Font.Bold = True
        GridBaseStyle5.StyleInfo.Interior = New Syncfusion.Drawing.BrushInfo(Syncfusion.Drawing.GradientStyle.Vertical, System.Drawing.Color.FromArgb(CType(CType(203, Byte), Integer), CType(CType(199, Byte), Integer), CType(CType(184, Byte), Integer)), System.Drawing.Color.FromArgb(CType(CType(238, Byte), Integer), CType(CType(234, Byte), Integer), CType(CType(216, Byte), Integer)))
        GridBaseStyle5.StyleInfo.VerticalAlignment = Syncfusion.Windows.Forms.Grid.GridVerticalAlignment.Middle
        GridBaseStyle6.Name = "Standard"
        GridBaseStyle6.StyleInfo.Font.Facename = "Tahoma"
        GridBaseStyle6.StyleInfo.Interior = New Syncfusion.Drawing.BrushInfo(System.Drawing.SystemColors.Window)
        GridBaseStyle7.Name = "Column Header"
        GridBaseStyle7.StyleInfo.BaseStyle = "Header"
        GridBaseStyle7.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Center
        GridBaseStyle8.Name = "Row Header"
        GridBaseStyle8.StyleInfo.BaseStyle = "Header"
        GridBaseStyle8.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Left
        GridBaseStyle8.StyleInfo.Interior = New Syncfusion.Drawing.BrushInfo(Syncfusion.Drawing.GradientStyle.Horizontal, System.Drawing.Color.FromArgb(CType(CType(203, Byte), Integer), CType(CType(199, Byte), Integer), CType(CType(184, Byte), Integer)), System.Drawing.Color.FromArgb(CType(CType(238, Byte), Integer), CType(CType(234, Byte), Integer), CType(CType(216, Byte), Integer)))
        Me.GridControl2.BaseStylesMap.AddRange(New Syncfusion.Windows.Forms.Grid.GridBaseStyle() {GridBaseStyle5, GridBaseStyle6, GridBaseStyle7, GridBaseStyle8})
        Me.GridControl2.ColCount = 8
        Me.GridControl2.ColWidthEntries.AddRange(New Syncfusion.Windows.Forms.Grid.GridColWidth() {New Syncfusion.Windows.Forms.Grid.GridColWidth(0, 35), New Syncfusion.Windows.Forms.Grid.GridColWidth(2, 102)})
        Me.GridControl2.CoveredRanges.AddRange(New Syncfusion.Windows.Forms.Grid.GridRangeInfo() {Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(4, 2, 4, 7), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(5, 2, 5, 7), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(6, 2, 6, 7), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(14, 2, 14, 6), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(15, 2, 15, 6), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(16, 2, 16, 6), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(17, 3, 17, 6), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(19, 2, 19, 6), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(20, 3, 20, 6), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(23, 2, 23, 6), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(24, 2, 24, 6), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(25, 2, 25, 6), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(26, 2, 26, 6), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(27, 3, 27, 6), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(29, 2, 29, 6), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(30, 2, 30, 6), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(32, 2, 32, 6), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(33, 2, 33, 6), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(34, 2, 34, 6), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(36, 3, 36, 6), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(37, 3, 37, 6), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(38, 2, 38, 6), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(39, 2, 39, 6), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(41, 3, 41, 6), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(42, 2, 42, 6), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(43, 2, 43, 6), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(45, 3, 45, 6), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(46, 2, 46, 6), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(48, 3, 48, 6), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(50, 2, 50, 6), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(51, 3, 51, 6), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(52, 3, 52, 6), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(53, 3, 53, 6), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(54, 3, 54, 6), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(55, 3, 55, 6), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(10, 4, 10, 6), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(9, 4, 9, 6)})
        Me.GridControl2.DefaultGridBorderStyle = Syncfusion.Windows.Forms.Grid.GridBorderStyle.Solid
        Me.GridControl2.DefaultRowHeight = 20
        Me.GridControl2.Dock = System.Windows.Forms.DockStyle.Fill
        Me.GridControl2.Font = New System.Drawing.Font("Tahoma", 9.0!)
        Me.GridControl2.ForeColor = System.Drawing.SystemColors.ControlText
        Me.GridControl2.GridOfficeScrollBars = Syncfusion.Windows.Forms.OfficeScrollBars.Metro
        Me.GridControl2.GridVisualStyles = Syncfusion.Windows.Forms.GridVisualStyles.Metro
        'Me.GridControl2.IsSpreadsheetFillSeries = False
        Me.GridControl2.Location = New System.Drawing.Point(0, 0)
        Me.GridControl2.MetroScrollBars = True
        Me.GridControl2.Name = "GridControl2"
        Me.GridControl2.Properties.ForceImmediateRepaint = False
        Me.GridControl2.Properties.GridLineColor = System.Drawing.Color.FromArgb(CType(CType(212, Byte), Integer), CType(CType(212, Byte), Integer), CType(CType(212, Byte), Integer))
        Me.GridControl2.Properties.MarkColHeader = False
        Me.GridControl2.Properties.MarkRowHeader = False
        GridRangeStyle147.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Table
        GridRangeStyle147.StyleInfo.Font.Bold = False
        GridRangeStyle147.StyleInfo.Font.Facename = "Tahoma"
        GridRangeStyle147.StyleInfo.Font.Italic = False
        GridRangeStyle147.StyleInfo.Font.Size = 9.0!
        GridRangeStyle147.StyleInfo.Font.Strikeout = False
        GridRangeStyle147.StyleInfo.Font.Underline = False
        GridRangeStyle147.StyleInfo.Font.Unit = System.Drawing.GraphicsUnit.Point
        GridRangeStyle147.StyleInfo.TextColor = System.Drawing.Color.Black
        GridRangeStyle148.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(4, 2)
        GridRangeStyle148.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Center
        GridRangeStyle148.StyleInfo.Text = "ESTADO DE RESULTADOS POR FUNCIÓN "
        GridRangeStyle149.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(5, 2)
        GridRangeStyle149.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Center
        GridRangeStyle149.StyleInfo.Text = "Del 01 de Enero  AL  31.12.2011"
        GridRangeStyle150.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(6, 2)
        GridRangeStyle150.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Center
        GridRangeStyle150.StyleInfo.Text = "     (Expresado en nuevos soles)"
        GridRangeStyle151.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(6, 3, 6, 7)
        GridRangeStyle151.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Center
        GridRangeStyle152.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(8, 2)
        GridRangeStyle152.StyleInfo.Text = "EJERCICIO:"
        GridRangeStyle153.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(8, 4)
        GridRangeStyle153.StyleInfo.Text = "2011"
        GridRangeStyle154.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(9, 2)
        GridRangeStyle154.StyleInfo.Text = "RUC:"
        GridRangeStyle155.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(9, 4)
        GridRangeStyle155.StyleInfo.Text = "205222124"
        GridRangeStyle156.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(10, 2)
        GridRangeStyle156.StyleInfo.Text = "RAZON SOCIAL:"
        GridRangeStyle157.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(10, 4)
        GridRangeStyle157.StyleInfo.Text = "CESAL CONSTRUCTORES"
        GridRangeStyle158.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(12, 2)
        GridRangeStyle158.StyleInfo.Text = "DESCRIPCION"
        GridRangeStyle159.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(12, 7)
        GridRangeStyle159.StyleInfo.Text = "S/."
        GridRangeStyle160.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(14, 1)
        GridRangeStyle160.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle160.StyleInfo.Text = "70"
        GridRangeStyle161.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(14, 2)
        GridRangeStyle161.StyleInfo.Text = "Ventas Netas (ingresos operacionales)"
        GridRangeStyle162.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(14, 7, 17, 7)
        GridRangeStyle162.StyleInfo.CellType = "Currency"
        GridRangeStyle162.StyleInfo.Text = "0.00"
        GridRangeStyle163.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(14, 8)
        GridRangeStyle163.StyleInfo.Text = "704101"
        GridRangeStyle164.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(15, 1)
        GridRangeStyle164.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle164.StyleInfo.Text = "73"
        GridRangeStyle165.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(15, 2)
        GridRangeStyle165.StyleInfo.Text = "Descuentos, rebajas y bonificaciones obtenidos "
        GridRangeStyle166.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(16, 1)
        GridRangeStyle166.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle166.StyleInfo.Text = "74"
        GridRangeStyle167.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(16, 2)
        GridRangeStyle167.StyleInfo.Text = "Descuentos, rebajas y bonificaciones concedidos "
        GridRangeStyle168.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(17, 3)
        GridRangeStyle168.StyleInfo.Text = "Total Ingresos Brutos "
        GridRangeStyle169.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(19, 1)
        GridRangeStyle169.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle169.StyleInfo.Text = "69"
        GridRangeStyle170.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(19, 2)
        GridRangeStyle170.StyleInfo.Text = "Costo de Ventas "
        GridRangeStyle171.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(19, 7, 20, 7)
        GridRangeStyle171.StyleInfo.CellType = "Currency"
        GridRangeStyle171.StyleInfo.Text = "0.00"
        GridRangeStyle172.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(19, 8)
        GridRangeStyle172.StyleInfo.Text = "69211"
        GridRangeStyle173.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(20, 3)
        GridRangeStyle173.StyleInfo.Text = "Utilidad Bruta "
        GridRangeStyle174.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(23, 1)
        GridRangeStyle174.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle174.StyleInfo.Text = "94"
        GridRangeStyle175.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(23, 2)
        GridRangeStyle175.StyleInfo.Text = "Gastos de Administración "
        GridRangeStyle176.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(23, 7, 27, 7)
        GridRangeStyle176.StyleInfo.CellType = "Currency"
        GridRangeStyle176.StyleInfo.Text = "0.00"
        GridRangeStyle177.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(23, 8)
        GridRangeStyle177.StyleInfo.Text = "943"
        GridRangeStyle178.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(24, 1)
        GridRangeStyle178.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle178.StyleInfo.Text = "95"
        GridRangeStyle179.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(24, 2)
        GridRangeStyle179.StyleInfo.Text = "Gastos de Venta"
        GridRangeStyle180.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(25, 1)
        GridRangeStyle180.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle180.StyleInfo.Text = "96"
        GridRangeStyle181.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(25, 2)
        GridRangeStyle181.StyleInfo.Text = "Gastos Operacionales "
        GridRangeStyle182.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(26, 1)
        GridRangeStyle182.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle182.StyleInfo.Text = "97"
        GridRangeStyle183.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(26, 2)
        GridRangeStyle183.StyleInfo.Text = "Gastos Financieros "
        GridRangeStyle184.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(27, 3)
        GridRangeStyle184.StyleInfo.Text = "Utilidad Operativa "
        GridRangeStyle185.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(29, 2)
        GridRangeStyle185.StyleInfo.Font.Bold = True
        GridRangeStyle185.StyleInfo.Text = "Otros Ingresos y/o Gastos"
        GridRangeStyle186.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(30, 1)
        GridRangeStyle186.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle186.StyleInfo.Text = "77"
        GridRangeStyle187.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(30, 2)
        GridRangeStyle187.StyleInfo.Text = "Ingresos Financieros "
        GridRangeStyle188.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(30, 7)
        GridRangeStyle188.StyleInfo.CellType = "Currency"
        GridRangeStyle188.StyleInfo.Text = "0.00"
        GridRangeStyle189.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(30, 8)
        GridRangeStyle189.StyleInfo.CellType = "TextBox"
        GridRangeStyle190.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(32, 1)
        GridRangeStyle190.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle190.StyleInfo.Text = "75-76"
        GridRangeStyle191.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(32, 2)
        GridRangeStyle191.StyleInfo.Text = "Otros Ingresos"
        GridRangeStyle192.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(32, 7, 33, 7)
        GridRangeStyle192.StyleInfo.CellType = "Currency"
        GridRangeStyle192.StyleInfo.Text = "0.00"
        GridRangeStyle193.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(32, 8, 33, 8)
        GridRangeStyle193.StyleInfo.CellType = "TextBox"
        GridRangeStyle194.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(33, 2)
        GridRangeStyle194.StyleInfo.Text = "Otros Gastos"
        GridRangeStyle195.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(34, 2)
        GridRangeStyle195.StyleInfo.Text = "Resultado por Exposición a la Inflación"
        GridRangeStyle196.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(36, 3)
        GridRangeStyle196.StyleInfo.Text = "Resultados Antes de Participaciones, Impuesto "
        GridRangeStyle197.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(37, 3)
        GridRangeStyle197.StyleInfo.Text = "a la Renta y Partidas Extraordionarias "
        GridRangeStyle198.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(37, 7)
        GridRangeStyle198.StyleInfo.CellType = "Currency"
        GridRangeStyle198.StyleInfo.Text = "0.00"
        GridRangeStyle199.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(37, 8)
        GridRangeStyle199.StyleInfo.CellType = "TextBox"
        GridRangeStyle200.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(38, 2)
        GridRangeStyle200.StyleInfo.Text = "Participaciones"
        GridRangeStyle201.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(39, 2)
        GridRangeStyle201.StyleInfo.Text = "Impuesto a la Renta "
        GridRangeStyle202.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(39, 7)
        GridRangeStyle202.StyleInfo.CellType = "Currency"
        GridRangeStyle202.StyleInfo.Text = "0.00"
        GridRangeStyle203.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(41, 3)
        GridRangeStyle203.StyleInfo.Text = "Resultados antes de Partidas Extraordinarias"
        GridRangeStyle204.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(41, 7)
        GridRangeStyle204.StyleInfo.CellType = "Currency"
        GridRangeStyle204.StyleInfo.Text = "0.00"
        GridRangeStyle205.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(42, 2)
        GridRangeStyle205.StyleInfo.Text = "Ingresos Extraordinarios"
        GridRangeStyle206.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(43, 2)
        GridRangeStyle206.StyleInfo.Text = "Gastos Extraordinarios "
        GridRangeStyle207.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(45, 3)
        GridRangeStyle207.StyleInfo.Text = "Resultado Antes de Interés Minoritario"
        GridRangeStyle208.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(46, 2)
        GridRangeStyle208.StyleInfo.Text = "Interés Minoritario"
        GridRangeStyle209.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(48, 3)
        GridRangeStyle209.StyleInfo.Text = "Utilidad (pérdida) Neta del Ejercicio"
        GridRangeStyle210.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(48, 7)
        GridRangeStyle210.StyleInfo.CellType = "Currency"
        GridRangeStyle210.StyleInfo.Text = "0.00"
        GridRangeStyle211.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(50, 2)
        GridRangeStyle211.StyleInfo.Text = "Dividendos de Acciones Preferentes"
        GridRangeStyle212.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(51, 3)
        GridRangeStyle212.StyleInfo.Text = "Utilidad (pérdida) Neta atribuible a los Accionistas"
        GridRangeStyle213.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(52, 3)
        GridRangeStyle213.StyleInfo.Text = "Utilidad (pérdida) Básica por Acción Común"
        GridRangeStyle214.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(53, 3)
        GridRangeStyle214.StyleInfo.Text = "Utilidad (pérdida) Básica por Acción de Inversión"
        GridRangeStyle215.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(54, 3)
        GridRangeStyle215.StyleInfo.Text = "Utilidad (pérdida) Diluida por Acción Común"
        GridRangeStyle216.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(55, 2)
        GridRangeStyle216.StyleInfo.Text = ""
        GridRangeStyle217.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(55, 3)
        GridRangeStyle217.StyleInfo.Text = "Utilidad (pérdida) Diluida por Acción de Inversión "
        Me.GridControl2.RangeStyles.AddRange(New Syncfusion.Windows.Forms.Grid.GridRangeStyle() {GridRangeStyle147, GridRangeStyle148, GridRangeStyle149, GridRangeStyle150, GridRangeStyle151, GridRangeStyle152, GridRangeStyle153, GridRangeStyle154, GridRangeStyle155, GridRangeStyle156, GridRangeStyle157, GridRangeStyle158, GridRangeStyle159, GridRangeStyle160, GridRangeStyle161, GridRangeStyle162, GridRangeStyle163, GridRangeStyle164, GridRangeStyle165, GridRangeStyle166, GridRangeStyle167, GridRangeStyle168, GridRangeStyle169, GridRangeStyle170, GridRangeStyle171, GridRangeStyle172, GridRangeStyle173, GridRangeStyle174, GridRangeStyle175, GridRangeStyle176, GridRangeStyle177, GridRangeStyle178, GridRangeStyle179, GridRangeStyle180, GridRangeStyle181, GridRangeStyle182, GridRangeStyle183, GridRangeStyle184, GridRangeStyle185, GridRangeStyle186, GridRangeStyle187, GridRangeStyle188, GridRangeStyle189, GridRangeStyle190, GridRangeStyle191, GridRangeStyle192, GridRangeStyle193, GridRangeStyle194, GridRangeStyle195, GridRangeStyle196, GridRangeStyle197, GridRangeStyle198, GridRangeStyle199, GridRangeStyle200, GridRangeStyle201, GridRangeStyle202, GridRangeStyle203, GridRangeStyle204, GridRangeStyle205, GridRangeStyle206, GridRangeStyle207, GridRangeStyle208, GridRangeStyle209, GridRangeStyle210, GridRangeStyle211, GridRangeStyle212, GridRangeStyle213, GridRangeStyle214, GridRangeStyle215, GridRangeStyle216, GridRangeStyle217})
        Me.GridControl2.RightToLeft = System.Windows.Forms.RightToLeft.No
        Me.GridControl2.RowCount = 55
        Me.GridControl2.RowHeightEntries.AddRange(New Syncfusion.Windows.Forms.Grid.GridRowHeight() {New Syncfusion.Windows.Forms.Grid.GridRowHeight(0, 29)})
        Me.GridControl2.SerializeCellsBehavior = Syncfusion.Windows.Forms.Grid.GridSerializeCellsBehavior.SerializeAsRangeStylesIntoCode
        Me.GridControl2.Size = New System.Drawing.Size(875, 378)
        Me.GridControl2.SmartSizeBox = False
        'Me.GridControl2.SpreadsheetLikeSelection = False
        Me.GridControl2.TabIndex = 0
        Me.GridControl2.ThemesEnabled = True
        Me.GridControl2.UseRightToLeftCompatibleTextBox = True
        '
        'frmReporteEEF
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.ClientSize = New System.Drawing.Size(878, 402)
        Me.Controls.Add(Me.TabControlAdv1)
        Me.Name = "frmReporteEEF"
        Me.Text = "frmReporteEEF"
        CType(Me.TabControlAdv1, System.ComponentModel.ISupportInitialize).EndInit()
        Me.TabControlAdv1.ResumeLayout(False)
        Me.TabPageAdv1.ResumeLayout(False)
        CType(Me.GridControl1, System.ComponentModel.ISupportInitialize).EndInit()
        Me.TabPageAdv2.ResumeLayout(False)
        CType(Me.GridControl2, System.ComponentModel.ISupportInitialize).EndInit()
        Me.ResumeLayout(False)

    End Sub
    Friend WithEvents TabControlAdv1 As Syncfusion.Windows.Forms.Tools.TabControlAdv
    Friend WithEvents TabPageAdv1 As Syncfusion.Windows.Forms.Tools.TabPageAdv
    Friend WithEvents TabPageAdv2 As Syncfusion.Windows.Forms.Tools.TabPageAdv
    Friend WithEvents GridControl1 As Syncfusion.Windows.Forms.Grid.GridControl
    Friend WithEvents GridControl2 As Syncfusion.Windows.Forms.Grid.GridControl
End Class
