<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class frmSituacionFinanciera1
    Inherits Helios.Cont.Presentation.WinForm.frmMaster

    'Form overrides dispose to clean up the component list.
    <System.Diagnostics.DebuggerNonUserCode()> _
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        Try
            If disposing AndAlso components IsNot Nothing Then
                components.Dispose()
            End If
        Finally
            MyBase.Dispose(disposing)
        End Try
    End Sub

    'Required by the Windows Form Designer
    Private components As System.ComponentModel.IContainer

    'NOTE: The following procedure is required by the Windows Form Designer
    'It can be modified using the Windows Form Designer.  
    'Do not modify it using the code editor.
    <System.Diagnostics.DebuggerStepThrough()> _
    Private Sub InitializeComponent()
        Dim GridBaseStyle1 As Syncfusion.Windows.Forms.Grid.GridBaseStyle = New Syncfusion.Windows.Forms.Grid.GridBaseStyle()
        Dim GridBaseStyle2 As Syncfusion.Windows.Forms.Grid.GridBaseStyle = New Syncfusion.Windows.Forms.Grid.GridBaseStyle()
        Dim GridBaseStyle3 As Syncfusion.Windows.Forms.Grid.GridBaseStyle = New Syncfusion.Windows.Forms.Grid.GridBaseStyle()
        Dim GridBaseStyle4 As Syncfusion.Windows.Forms.Grid.GridBaseStyle = New Syncfusion.Windows.Forms.Grid.GridBaseStyle()
        Dim GridRangeStyle1 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle2 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle3 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle4 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle5 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle6 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle7 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle8 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle9 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle10 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle11 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle12 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle13 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle14 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle15 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle16 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle17 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle18 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle19 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle20 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle21 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle22 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle23 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle24 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle25 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle26 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle27 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle28 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle29 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle30 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle31 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle32 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle33 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle34 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle35 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle36 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle37 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle38 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle39 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle40 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle41 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle42 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle43 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle44 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle45 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle46 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle47 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle48 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle49 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle50 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle51 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle52 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle53 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle54 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle55 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle56 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle57 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle58 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle59 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle60 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle61 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle62 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle63 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle64 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle65 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle66 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle67 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle68 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle69 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle70 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle71 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle72 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle73 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle74 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle75 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle76 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle77 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle78 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle79 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle80 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle81 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle82 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle83 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle84 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle85 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle86 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle87 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle88 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle89 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle90 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle91 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle92 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle93 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle94 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle95 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle96 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle97 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle98 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle99 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle100 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle101 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle102 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle103 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle104 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle105 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle106 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle107 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle108 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle109 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle110 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle111 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle112 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle113 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle114 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle115 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle116 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle117 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle118 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle119 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle120 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle121 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle122 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle123 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle124 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle125 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle126 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle127 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle128 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle129 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle130 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle131 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle132 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle133 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle134 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle135 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle136 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle137 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle138 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle139 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle140 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle141 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle142 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle143 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle144 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle145 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle146 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle147 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle148 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle149 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle150 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle151 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle152 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle153 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle154 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim GridRangeStyle155 As Syncfusion.Windows.Forms.Grid.GridRangeStyle = New Syncfusion.Windows.Forms.Grid.GridRangeStyle()
        Dim CaptionLabel1 As Syncfusion.Windows.Forms.CaptionLabel = New Syncfusion.Windows.Forms.CaptionLabel()
        Me.gridSituacion = New Syncfusion.Windows.Forms.Grid.GridControl()
        CType(Me.gridSituacion, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.SuspendLayout()
        '
        'gridSituacion
        '
        Me.gridSituacion.AlphaBlendSelectionColor = System.Drawing.Color.FromArgb(CType(CType(64, Byte), Integer), CType(CType(94, Byte), Integer), CType(CType(171, Byte), Integer), CType(CType(222, Byte), Integer))
        Me.gridSituacion.BackColor = System.Drawing.Color.White
        GridBaseStyle1.Name = "Header"
        GridBaseStyle1.StyleInfo.Borders.Bottom = New Syncfusion.Windows.Forms.Grid.GridBorder(Syncfusion.Windows.Forms.Grid.GridBorderStyle.None)
        GridBaseStyle1.StyleInfo.Borders.Left = New Syncfusion.Windows.Forms.Grid.GridBorder(Syncfusion.Windows.Forms.Grid.GridBorderStyle.None)
        GridBaseStyle1.StyleInfo.Borders.Right = New Syncfusion.Windows.Forms.Grid.GridBorder(Syncfusion.Windows.Forms.Grid.GridBorderStyle.None)
        GridBaseStyle1.StyleInfo.Borders.Top = New Syncfusion.Windows.Forms.Grid.GridBorder(Syncfusion.Windows.Forms.Grid.GridBorderStyle.None)
        GridBaseStyle1.StyleInfo.CellType = "Header"
        GridBaseStyle1.StyleInfo.Font.Bold = True
        GridBaseStyle1.StyleInfo.Interior = New Syncfusion.Drawing.BrushInfo(Syncfusion.Drawing.GradientStyle.Vertical, System.Drawing.Color.FromArgb(CType(CType(203, Byte), Integer), CType(CType(199, Byte), Integer), CType(CType(184, Byte), Integer)), System.Drawing.Color.FromArgb(CType(CType(238, Byte), Integer), CType(CType(234, Byte), Integer), CType(CType(216, Byte), Integer)))
        GridBaseStyle1.StyleInfo.VerticalAlignment = Syncfusion.Windows.Forms.Grid.GridVerticalAlignment.Middle
        GridBaseStyle2.Name = "Standard"
        GridBaseStyle2.StyleInfo.Font.Facename = "Tahoma"
        GridBaseStyle2.StyleInfo.Interior = New Syncfusion.Drawing.BrushInfo(System.Drawing.SystemColors.Window)
        GridBaseStyle3.Name = "Column Header"
        GridBaseStyle3.StyleInfo.BaseStyle = "Header"
        GridBaseStyle3.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Center
        GridBaseStyle4.Name = "Row Header"
        GridBaseStyle4.StyleInfo.BaseStyle = "Header"
        GridBaseStyle4.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Left
        GridBaseStyle4.StyleInfo.Interior = New Syncfusion.Drawing.BrushInfo(Syncfusion.Drawing.GradientStyle.Horizontal, System.Drawing.Color.FromArgb(CType(CType(203, Byte), Integer), CType(CType(199, Byte), Integer), CType(CType(184, Byte), Integer)), System.Drawing.Color.FromArgb(CType(CType(238, Byte), Integer), CType(CType(234, Byte), Integer), CType(CType(216, Byte), Integer)))
        Me.gridSituacion.BaseStylesMap.AddRange(New Syncfusion.Windows.Forms.Grid.GridBaseStyle() {GridBaseStyle1, GridBaseStyle2, GridBaseStyle3, GridBaseStyle4})
        Me.gridSituacion.ColCount = 14
        Me.gridSituacion.ColWidthEntries.AddRange(New Syncfusion.Windows.Forms.Grid.GridColWidth() {New Syncfusion.Windows.Forms.Grid.GridColWidth(0, 35), New Syncfusion.Windows.Forms.Grid.GridColWidth(1, 162), New Syncfusion.Windows.Forms.Grid.GridColWidth(2, 60), New Syncfusion.Windows.Forms.Grid.GridColWidth(3, 39), New Syncfusion.Windows.Forms.Grid.GridColWidth(4, 321), New Syncfusion.Windows.Forms.Grid.GridColWidth(5, 80), New Syncfusion.Windows.Forms.Grid.GridColWidth(6, 34), New Syncfusion.Windows.Forms.Grid.GridColWidth(13, 72), New Syncfusion.Windows.Forms.Grid.GridColWidth(14, 22)})
        Me.gridSituacion.CoveredRanges.AddRange(New Syncfusion.Windows.Forms.Grid.GridRangeInfo() {Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(1, 2, 1, 14), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(2, 2, 2, 14), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(3, 2, 3, 14), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(4, 2, 4, 3), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(6, 2, 6, 3), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(10, 2, 10, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(12, 2, 12, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(13, 3, 13, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(16, 2, 16, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(17, 2, 17, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(18, 2, 18, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(19, 2, 19, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(20, 2, 20, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(21, 2, 21, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(23, 2, 23, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(24, 2, 24, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(25, 2, 25, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(26, 2, 26, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(27, 2, 27, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(28, 2, 28, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(29, 2, 29, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(30, 2, 30, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(32, 3, 32, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(34, 2, 34, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(35, 2, 35, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(36, 2, 36, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(37, 2, 37, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(38, 2, 38, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(39, 2, 39, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(40, 2, 40, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(41, 2, 41, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(42, 2, 42, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(43, 2, 43, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(44, 2, 44, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(48, 3, 48, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(63, 3, 63, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(8, 8, 8, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(10, 8, 10, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(11, 8, 11, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(12, 8, 12, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(13, 8, 13, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(15, 8, 15, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(16, 8, 16, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(17, 8, 17, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(18, 8, 18, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(19, 8, 19, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(20, 8, 20, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(21, 8, 21, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(22, 8, 22, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(23, 8, 23, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(24, 8, 24, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(25, 8, 25, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(28, 9, 28, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(32, 8, 32, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(33, 8, 33, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(41, 9, 41, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(45, 10, 45, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(49, 8, 49, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(51, 8, 51, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(52, 8, 52, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(53, 8, 53, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(57, 8, 57, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(58, 8, 58, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(59, 8, 59, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(60, 8, 60, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(62, 9, 62, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(61, 9, 61, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(63, 9, 63, 12), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(22, 2, 22, 4), Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(5, 2, 5, 3)})
        Me.gridSituacion.DefaultGridBorderStyle = Syncfusion.Windows.Forms.Grid.GridBorderStyle.Solid
        Me.gridSituacion.DefaultRowHeight = 20
        Me.gridSituacion.Dock = System.Windows.Forms.DockStyle.Fill
        Me.gridSituacion.Font = New System.Drawing.Font("Segoe UI", 8.25!)
        Me.gridSituacion.ForeColor = System.Drawing.Color.Black
        Me.gridSituacion.GridOfficeScrollBars = Syncfusion.Windows.Forms.OfficeScrollBars.Metro
        Me.gridSituacion.GridVisualStyles = Syncfusion.Windows.Forms.GridVisualStyles.Metro
        'Me.gridSituacion.IsSpreadsheetFillSeries = False
        Me.gridSituacion.Location = New System.Drawing.Point(0, 0)
        Me.gridSituacion.MetroScrollBars = True
        Me.gridSituacion.Name = "gridSituacion"
        Me.gridSituacion.Properties.ColHeaders = False
        Me.gridSituacion.Properties.ForceImmediateRepaint = False
        Me.gridSituacion.Properties.GridLineColor = System.Drawing.Color.FromArgb(CType(CType(212, Byte), Integer), CType(CType(212, Byte), Integer), CType(CType(212, Byte), Integer))
        Me.gridSituacion.Properties.MarkColHeader = False
        Me.gridSituacion.Properties.MarkRowHeader = False
        GridRangeStyle1.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Table
        GridRangeStyle1.StyleInfo.Font.Bold = False
        GridRangeStyle1.StyleInfo.Font.Facename = "Segoe UI"
        GridRangeStyle1.StyleInfo.Font.Italic = False
        GridRangeStyle1.StyleInfo.Font.Size = 8.25!
        GridRangeStyle1.StyleInfo.Font.Strikeout = False
        GridRangeStyle1.StyleInfo.Font.Underline = False
        GridRangeStyle1.StyleInfo.Font.Unit = System.Drawing.GraphicsUnit.Point
        GridRangeStyle2.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Table
        GridRangeStyle2.StyleInfo.Font.Bold = False
        GridRangeStyle2.StyleInfo.Font.Facename = "Segoe UI"
        GridRangeStyle2.StyleInfo.Font.Italic = False
        GridRangeStyle2.StyleInfo.Font.Size = 8.25!
        GridRangeStyle2.StyleInfo.Font.Strikeout = False
        GridRangeStyle2.StyleInfo.Font.Underline = False
        GridRangeStyle2.StyleInfo.Font.Unit = System.Drawing.GraphicsUnit.Point
        GridRangeStyle2.StyleInfo.TextColor = System.Drawing.Color.Black
        GridRangeStyle3.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Col(1)
        GridRangeStyle3.StyleInfo.Font.Bold = False
        GridRangeStyle3.StyleInfo.Interior = New Syncfusion.Drawing.BrushInfo(System.Drawing.Color.Snow)
        GridRangeStyle3.StyleInfo.TextColor = System.Drawing.SystemColors.HotTrack
        GridRangeStyle4.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Col(7)
        GridRangeStyle4.StyleInfo.Interior = New Syncfusion.Drawing.BrushInfo(System.Drawing.Color.Snow)
        GridRangeStyle4.StyleInfo.TextColor = System.Drawing.SystemColors.HotTrack
        GridRangeStyle5.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(1, 2)
        GridRangeStyle5.StyleInfo.Font.Bold = True
        GridRangeStyle5.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Center
        GridRangeStyle5.StyleInfo.Text = "ESTADO DE SITUACIÓN FINANCIERA "
        GridRangeStyle6.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(2, 2)
        GridRangeStyle6.StyleInfo.Font.Bold = True
        GridRangeStyle6.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Center
        GridRangeStyle6.StyleInfo.Text = "Del 01 de enero Al 31 de diciembre del 2011"
        GridRangeStyle7.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(3, 2)
        GridRangeStyle7.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Center
        GridRangeStyle7.StyleInfo.Text = "(Expresado en Nuevos Soles)"
        GridRangeStyle8.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(4, 2)
        GridRangeStyle8.StyleInfo.Font.Bold = True
        GridRangeStyle8.StyleInfo.Interior = New Syncfusion.Drawing.BrushInfo(System.Drawing.SystemColors.Info)
        GridRangeStyle8.StyleInfo.Text = "EJERCICIO:"
        GridRangeStyle9.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(4, 3, 6, 3)
        GridRangeStyle9.StyleInfo.Interior = New Syncfusion.Drawing.BrushInfo(System.Drawing.SystemColors.Info)
        GridRangeStyle10.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(4, 4)
        GridRangeStyle10.StyleInfo.Interior = New Syncfusion.Drawing.BrushInfo(System.Drawing.SystemColors.Info)
        GridRangeStyle10.StyleInfo.Text = "2011"
        GridRangeStyle11.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(5, 2)
        GridRangeStyle11.StyleInfo.Font.Bold = True
        GridRangeStyle11.StyleInfo.Interior = New Syncfusion.Drawing.BrushInfo(System.Drawing.SystemColors.Info)
        GridRangeStyle11.StyleInfo.Text = "RUC:"
        GridRangeStyle12.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(5, 4)
        GridRangeStyle12.StyleInfo.Interior = New Syncfusion.Drawing.BrushInfo(System.Drawing.SystemColors.Info)
        GridRangeStyle12.StyleInfo.Text = "20541581813"
        GridRangeStyle13.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(6, 2)
        GridRangeStyle13.StyleInfo.Font.Bold = True
        GridRangeStyle13.StyleInfo.Interior = New Syncfusion.Drawing.BrushInfo(System.Drawing.SystemColors.Info)
        GridRangeStyle13.StyleInfo.Text = "RAZÓN SOCIAL:"
        GridRangeStyle14.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(6, 4)
        GridRangeStyle14.StyleInfo.Interior = New Syncfusion.Drawing.BrushInfo(System.Drawing.SystemColors.Info)
        GridRangeStyle14.StyleInfo.Text = "CESAL CONSTRUCTORES EIRL "
        GridRangeStyle15.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(7, 5)
        GridRangeStyle15.StyleInfo.Text = ""
        GridRangeStyle16.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(8, 2)
        GridRangeStyle16.StyleInfo.Font.Bold = True
        GridRangeStyle16.StyleInfo.Text = "ACTIVO "
        GridRangeStyle17.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(8, 5)
        GridRangeStyle17.StyleInfo.Font.Bold = True
        GridRangeStyle17.StyleInfo.Text = "HISTORICO"
        GridRangeStyle18.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(8, 8)
        GridRangeStyle18.StyleInfo.Font.Bold = True
        GridRangeStyle18.StyleInfo.Text = "PASIVO Y PATRIMONIO "
        GridRangeStyle19.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(8, 13)
        GridRangeStyle19.StyleInfo.Font.Bold = True
        GridRangeStyle19.StyleInfo.Text = "HISTORICO"
        GridRangeStyle20.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(10, 2)
        GridRangeStyle20.StyleInfo.Font.Bold = True
        GridRangeStyle20.StyleInfo.Text = "ACTIVO CORRIENTE"
        GridRangeStyle21.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(10, 8)
        GridRangeStyle21.StyleInfo.Font.Bold = True
        GridRangeStyle21.StyleInfo.Text = "PASIVO CORRIENTE"
        GridRangeStyle22.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(11, 7)
        GridRangeStyle22.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle22.StyleInfo.Text = "40"
        GridRangeStyle23.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(11, 8)
        GridRangeStyle23.StyleInfo.Text = "Tributos, aportes al sistema de pensiones y de salud por pagar"
        GridRangeStyle24.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(11, 13, 25, 13)
        GridRangeStyle24.StyleInfo.CellType = "Currency"
        GridRangeStyle24.StyleInfo.Text = "0.00"
        GridRangeStyle25.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(12, 1)
        GridRangeStyle25.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle25.StyleInfo.Text = "10"
        GridRangeStyle26.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(12, 2)
        GridRangeStyle26.StyleInfo.Text = "efectvo y equivalentes de efectivo "
        GridRangeStyle27.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(12, 5)
        GridRangeStyle27.StyleInfo.CellType = "Currency"
        GridRangeStyle27.StyleInfo.Text = "0.00"
        GridRangeStyle28.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(12, 8)
        GridRangeStyle28.StyleInfo.Text = "Puede tener saldos positivos o negativos, pero se muestra el saldo final "
        GridRangeStyle29.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(13, 2, 13, 3)
        GridRangeStyle29.StyleInfo.Text = ""
        GridRangeStyle30.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(13, 5, 15, 5)
        GridRangeStyle30.StyleInfo.CellType = "Currency"
        GridRangeStyle30.StyleInfo.Text = ""
        GridRangeStyle31.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(13, 8)
        GridRangeStyle31.StyleInfo.Text = "Activo/Pasivo"
        GridRangeStyle32.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(14, 3, 15, 4)
        GridRangeStyle32.StyleInfo.Text = ""
        GridRangeStyle33.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(15, 7)
        GridRangeStyle33.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle33.StyleInfo.Text = "41"
        GridRangeStyle34.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(15, 8)
        GridRangeStyle34.StyleInfo.Text = "Remuneraciones y particicipaciones por pagar "
        GridRangeStyle35.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(16, 1)
        GridRangeStyle35.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle35.StyleInfo.Text = "11"
        GridRangeStyle36.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(16, 2)
        GridRangeStyle36.StyleInfo.Text = "Inversiones financieras"
        GridRangeStyle37.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(16, 5)
        GridRangeStyle37.StyleInfo.CellType = "Currency"
        GridRangeStyle37.StyleInfo.Text = "0"
        GridRangeStyle38.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(16, 7)
        GridRangeStyle38.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle38.StyleInfo.Text = "42"
        GridRangeStyle39.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(16, 8)
        GridRangeStyle39.StyleInfo.Text = "Cuentas por pagar comerciales - Terceros"
        GridRangeStyle40.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(17, 1)
        GridRangeStyle40.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle40.StyleInfo.Text = "12"
        GridRangeStyle41.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(17, 2)
        GridRangeStyle41.StyleInfo.Text = "Cuentas por cobrar comerciales - terceros"
        GridRangeStyle42.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(17, 5, 29, 5)
        GridRangeStyle42.StyleInfo.CellType = "Currency"
        GridRangeStyle42.StyleInfo.Text = "0.00"
        GridRangeStyle43.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(17, 7)
        GridRangeStyle43.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle43.StyleInfo.Text = "122"
        GridRangeStyle43.StyleInfo.TextColor = System.Drawing.Color.Red
        GridRangeStyle44.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(17, 8)
        GridRangeStyle44.StyleInfo.Text = "Anticipos de clientes "
        GridRangeStyle45.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(18, 1)
        GridRangeStyle45.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle45.StyleInfo.Text = "422"
        GridRangeStyle45.StyleInfo.TextColor = System.Drawing.Color.Red
        GridRangeStyle46.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(18, 2)
        GridRangeStyle46.StyleInfo.Text = "Anticipos a proveedores "
        GridRangeStyle47.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(18, 7)
        GridRangeStyle47.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle47.StyleInfo.Text = "43"
        GridRangeStyle48.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(18, 8)
        GridRangeStyle48.StyleInfo.Text = "Cuentas por pagar comerciales - Relacionadas"
        GridRangeStyle49.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(19, 1)
        GridRangeStyle49.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle49.StyleInfo.Text = "432"
        GridRangeStyle49.StyleInfo.TextColor = System.Drawing.Color.Red
        GridRangeStyle50.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(19, 2)
        GridRangeStyle50.StyleInfo.Text = "Anticipos otorgados"
        GridRangeStyle51.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(19, 7)
        GridRangeStyle51.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle51.StyleInfo.Text = "132"
        GridRangeStyle51.StyleInfo.TextColor = System.Drawing.Color.Red
        GridRangeStyle52.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(19, 8)
        GridRangeStyle52.StyleInfo.Text = "Anticipos recibidos "
        GridRangeStyle53.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(20, 1)
        GridRangeStyle53.StyleInfo.Font.Underline = False
        GridRangeStyle53.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle53.StyleInfo.Text = "13"
        GridRangeStyle54.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(20, 2)
        GridRangeStyle54.StyleInfo.Text = "Cuentas por cobrar comerciales - relacionadas"
        GridRangeStyle55.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(20, 7)
        GridRangeStyle55.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle55.StyleInfo.Text = "44"
        GridRangeStyle56.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(20, 8)
        GridRangeStyle56.StyleInfo.Text = "Cuentas por pagar a los accionistas (socios), directores y gerentes"
        GridRangeStyle57.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(21, 1)
        GridRangeStyle57.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle57.StyleInfo.Text = "14"
        GridRangeStyle58.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(21, 2)
        GridRangeStyle58.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Left
        GridRangeStyle58.StyleInfo.Text = "Cuentas por cobrar al personal, a los accionistas (socios), directores y gerentes" & _
    ""
        GridRangeStyle59.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(21, 3, 21, 4)
        GridRangeStyle59.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Left
        GridRangeStyle60.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(21, 7)
        GridRangeStyle60.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle60.StyleInfo.Text = "45"
        GridRangeStyle61.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(21, 8)
        GridRangeStyle61.StyleInfo.Text = "Obligaciones financieras"
        GridRangeStyle62.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(22, 1)
        GridRangeStyle62.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle62.StyleInfo.Text = "15"
        GridRangeStyle63.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(22, 7)
        GridRangeStyle63.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle63.StyleInfo.Text = "46"
        GridRangeStyle64.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(22, 8)
        GridRangeStyle64.StyleInfo.Text = "Cuentas por pagar diversas-terceros "
        GridRangeStyle65.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(23, 1)
        GridRangeStyle65.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle65.StyleInfo.Text = "16"
        GridRangeStyle66.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(23, 2)
        GridRangeStyle66.StyleInfo.Text = "Cuentas por cobrar diversas - terceros"
        GridRangeStyle67.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(23, 7)
        GridRangeStyle67.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle67.StyleInfo.Text = "47"
        GridRangeStyle68.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(23, 8)
        GridRangeStyle68.StyleInfo.Text = "Cuentas por pagar diversas-relacionadas "
        GridRangeStyle69.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(24, 1)
        GridRangeStyle69.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle69.StyleInfo.Text = "17"
        GridRangeStyle70.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(24, 2)
        GridRangeStyle70.StyleInfo.Text = "Cuentas por cobrar diversas - relacionadas"
        GridRangeStyle71.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(24, 7)
        GridRangeStyle71.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle71.StyleInfo.Text = "48"
        GridRangeStyle72.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(24, 8)
        GridRangeStyle72.StyleInfo.Text = "Provisiones"
        GridRangeStyle73.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(25, 1)
        GridRangeStyle73.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle73.StyleInfo.Text = "18"
        GridRangeStyle74.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(25, 2)
        GridRangeStyle74.StyleInfo.Text = "Servicios y otros contratados por anticipado"
        GridRangeStyle75.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(25, 7)
        GridRangeStyle75.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle75.StyleInfo.Text = "49"
        GridRangeStyle76.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(25, 8)
        GridRangeStyle76.StyleInfo.Text = "Pasivo diferido "
        GridRangeStyle77.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(26, 1)
        GridRangeStyle77.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle77.StyleInfo.Text = "19"
        GridRangeStyle78.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(26, 2)
        GridRangeStyle78.StyleInfo.Text = "Estimación de cuentas de cobranza dudosa (pendiente)"
        GridRangeStyle79.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(27, 1)
        GridRangeStyle79.StyleInfo.Text = "20,21,22,23,24,25,26,27,28 y 29"
        GridRangeStyle80.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(27, 2)
        GridRangeStyle80.StyleInfo.Text = "Inventarios "
        GridRangeStyle81.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(28, 1)
        GridRangeStyle81.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle81.StyleInfo.Text = "40"
        GridRangeStyle82.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(28, 2)
        GridRangeStyle82.StyleInfo.Text = "Tributos, aportes al sistema de pensiones y de salud por pagar"
        GridRangeStyle83.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(28, 9)
        GridRangeStyle83.StyleInfo.Font.Bold = True
        GridRangeStyle83.StyleInfo.Text = "TOTAL PASIVO CORRIENTE"
        GridRangeStyle84.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(28, 13)
        GridRangeStyle84.StyleInfo.CellType = "FormulaCell"
        GridRangeStyle84.StyleInfo.Font.Bold = True
        GridRangeStyle84.StyleInfo.Text = "=sum(M11:M25)"
        GridRangeStyle85.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(29, 2)
        GridRangeStyle85.StyleInfo.Text = "Puede tener saldos positivos o negativos, pero se muestra el saldo final "
        GridRangeStyle86.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(30, 2)
        GridRangeStyle86.StyleInfo.Text = "Activo/Pasivo"
        GridRangeStyle87.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(32, 3)
        GridRangeStyle87.StyleInfo.Font.Bold = True
        GridRangeStyle87.StyleInfo.Text = "TOTAL ACTVO CORRIENTE"
        GridRangeStyle88.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(32, 5)
        GridRangeStyle88.StyleInfo.CellType = "FormulaCell"
        GridRangeStyle88.StyleInfo.Font.Bold = True
        GridRangeStyle88.StyleInfo.Text = "=SUM(E11:E29)"
        GridRangeStyle89.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(32, 8)
        GridRangeStyle89.StyleInfo.Font.Bold = True
        GridRangeStyle89.StyleInfo.Text = "PASIVO NO CORRIENTE"
        GridRangeStyle90.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(33, 7)
        GridRangeStyle90.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle90.StyleInfo.Text = "47"
        GridRangeStyle91.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(33, 8)
        GridRangeStyle91.StyleInfo.Text = "Cuentas por pagar diversas-relacionadas "
        GridRangeStyle92.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(33, 13)
        GridRangeStyle92.StyleInfo.CellType = "FormulaCell"
        GridRangeStyle92.StyleInfo.Font.Bold = True
        GridRangeStyle92.StyleInfo.Text = "=M23"
        GridRangeStyle93.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(34, 2)
        GridRangeStyle93.StyleInfo.Text = "ACTIVO NO CORRIENTE"
        GridRangeStyle94.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(35, 1)
        GridRangeStyle94.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle94.StyleInfo.Text = "30"
        GridRangeStyle95.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(35, 2)
        GridRangeStyle95.StyleInfo.Text = "Inversiones mobiliarias"
        GridRangeStyle96.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(35, 5, 44, 5)
        GridRangeStyle96.StyleInfo.CellType = "Currency"
        GridRangeStyle96.StyleInfo.Text = "0.00"
        GridRangeStyle97.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(36, 1)
        GridRangeStyle97.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle97.StyleInfo.Text = "31"
        GridRangeStyle98.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(36, 2)
        GridRangeStyle98.StyleInfo.Text = "Inversiones inmobiliarias"
        GridRangeStyle99.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(37, 1)
        GridRangeStyle99.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle99.StyleInfo.Text = "32"
        GridRangeStyle100.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(37, 2)
        GridRangeStyle100.StyleInfo.Text = "Activos adquiridos en arrendamiento financiero "
        GridRangeStyle101.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(38, 1)
        GridRangeStyle101.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle101.StyleInfo.Text = "33"
        GridRangeStyle102.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(38, 2)
        GridRangeStyle102.StyleInfo.Text = "Inmuebles, maquinaria y equipo"
        GridRangeStyle103.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(39, 1)
        GridRangeStyle103.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle103.StyleInfo.Text = "34"
        GridRangeStyle104.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(39, 2)
        GridRangeStyle104.StyleInfo.Text = "Intangibles "
        GridRangeStyle105.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(40, 1)
        GridRangeStyle105.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle105.StyleInfo.Text = "35"
        GridRangeStyle106.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(40, 2)
        GridRangeStyle106.StyleInfo.Text = "Activos biológicos "
        GridRangeStyle107.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(41, 1)
        GridRangeStyle107.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle107.StyleInfo.Text = "36"
        GridRangeStyle108.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(41, 2)
        GridRangeStyle108.StyleInfo.Text = "Desvalorización de activo inmovilizado "
        GridRangeStyle109.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(41, 9)
        GridRangeStyle109.StyleInfo.Font.Bold = True
        GridRangeStyle109.StyleInfo.Text = "TOTAL PASIVO NO CORRIENTE"
        GridRangeStyle110.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(41, 13)
        GridRangeStyle110.StyleInfo.CellType = "FormulaCell"
        GridRangeStyle110.StyleInfo.Font.Bold = True
        GridRangeStyle110.StyleInfo.Text = "=M33"
        GridRangeStyle111.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(42, 1)
        GridRangeStyle111.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle111.StyleInfo.Text = "37"
        GridRangeStyle112.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(42, 2)
        GridRangeStyle112.StyleInfo.Text = "Activo diferido "
        GridRangeStyle113.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(43, 1)
        GridRangeStyle113.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle113.StyleInfo.Text = "38"
        GridRangeStyle114.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(43, 2)
        GridRangeStyle114.StyleInfo.Text = "Otros activos "
        GridRangeStyle115.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(44, 1)
        GridRangeStyle115.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle115.StyleInfo.Text = "39"
        GridRangeStyle116.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(44, 2)
        GridRangeStyle116.StyleInfo.Text = "Depreciación, amortización y agotamiento acumulados (pendiente)"
        GridRangeStyle117.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(45, 10)
        GridRangeStyle117.StyleInfo.Font.Bold = True
        GridRangeStyle117.StyleInfo.Text = "TOTAL PASIVO "
        GridRangeStyle118.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(45, 13)
        GridRangeStyle118.StyleInfo.CellType = "FormulaCell"
        GridRangeStyle118.StyleInfo.Font.Bold = True
        GridRangeStyle118.StyleInfo.Text = "=M28+M41"
        GridRangeStyle119.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(48, 3)
        GridRangeStyle119.StyleInfo.Font.Bold = True
        GridRangeStyle119.StyleInfo.Text = "TOTAL ACTIVO NO CORRIENTE"
        GridRangeStyle120.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(48, 4)
        GridRangeStyle120.StyleInfo.Font.Bold = True
        GridRangeStyle121.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(48, 5)
        GridRangeStyle121.StyleInfo.CellType = "FormulaCell"
        GridRangeStyle121.StyleInfo.Font.Bold = True
        GridRangeStyle121.StyleInfo.Text = "=sum(E35:E44)"
        GridRangeStyle122.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(49, 8)
        GridRangeStyle122.StyleInfo.Font.Bold = True
        GridRangeStyle122.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Left
        GridRangeStyle122.StyleInfo.Text = "PATRIMONIO NETO "
        GridRangeStyle123.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(49, 9, 49, 12)
        GridRangeStyle123.StyleInfo.Font.Bold = True
        GridRangeStyle123.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Left
        GridRangeStyle124.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(50, 7)
        GridRangeStyle124.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle124.StyleInfo.Text = "50"
        GridRangeStyle125.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(50, 8)
        GridRangeStyle125.StyleInfo.Text = "Capital"
        GridRangeStyle126.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(50, 13, 60, 13)
        GridRangeStyle126.StyleInfo.CellType = "Currency"
        GridRangeStyle126.StyleInfo.Text = "0.00"
        GridRangeStyle127.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(51, 7)
        GridRangeStyle127.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle127.StyleInfo.Text = "51"
        GridRangeStyle128.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(51, 8)
        GridRangeStyle128.StyleInfo.Text = "Acciones de Inversión"
        GridRangeStyle129.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(52, 7)
        GridRangeStyle129.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle129.StyleInfo.Text = "52"
        GridRangeStyle130.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(52, 8)
        GridRangeStyle130.StyleInfo.Text = "Capital adicional "
        GridRangeStyle131.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(53, 7)
        GridRangeStyle131.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle131.StyleInfo.Text = "53"
        GridRangeStyle132.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(53, 8)
        GridRangeStyle132.StyleInfo.Text = ""
        GridRangeStyle133.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(54, 7)
        GridRangeStyle133.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle133.StyleInfo.Text = "54"
        GridRangeStyle134.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(55, 7)
        GridRangeStyle134.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle134.StyleInfo.Text = "55"
        GridRangeStyle135.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(56, 7)
        GridRangeStyle135.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle135.StyleInfo.Text = "56"
        GridRangeStyle136.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(56, 8)
        GridRangeStyle136.StyleInfo.Text = "Resultados no realizados"
        GridRangeStyle137.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(57, 7)
        GridRangeStyle137.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle137.StyleInfo.Text = "57"
        GridRangeStyle138.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(57, 8)
        GridRangeStyle138.StyleInfo.Text = "Excedente de revaluación "
        GridRangeStyle139.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(58, 7)
        GridRangeStyle139.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle139.StyleInfo.Text = "58"
        GridRangeStyle140.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(58, 8)
        GridRangeStyle140.StyleInfo.Text = "Reservas"
        GridRangeStyle141.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(59, 7)
        GridRangeStyle141.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle141.StyleInfo.Text = "59"
        GridRangeStyle142.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(59, 8)
        GridRangeStyle142.StyleInfo.Text = "Resultados acumulados "
        GridRangeStyle143.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(60, 7, 61, 7)
        GridRangeStyle143.StyleInfo.HorizontalAlignment = Syncfusion.Windows.Forms.Grid.GridHorizontalAlignment.Right
        GridRangeStyle143.StyleInfo.Text = ""
        GridRangeStyle144.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(60, 8)
        GridRangeStyle144.StyleInfo.Text = "Resultado del periodo"
        GridRangeStyle145.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(61, 8)
        GridRangeStyle145.StyleInfo.Text = ""
        GridRangeStyle146.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(61, 9)
        GridRangeStyle146.StyleInfo.Font.Bold = True
        GridRangeStyle146.StyleInfo.Text = "TOTAL PATRIMONIO NETO"
        GridRangeStyle147.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(61, 10, 61, 12)
        GridRangeStyle147.StyleInfo.Font.Bold = True
        GridRangeStyle148.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(61, 13)
        GridRangeStyle148.StyleInfo.CellType = "FormulaCell"
        GridRangeStyle148.StyleInfo.Font.Bold = True
        GridRangeStyle148.StyleInfo.Text = "=sum(M50:M60)"
        GridRangeStyle149.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(62, 9)
        GridRangeStyle149.StyleInfo.Text = ""
        GridRangeStyle150.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(63, 3)
        GridRangeStyle150.StyleInfo.Font.Bold = True
        GridRangeStyle150.StyleInfo.Text = "TOTAL ACTIVO "
        GridRangeStyle151.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(63, 4)
        GridRangeStyle151.StyleInfo.Font.Bold = True
        GridRangeStyle152.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(63, 5)
        GridRangeStyle152.StyleInfo.Borders.Top = New Syncfusion.Windows.Forms.Grid.GridBorder(Syncfusion.Windows.Forms.Grid.GridBorderStyle.Solid, System.Drawing.SystemColors.InactiveCaptionText, Syncfusion.Windows.Forms.Grid.GridBorderWeight.Medium)
        GridRangeStyle152.StyleInfo.CellType = "FormulaCell"
        GridRangeStyle152.StyleInfo.Font.Bold = True
        GridRangeStyle152.StyleInfo.Text = "=E32+E48"
        GridRangeStyle153.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(63, 9)
        GridRangeStyle153.StyleInfo.Font.Bold = True
        GridRangeStyle153.StyleInfo.Text = "TOTAL PASIVO Y PATRIMONIO NETO "
        GridRangeStyle154.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cells(63, 10, 63, 12)
        GridRangeStyle154.StyleInfo.Font.Bold = True
        GridRangeStyle155.Range = Syncfusion.Windows.Forms.Grid.GridRangeInfo.Cell(63, 13)
        GridRangeStyle155.StyleInfo.Borders.Top = New Syncfusion.Windows.Forms.Grid.GridBorder(Syncfusion.Windows.Forms.Grid.GridBorderStyle.Solid, System.Drawing.SystemColors.InactiveCaptionText, Syncfusion.Windows.Forms.Grid.GridBorderWeight.Medium)
        GridRangeStyle155.StyleInfo.CellType = "FormulaCell"
        GridRangeStyle155.StyleInfo.Font.Bold = True
        GridRangeStyle155.StyleInfo.Text = "=M45+M61"
        Me.gridSituacion.RangeStyles.AddRange(New Syncfusion.Windows.Forms.Grid.GridRangeStyle() {GridRangeStyle1, GridRangeStyle2, GridRangeStyle3, GridRangeStyle4, GridRangeStyle5, GridRangeStyle6, GridRangeStyle7, GridRangeStyle8, GridRangeStyle9, GridRangeStyle10, GridRangeStyle11, GridRangeStyle12, GridRangeStyle13, GridRangeStyle14, GridRangeStyle15, GridRangeStyle16, GridRangeStyle17, GridRangeStyle18, GridRangeStyle19, GridRangeStyle20, GridRangeStyle21, GridRangeStyle22, GridRangeStyle23, GridRangeStyle24, GridRangeStyle25, GridRangeStyle26, GridRangeStyle27, GridRangeStyle28, GridRangeStyle29, GridRangeStyle30, GridRangeStyle31, GridRangeStyle32, GridRangeStyle33, GridRangeStyle34, GridRangeStyle35, GridRangeStyle36, GridRangeStyle37, GridRangeStyle38, GridRangeStyle39, GridRangeStyle40, GridRangeStyle41, GridRangeStyle42, GridRangeStyle43, GridRangeStyle44, GridRangeStyle45, GridRangeStyle46, GridRangeStyle47, GridRangeStyle48, GridRangeStyle49, GridRangeStyle50, GridRangeStyle51, GridRangeStyle52, GridRangeStyle53, GridRangeStyle54, GridRangeStyle55, GridRangeStyle56, GridRangeStyle57, GridRangeStyle58, GridRangeStyle59, GridRangeStyle60, GridRangeStyle61, GridRangeStyle62, GridRangeStyle63, GridRangeStyle64, GridRangeStyle65, GridRangeStyle66, GridRangeStyle67, GridRangeStyle68, GridRangeStyle69, GridRangeStyle70, GridRangeStyle71, GridRangeStyle72, GridRangeStyle73, GridRangeStyle74, GridRangeStyle75, GridRangeStyle76, GridRangeStyle77, GridRangeStyle78, GridRangeStyle79, GridRangeStyle80, GridRangeStyle81, GridRangeStyle82, GridRangeStyle83, GridRangeStyle84, GridRangeStyle85, GridRangeStyle86, GridRangeStyle87, GridRangeStyle88, GridRangeStyle89, GridRangeStyle90, GridRangeStyle91, GridRangeStyle92, GridRangeStyle93, GridRangeStyle94, GridRangeStyle95, GridRangeStyle96, GridRangeStyle97, GridRangeStyle98, GridRangeStyle99, GridRangeStyle100, GridRangeStyle101, GridRangeStyle102, GridRangeStyle103, GridRangeStyle104, GridRangeStyle105, GridRangeStyle106, GridRangeStyle107, GridRangeStyle108, GridRangeStyle109, GridRangeStyle110, GridRangeStyle111, GridRangeStyle112, GridRangeStyle113, GridRangeStyle114, GridRangeStyle115, GridRangeStyle116, GridRangeStyle117, GridRangeStyle118, GridRangeStyle119, GridRangeStyle120, GridRangeStyle121, GridRangeStyle122, GridRangeStyle123, GridRangeStyle124, GridRangeStyle125, GridRangeStyle126, GridRangeStyle127, GridRangeStyle128, GridRangeStyle129, GridRangeStyle130, GridRangeStyle131, GridRangeStyle132, GridRangeStyle133, GridRangeStyle134, GridRangeStyle135, GridRangeStyle136, GridRangeStyle137, GridRangeStyle138, GridRangeStyle139, GridRangeStyle140, GridRangeStyle141, GridRangeStyle142, GridRangeStyle143, GridRangeStyle144, GridRangeStyle145, GridRangeStyle146, GridRangeStyle147, GridRangeStyle148, GridRangeStyle149, GridRangeStyle150, GridRangeStyle151, GridRangeStyle152, GridRangeStyle153, GridRangeStyle154, GridRangeStyle155})
        Me.gridSituacion.RightToLeft = System.Windows.Forms.RightToLeft.No
        Me.gridSituacion.RowCount = 63
        Me.gridSituacion.RowHeightEntries.AddRange(New Syncfusion.Windows.Forms.Grid.GridRowHeight() {New Syncfusion.Windows.Forms.Grid.GridRowHeight(0, 25)})
        Me.gridSituacion.SerializeCellsBehavior = Syncfusion.Windows.Forms.Grid.GridSerializeCellsBehavior.SerializeAsRangeStylesIntoCode
        Me.gridSituacion.Size = New System.Drawing.Size(1328, 647)
        Me.gridSituacion.SmartSizeBox = False
        'Me.gridSituacion.SpreadsheetLikeSelection = False
        Me.gridSituacion.TabIndex = 250
        Me.gridSituacion.ThemesEnabled = True
        Me.gridSituacion.UseRightToLeftCompatibleTextBox = True
        '
        'frmSituacionFinanciera1
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.BorderThickness = 0
        Me.CaptionBarColor = System.Drawing.Color.WhiteSmoke
        Me.CaptionBarHeight = 55
        CaptionLabel1.Font = New System.Drawing.Font("Segoe UI", 8.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        CaptionLabel1.ForeColor = System.Drawing.Color.DimGray
        CaptionLabel1.Location = New System.Drawing.Point(30, 15)
        CaptionLabel1.Name = "CaptionLabel1"
        CaptionLabel1.Size = New System.Drawing.Size(180, 24)
        CaptionLabel1.Text = "Situación Financiera"
        Me.CaptionLabels.Add(CaptionLabel1)
        Me.ClientSize = New System.Drawing.Size(1328, 647)
        Me.Controls.Add(Me.gridSituacion)
        Me.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle
        Me.MaximizeBox = False
        Me.MinimizeBox = False
        Me.Name = "frmSituacionFinanciera1"
        Me.ShowIcon = False
        Me.Text = ""
        CType(Me.gridSituacion, System.ComponentModel.ISupportInitialize).EndInit()
        Me.ResumeLayout(False)

    End Sub
    Friend WithEvents gridSituacion As Syncfusion.Windows.Forms.Grid.GridControl
End Class
