'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class accionistasOtros
    Public Property idAccionista As Integer
    Public Property idEmpresa As String
    Public Property idEstablecimiento As Integer
    Public Property idDocIdentidad As String
    Public Property nroDoc As String
    Public Property appat As String
    Public Property apmat As String
    Public Property nombres As String
    Public Property fechanac As Nullable(Of Date)
    Public Property nacionalidad As String
    Public Property sexo As String
    Public Property fono As String
    Public Property email As String
    Public Property estado As String
    Public Property cuenta As String
    Public Property usuarioModificacion As String
    Public Property fechaModificacion As Nullable(Of Date)

End Class
