'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class activosfijosDatosRelacionados
    Public Property idActivo As Integer
    Public Property recorridoDiario As Nullable(Of Decimal)
    Public Property fechaCambio As Nullable(Of Date)
    Public Property kmActual As Nullable(Of Decimal)
    Public Property cambioSugerido_km As Nullable(Of Decimal)
    Public Property proxCambio_km As Nullable(Of Decimal)
    Public Property fechaProximoCambio As Nullable(Of Date)
    Public Property estado As Nullable(Of Integer)

    Public Overridable Property activosFijos As activosFijos

End Class
