'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class actividadSeguimiento
    Public Property Secuencia As Integer
    Public Property idActividad As Nullable(Of Integer)
    Public Property fechaInicioEjec As Nullable(Of Date)
    Public Property fechaFinEjec As Nullable(Of Date)
    Public Property horaInicioEjec As String
    Public Property horaFinEjec As String
    Public Property descrpcionEjec As String
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property Actividades As Actividades

End Class
