'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class actividadPersonal
    Public Property idActividad As Integer
    Public Property idPersona As Nullable(Of Integer)
    Public Property tipopersona As String
    Public Property nombre As String
    Public Property tipo As Nullable(Of Integer)
    Public Property costo As Nullable(Of Decimal)
    Public Property usuarioModificacion As Nullable(Of Integer)
    Public Property fechaModificacion As Nullable(Of Date)

    Public Overridable Property clasehorario_actividadPersonal As ICollection(Of clasehorario_actividadPersonal) = New HashSet(Of clasehorario_actividadPersonal)
    Public Overridable Property clasehorarios As ICollection(Of clasehorarios) = New HashSet(Of clasehorarios)

End Class
