'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class activosFijos
    Public Property idActivo As Integer
    Public Property idEntidad As Integer
    Public Property cuenta As String
    Public Property idEmpresa As String
    Public Property idEstablecimiento As Nullable(Of Integer)
    Public Property descripcionItem As String
    Public Property unidadMedida As String
    Public Property unidad2 As String
    Public Property tipoActivo As String
    Public Property anio As Nullable(Of Integer)
    Public Property nroSeriePlaca As String
    Public Property marca As String
    Public Property modelo As String
    Public Property motor As String
    Public Property color As String
    Public Property transimision As Nullable(Of Integer)
    Public Property odometro As Nullable(Of Decimal)
    Public Property sistemaCombustion As Nullable(Of Integer)
    Public Property combustible As Nullable(Of Integer)
    Public Property direccion As Nullable(Of Integer)
    Public Property destinoGravado As String
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property empresa As empresa
    Public Overridable Property entidad As entidad
    Public Overridable Property activosfijosDatosRelacionados As activosfijosDatosRelacionados

End Class
