'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class actividadRecurso
    Public Property idActividadRecurso As Integer
    Public Property idActividad As Integer
    Public Property idProyecto As Nullable(Of Integer)
    Public Property tipoActividad As String
    Public Property fechaIngreso As Nullable(Of Date)
    Public Property TipoRecurso As String
    Public Property idItem As Nullable(Of Integer)
    Public Property cuentaContable As String
    Public Property Descripcion As String
    Public Property detalleExtra As String
    Public Property unidadMedida As String
    Public Property ValorMercadoPu As Nullable(Of Decimal)
    Public Property CantRequerida As Nullable(Of Decimal)
    Public Property TotalCosto As Nullable(Of Decimal)
    Public Property PsptoReferencial As Nullable(Of Decimal)
    Public Property ReferenciaSustento As String
    Public Property Costo As Nullable(Of Decimal)
    Public Property NoSustentado As Nullable(Of Decimal)
    Public Property PorIgv As String
    Public Property Igv As Nullable(Of Decimal)
    Public Property Total As Nullable(Of Decimal)
    Public Property PorDeducPlanilla As String
    Public Property DeducPlanilla As Nullable(Of Decimal)
    Public Property PorOtrosDeduc As String
    Public Property OtrosDeduc As Nullable(Of Decimal)
    Public Property TotalDeduc As Nullable(Of Decimal)
    Public Property NetoPagar As Nullable(Of Decimal)
    Public Property PorAporPlanilla As String
    Public Property AporPlanilla As Nullable(Of Decimal)
    Public Property PorOtros1 As String
    Public Property Otros1 As Nullable(Of Decimal)
    Public Property TotalAporte As Nullable(Of Decimal)
    Public Property TotalRetenciones As Nullable(Of Decimal)
    Public Property PorImpor1 As String
    Public Property Impor1 As Nullable(Of Decimal)
    Public Property PorImpor2 As String
    Public Property Impor2 As Nullable(Of Decimal)
    Public Property TotalImpor As Nullable(Of Decimal)
    Public Property TipoPresupuesto As String
    Public Property CostoDirecto As Nullable(Of Decimal)
    Public Property PorGastosGenerales As String
    Public Property GastosGenerales As Nullable(Of Decimal)
    Public Property PorUtilidad As String
    Public Property Utilidad As Nullable(Of Decimal)
    Public Property PorOtrosIn1 As Nullable(Of Decimal)
    Public Property OtrosIn1 As String
    Public Property ValorVenta As Nullable(Of Decimal)
    Public Property Porcentaje As String
    Public Property TotalProyecto As Nullable(Of Decimal)
    Public Property PorPercep As String
    Public Property Percepciones As Nullable(Of Decimal)
    Public Property PorOtrosIn2 As String
    Public Property OtrosIn2 As Nullable(Of Decimal)
    Public Property TotalPorCobrar As Nullable(Of Decimal)
    Public Property PorDetracciones As String
    Public Property Detracciones As Nullable(Of Decimal)
    Public Property PorRetenciones As String
    Public Property Retenciones As Nullable(Of Decimal)
    Public Property PorOtroIn3 As String
    Public Property OtroIn3 As Nullable(Of Decimal)
    Public Property NetoCobrar As Nullable(Of Decimal)
    Public Property PorcentajeIngre As String
    Public Property TipoIncidencia As String
    Public Property tipoPlan As String
    Public Property idOrden As Nullable(Of Integer)
    Public Property Sustentado As String

    Public Overridable Property Actividades As Actividades
    Public Overridable Property detalleitems As detalleitems
    Public Overridable Property actividadRecursoCalculo As actividadRecursoCalculo
    Public Overridable Property proyectoAvance As ICollection(Of proyectoAvance) = New HashSet(Of proyectoAvance)

End Class
