'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class actividadRecursoCalculo
    Public Property idActividadRecurso As Integer
    Public Property laborDiaria As Nullable(Of Decimal)
    Public Property hm As Nullable(Of Decimal)
    Public Property porcentaje As Nullable(Of Decimal)
    Public Property dias As Nullable(Of Decimal)
    Public Property costoUnithh As Nullable(Of Decimal)
    Public Property cant As Nullable(Of Decimal)
    Public Property costoUnit As Nullable(Of Decimal)
    Public Property costoDirecto1 As Nullable(Of Decimal)
    Public Property costoDirecto2 As Nullable(Of Decimal)
    Public Property ggPorc As Nullable(Of Decimal)
    Public Property ggImporte As Nullable(Of Decimal)
    Public Property utPorc As Nullable(Of Decimal)
    Public Property utImporte As Nullable(Of Decimal)
    Public Property costoFinal As Nullable(Of Decimal)
    Public Property igvPorc As Nullable(Of Decimal)
    Public Property igvImporte As Nullable(Of Decimal)
    Public Property precioFinal As Nullable(Of Decimal)
    Public Property cantFinal As Nullable(Of Decimal)
    Public Property precUnitFinal As Nullable(Of Decimal)

    Public Overridable Property actividadRecurso As actividadRecurso

End Class
