'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class almacen
    Public Property idEmpresa As String
    Public Property idAlmacen As Integer
    Public Property idEstablecimiento As Nullable(Of Integer)
    Public Property descripcionAlmacen As String
    Public Property encargado As String
    Public Property tipo As String
    Public Property estado As String
    Public Property predeterminado As String
    Public Property porcentajeUtilidad As Nullable(Of Decimal)
    Public Property direccionAlmacen As String
    Public Property usuarioModificacion As String
    Public Property fechaModificacion As Nullable(Of Date)

    Public Overridable Property centrocosto As centrocosto
    Public Overridable Property InventarioMovimiento As ICollection(Of InventarioMovimiento) = New HashSet(Of InventarioMovimiento)

End Class
