'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class anticipos
    Public Property idDocumento As Integer
    Public Property idEmpresa As String
    Public Property idEstablecimiento As Nullable(Of Integer)
    Public Property tipoMovimiento As String
    Public Property fechaPeriodo As String
    Public Property fechaProceso As Nullable(Of Date)
    Public Property tipoDoc As String
    Public Property numero As String
    Public Property moneda As String
    Public Property idEntidad As Nullable(Of Integer)
    Public Property nombreEntidad As String
    Public Property tipoEntidad As String
    Public Property tipocambio As Nullable(Of Decimal)
    Public Property formaPago As String
    Public Property idEstablecimientoCaja As Nullable(Of Integer)
    Public Property entidadFinanciera As Nullable(Of Integer)
    Public Property nombreFinanciera As String
    Public Property importeMN As Nullable(Of Decimal)
    Public Property importeME As Nullable(Of Decimal)
    Public Property glosa As String
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property documento As documento

End Class
