'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class articuloplantilla
    Public Property idarticulo As Integer
    Public Property secuencia As Integer
    Public Property idpadre As Nullable(Of Integer)
    Public Property descripcion As String
    Public Property cant As Nullable(Of Decimal)
    Public Property otros As String

    Public Overridable Property detalleitems As detalleitems

End Class
