'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class asientoContablePlantilla
    Public Property idplantilla As Integer
    Public Property tipoOperacion As String
    Public Property cuenta As String
    Public Property tipo As String

End Class
