'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class asiento
    Public Property idAsiento As Integer
    Public Property idDocumento As Integer
    Public Property idEmpresa As String
    Public Property idCentroCostos As Integer
    Public Property idDocumentoRef As String
    Public Property idAlmacen As String
    Public Property nombreAlmacen As String
    Public Property idEntidad As String
    Public Property nombreEntidad As String
    Public Property tipoEntidad As String
    Public Property fechaProceso As Nullable(Of Date)
    Public Property periodo As String
    Public Property codigoLibro As String
    Public Property tipo As String
    Public Property tipoAsiento As String
    Public Property importeMN As Nullable(Of Decimal)
    Public Property importeME As Nullable(Of Decimal)
    Public Property glosa As String
    Public Property sunat As String
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property movimiento As ICollection(Of movimiento) = New HashSet(Of movimiento)
    Public Overridable Property documento As documento

End Class
