'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class beneficio
    Public Property beneficio_id As Integer
    Public Property idEmpresa As String
    Public Property idOrganizacion As Nullable(Of Integer)
    Public Property tipoTabla As String
    Public Property detalleBeneficio As String
    Public Property tipoBeneficio As Nullable(Of Integer)
    Public Property beneficioReferencia As Nullable(Of Integer)
    Public Property beneficioReferenciaCantidad As Nullable(Of Decimal)
    Public Property afectoComprobante As Nullable(Of Boolean)
    Public Property tipoAfectacion As String
    Public Property importeBase As Nullable(Of Decimal)
    Public Property valorConvertido As Nullable(Of Decimal)
    Public Property vigencia As Nullable(Of Date)
    Public Property esPremioRegaloBonif As Nullable(Of Boolean)
    Public Property idCliente As Nullable(Of Integer)
    Public Property produccion_id As Nullable(Of Integer)
    Public Property estado As Nullable(Of Integer)

    Public Overridable Property entidad As entidad
    Public Overridable Property beneficioDetalle As ICollection(Of beneficioDetalle) = New HashSet(Of beneficioDetalle)

End Class
