'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class beneficioConsumo
    Public Property consumo_id As Integer
    Public Property beneficio_id As Integer
    Public Property produccion_id As Integer
    Public Property idEntidad As Nullable(Of Integer)
    Public Property fechaConsumo As Nullable(Of Date)
    Public Property valorConsumo As Nullable(Of Decimal)
    Public Property beneficioUsado As Nullable(Of Boolean)

    Public Overridable Property entidad As entidad

End Class
