'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class beneficioDetalle
    Public Property secuencia As Integer
    Public Property beneficio_id As Integer
    Public Property iditem As Nullable(Of Integer)
    Public Property cantidad As Nullable(Of Decimal)
    Public Property almacen As Nullable(Of Integer)

    Public Overridable Property beneficio As beneficio

End Class
