'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class beneficioProduccionConsumo
    Public Property produccion_id As Integer
    Public Property fechaEmision As Nullable(Of Date)
    Public Property tipo As String
    Public Property descripcion As String
    Public Property valorbase As Nullable(Of Decimal)
    Public Property valor As Nullable(Of Decimal)
    Public Property moneda As String
    Public Property tieneVigencia As Nullable(Of Boolean)
    Public Property Vigencia As Nullable(Of Date)
    Public Property nroImpresionMax As Nullable(Of Integer)

End Class
