'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class cajaUsuariodetalle
    Public Property idcajaUsuario As Integer
    Public Property secuencia As Integer
    Public Property idEntidad As Nullable(Of Integer)
    Public Property moneda As String
    Public Property importeMN As Nullable(Of Decimal)
    Public Property importeME As Nullable(Of Decimal)
    Public Property idConfiguracion As Nullable(Of Integer)
    Public Property tipoCambio As Nullable(Of Decimal)
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property cajaUsuario As cajaUsuario

End Class
