'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class cajaUsuarioDineroEntregado
    Public Property entrega_id As Integer
    Public Property idcajaUsuario As Integer
    Public Property equivalencia As Nullable(Of Decimal)
    Public Property cantidad As Nullable(Of Integer)
    Public Property importe As Nullable(Of Decimal)
    Public Property usuarioActualizacion As Nullable(Of Integer)
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property cajaUsuario As cajaUsuario

End Class
