'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class caracteristicaItem
    Public Property idCaracteristica As Integer
    Public Property codigodetalle As Integer
    Public Property idSubClasificacion As Integer
    Public Property tipo As String
    Public Property idPadre As Nullable(Of Integer)
    Public Property campo As String
    Public Property descripcion As String

End Class
