'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class centroCostoHorario
    Public Property idCentroCostoHorario As Integer
    Public Property idEmpresa As String
    Public Property idCentroCosto As Integer
    Public Property diaInicio As Nullable(Of Integer)
    Public Property diaFin As Nullable(Of Integer)
    Public Property horarioInicio As Nullable(Of Date)
    Public Property horarioFin As Nullable(Of Date)
    Public Property estado As String
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property centrocosto As centrocosto
    Public Overridable Property comercioEspecializado_Precio As ICollection(Of comercioEspecializado_Precio) = New HashSet(Of comercioEspecializado_Precio)

End Class
