'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class centroCostosXNComercial
    Public Property idEmpresa As String
    Public Property idCentroCosto As Integer
    Public Property IdNegocioComercial As Integer
    Public Property EstaAutorizado As String
    Public Property idUsuario As Nullable(Of Integer)
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property centrocosto As centrocosto
    Public Overridable Property negocioComercial As negocioComercial

End Class
