'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class cierreinventario
    Public Property idEmpresa As String
    Public Property idCentroCosto As Integer
    Public Property periodo As String
    Public Property idAlmacen As Integer
    Public Property idItem As Integer
    Public Property codigoLote As Integer
    Public Property idDocumento As Integer
    Public Property anio As Nullable(Of Integer)
    Public Property mes As Nullable(Of Integer)
    Public Property dia As Nullable(Of Integer)
    Public Property cantidad As Nullable(Of Decimal)
    Public Property importe As Nullable(Of Decimal)
    Public Property importeUS As Nullable(Of Decimal)
    Public Property unidad As String
    Public Property usuarioModificacion As String
    Public Property fechaModificacion As Nullable(Of Date)

    Public Overridable Property documento As documento

End Class
