'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class cierreResultados
    Public Property idEmpresa As String
    Public Property idCentroCosto As Integer
    Public Property periodo As String
    Public Property idDocumento As Integer
    Public Property anio As Nullable(Of Integer)
    Public Property mes As Nullable(Of Integer)
    Public Property montoImpuesto As Nullable(Of Decimal)
    Public Property montoImpuestoUSD As Nullable(Of Decimal)
    Public Property utilidadPerdida As Nullable(Of Decimal)
    Public Property utilidadPerdidaUSD As Nullable(Of Decimal)
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property documento As documento

End Class
