'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class cierreCaja
    Public Property secuencia As Integer
    Public Property idEntidadFinanciera As Nullable(Of Integer)
    Public Property idEmpresa As String
    Public Property idEstablecimiento As Nullable(Of Integer)
    Public Property periodo As String
    Public Property fechaProceso As Nullable(Of Date)
    Public Property idDocumento As Nullable(Of Integer)
    Public Property anio As Nullable(Of Integer)
    Public Property mes As Nullable(Of Integer)
    Public Property dia As Nullable(Of Integer)
    Public Property montoMN As Nullable(Of Decimal)
    Public Property montoME As Nullable(Of Decimal)
    Public Property tipoCaja As String
    Public Property idcajaUsuario As Nullable(Of Integer)
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property documento As documento

End Class
