'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class clasehorarios
    Public Property idclasehorario As Integer
    Public Property idActividad As Integer
    Public Property textInfo As String
    Public Property dia As String
    Public Property fechainicio As Nullable(Of Date)
    Public Property fechafin As Nullable(Of Date)
    Public Property horainicio As Nullable(Of System.TimeSpan)
    Public Property horafin As Nullable(Of System.TimeSpan)
    Public Property idinstructor As Nullable(Of Integer)
    Public Property costo As Nullable(Of Decimal)
    Public Property status As Nullable(Of Integer)
    Public Property aforo As Nullable(Of Integer)
    Public Property usuarioModificacion As Nullable(Of Integer)
    Public Property fechaModificacion As Nullable(Of Date)

    Public Overridable Property actividadPersonal As actividadPersonal

End Class
