'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class comercioEspecializado_Precio
    Public Property idComercioEspecializado As Integer
    Public Property idCentroCostoHorario As Integer
    Public Property idDistribucion As Integer
    Public Property idComponente As Integer
    Public Property idEmpresa As String
    Public Property idEstablecimiento As Integer
    Public Property idActivo As Nullable(Of Integer)
    Public Property origen As Nullable(Of Integer)
    Public Property moneda As String
    Public Property numeracion As String
    Public Property precioAsientoMN As Nullable(Of Decimal)
    Public Property precioAsientoME As Nullable(Of Decimal)
    Public Property idConfiguracion As Nullable(Of Integer)
    Public Property idItem As Nullable(Of Integer)
    Public Property descripcionItem As String
    Public Property destino As Nullable(Of Integer)
    Public Property estado As String
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property centroCostoHorario As centroCostoHorario
    Public Overridable Property distribucionInfraestructura As distribucionInfraestructura

End Class
