'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class componenteXDistribucion
    Public Property idComponenteXDistribucion As Integer
    Public Property idDistribucionComponente As Integer
    Public Property idEmpresa As String
    Public Property idEstablecimiento As Integer
    Public Property idActivoEnvio As Integer
    Public Property descripcionComponenteXDistribucion As String
    Public Property tipoComponente As String
    Public Property imagenUbicacion As String
    Public Property estado As String
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property ActivoDistribucion As ActivoDistribucion
    Public Overridable Property distribucionComponente As distribucionComponente

End Class
