'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class composicion
    Public Property idComposicion As Integer
    Public Property idProducto As Integer
    Public Property codigoDetalle As Nullable(Of Integer)
    Public Property idEmpresa As String
    Public Property idEstablecimiento As Nullable(Of Integer)
    Public Property origen As Nullable(Of Integer)
    Public Property tipoInventario As String
    Public Property cantidad As Nullable(Of Decimal)
    Public Property descripcionComposicion As String
    Public Property equivalencia As Nullable(Of Decimal)
    Public Property unidadMedida As String
    Public Property pumn As Nullable(Of Decimal)
    Public Property pume As Nullable(Of Decimal)
    Public Property importeMN As Nullable(Of Decimal)
    Public Property importeME As Nullable(Of Decimal)
    Public Property observacion As String
    Public Property estado As String
    Public Property tipoExistencia As String
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property detalleitems As detalleitems
    Public Overridable Property servicio As servicio

End Class
