'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Compensacion
    Public Property idDocumentoOrigen As Integer
    Public Property idDocumentoDestino As Integer
    Public Property operacionOrigen As String
    Public Property operacionDestino As String

End Class
