'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class componente
    Public Property idComponente As Integer
    Public Property idActivo As Nullable(Of Integer)
    Public Property idEmpresa As String
    Public Property idEstablecimiento As Nullable(Of Integer)
    Public Property idPadre As Nullable(Of Integer)
    Public Property idItem As Nullable(Of Integer)
    Public Property descripcionItem As String
    Public Property estado As String
    Public Property tipo As String
    Public Property imagen As String
    Public Property direccionImagen As String
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property distribucionComponente As ICollection(Of distribucionComponente) = New HashSet(Of distribucionComponente)
    Public Overridable Property distribucionInfraestructura As ICollection(Of distribucionInfraestructura) = New HashSet(Of distribucionInfraestructura)

End Class
