'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class configuracionPrecioProducto
    Public Property idPrecioProducto As Integer
    Public Property idOriganizacion As Nullable(Of Integer)
    Public Property idPrecio As Integer
    Public Property idproducto As Integer
    Public Property fecha As Date
    Public Property tipo As String
    Public Property valPorcentaje As Decimal
    Public Property nroLote As Nullable(Of Integer)
    Public Property descripcion As String
    Public Property tipoModalidad As String
    Public Property unidadAsignadainicio As String
    Public Property unidadAsignadafin As String
    Public Property validaStock As Nullable(Of Boolean)
    Public Property precioMN As Nullable(Of Decimal)
    Public Property precioME As Nullable(Of Decimal)
    Public Property usuarioActualizacion As Nullable(Of Integer)
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property configuracionPrecio As configuracionPrecio

End Class
