'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class configuracionReserva
    Public Property idConfiguracion As Integer
    Public Property idEmpresa As String
    Public Property idEstablecimiento As Nullable(Of Integer)
    Public Property descripcion As String
    Public Property color As String
    Public Property abreviatura As String
    Public Property estado As String
    Public Property usuarioActualizacion As String
    Public Property fechaModificacion As Nullable(Of Date)

End Class
