'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CronogramaRepartos
    Public Property idReparto As Integer
    Public Property idDocumento As Integer
    Public Property idProductoVenta As Integer
    Public Property fechaEntrega As Nullable(Of Date)
    Public Property tipoOperacion As String
    Public Property departamento As String
    Public Property provincia As String
    Public Property distrito As String
    Public Property direccionGeneral As String
    Public Property direccionReferencial As String
    Public Property contacto As String
    Public Property contactoTelefono As String
    Public Property codigoDetalle As Nullable(Of Integer)
    Public Property detalle As String
    Public Property cantidad As Nullable(Of Decimal)
    Public Property status As Nullable(Of Integer)
    Public Property usuarioActualizacion As Nullable(Of Integer)
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property documentoventaAbarrotesDet As documentoventaAbarrotesDet

End Class
