'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class cuentaMascara
    Public Property idcuentaMascara As Integer
    Public Property idEmpresa As String
    Public Property parametro As String
    Public Property cuentaBase As String
    Public Property cuentaEspecifica As String
    Public Property tipoAsiento As String
    Public Property tipo As String
    Public Property idModulo As String

End Class
