'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class cuentaplanContableEmpresa
    Public Property idEmpresa As String
    Public Property cuenta As String
    Public Property cuentaPadre As String
    Public Property descripcion As String
    Public Property Observaciones As String
    Public Property idCosto As Nullable(Of Integer)
    Public Property usuarioModificacion As String
    Public Property fechaModificacion As Nullable(Of Date)

    Public Overridable Property empresa As empresa

End Class
