'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class datosGenerales
    Public Property idConfiguracion As Integer
    Public Property idEmpresa As String
    Public Property idEstablecimiento As Nullable(Of Integer)
    Public Property idclientespk As String
    Public Property razonSocial As String
    Public Property nombreCorto As String
    Public Property ruc As String
    Public Property direccionPrincipal As String
    Public Property direccionSecudaria As String
    Public Property telefono1 As String
    Public Property telefono2 As String
    Public Property telefono3 As String
    Public Property telefono4 As String
    Public Property e_mail As String
    Public Property password As String
    Public Property logo As String
    Public Property posicionLogo As String
    Public Property formaLogo As String
    Public Property nombreGiro As String
    Public Property formaImpresion As String
    Public Property formatoImpresion As String
    Public Property nombreImpresion As String
    Public Property tipoImpresion As String
    Public Property publicidad As String
    Public Property condicionImpresion As String
    Public Property nroImpresion As Nullable(Of Integer)
    Public Property predeterminado As Nullable(Of Integer)
    Public Property formato As String
    Public Property nroCuentaSoles As String
    Public Property nroCuentaSoles2 As String
    Public Property nroCuentaDolares As String
    Public Property nroCuentaDolares2 As String
    Public Property glosario As String
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)
    Public Property nroCuentaDetraccion As String
    Public Property nroCuentaDetraccion2 As String

End Class
