'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class detalleitemcatalogo_comision
    Public Property idComision As Integer
    Public Property empresa As String
    Public Property unidadNegocio As Nullable(Of Integer)
    Public Property codigodetalle As Integer
    Public Property equivalencia_id As Integer
    Public Property idCatalogo As Integer
    Public Property nombre_comision As String
    Public Property tipo_comision As String
    Public Property bloqueado As Nullable(Of Boolean)
    Public Property vigencia As Nullable(Of Date)
    Public Property apartir_de As Nullable(Of Decimal)
    Public Property montoMaximo As Nullable(Of Decimal)
    Public Property montoMinimo As Nullable(Of Decimal)

    Public Overridable Property detalleitemcatalogo_comisiondetalle As List(Of detalleitemcatalogo_comisiondetalle) = New HashSet(Of detalleitemcatalogo_comisiondetalle)().ToList

End Class
