'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class detalleitem_precios
    Public Property precio_id As Integer
    Public Property codigodetalle As Integer
    Public Property tipo_rango As String
    Public Property rango_inicio As Nullable(Of Integer)
    Public Property rango_final As Nullable(Of Integer)
    Public Property tipo_precio As String
    Public Property ultimoCosto As Nullable(Of Decimal)
    Public Property VContadoPrecioConIgv As Nullable(Of Decimal)
    Public Property VContadoPrecioSinIgv As Nullable(Of Decimal)
    Public Property VCreditoPrecioConIgv As Nullable(Of Decimal)
    Public Property VCreditoPrecioSinIgv As Nullable(Of Decimal)
    Public Property estado As String
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property detalleitems As detalleitems

End Class
