'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class detalleitemequivalencia_beneficio
    Public Property beneficio_id As Integer
    Public Property codigodetalle As Integer
    Public Property equivalencia_id As Integer
    Public Property modalidadVenta As String
    Public Property beneficio_detalle As String
    Public Property tipobeneficio As String
    Public Property aplica As String
    Public Property tipoafectacion As String
    Public Property valor_evaluado As Nullable(Of Decimal)
    Public Property valor_conversion As String
    Public Property valor_beneficio As Nullable(Of Decimal)
    Public Property lote_id As Nullable(Of Integer)
    Public Property estado As Nullable(Of Integer)
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property detalleitem_equivalencias As detalleitem_equivalencias

End Class
