'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class detalleitems
    Public Property codigodetalle As Integer
    Public Property idItem As Nullable(Of Integer)
    Public Property idEmpresa As String
    Public Property idEstablecimiento As Nullable(Of Integer)
    Public Property cuenta As String
    Public Property descripcionItem As String
    Public Property presentacion As String
    Public Property unidad1 As String
    Public Property unidad2 As String
    Public Property tipoExistencia As String
    Public Property origenProducto As String
    Public Property tipoProducto As String
    Public Property cProductor As String
    Public Property cProveedor As String
    Public Property modelo As String
    Public Property composicion As String
    Public Property talla As String
    Public Property color As String
    Public Property nroOrden As String
    Public Property codigo As String
    Public Property capacidad As String
    Public Property presion As String
    Public Property electricidad As String
    Public Property transmision As String
    Public Property rpm As String
    Public Property marcaRef As String
    Public Property nivelRuido As String
    Public Property Peso As String
    Public Property Filtros As String
    Public Property Retencion As Nullable(Of Boolean)
    Public Property ValorRetencion As Nullable(Of Decimal)
    Public Property Percepcion As Nullable(Of Boolean)
    Public Property ValorPercepcion As Nullable(Of Decimal)
    Public Property AfectoCompra As Nullable(Of Boolean)
    Public Property AfectoVenta As Nullable(Of Boolean)
    Public Property AfectoStock As Nullable(Of Boolean)
    Public Property preciocompratipo As String
    Public Property precioCompra As Nullable(Of Decimal)
    Public Property firstpercent As Nullable(Of Decimal)
    Public Property beforepercent As Nullable(Of Decimal)
    Public Property productoRestringido As Nullable(Of Boolean)
    Public Property igv As Nullable(Of Decimal)
    Public Property tipoOtroImpuesto As String
    Public Property otroImpuesto As Nullable(Of Decimal)
    Public Property cantidadMaxima As Nullable(Of Decimal)
    Public Property cantidadMinima As Nullable(Of Decimal)
    Public Property fotoUrl As String
    Public Property estado As String
    Public Property tipoItem As String
    Public Property tipoBien As String
    Public Property idCaracteristica As Nullable(Of Integer)
    Public Property idClasificacion As Nullable(Of Integer)
    Public Property codigoInterno As String
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property actividadRecurso As List(Of actividadRecurso) = New HashSet(Of actividadRecurso)().ToList
    Public Overridable Property articuloplantilla As List(Of articuloplantilla) = New HashSet(Of articuloplantilla)().ToList
    Public Overridable Property composicion1 As List(Of composicion) = New HashSet(Of composicion)().ToList
    Public Overridable Property detalleitem_equivalencias As List(Of detalleitem_equivalencias) = New HashSet(Of detalleitem_equivalencias)().ToList
    Public Overridable Property detalleitem_precios As List(Of detalleitem_precios) = New HashSet(Of detalleitem_precios)().ToList
    Public Overridable Property detalleitems_conexo As List(Of detalleitems_conexo) = New HashSet(Of detalleitems_conexo)().ToList
    Public Overridable Property item As item
    Public Overridable Property InventarioMovimiento As List(Of InventarioMovimiento) = New HashSet(Of InventarioMovimiento)().ToList
    Public Overridable Property ProductoXAreaOperativa As List(Of productoxAreaOperativa) = New HashSet(Of productoxAreaOperativa)().ToList
    Public Overridable Property recursoCostoLote As List(Of recursoCostoLote) = New HashSet(Of recursoCostoLote)().ToList
    Public Overridable Property sist_recaudacion As List(Of sist_recaudacion) = New HashSet(Of sist_recaudacion)().ToList
    Public Overridable Property totalesAlmacen As List(Of totalesAlmacen) = New HashSet(Of totalesAlmacen)().ToList

End Class
