'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class detalleitems_conexo
    Public Property conexo_id As Integer
    Public Property codigodetalle As Integer
    Public Property idProducto As Nullable(Of Integer)
    Public Property detalle As String
    Public Property cantidad As Nullable(Of Decimal)
    Public Property equivalencia_id As Nullable(Of Integer)
    Public Property unidadComercial As String
    Public Property fraccion As Nullable(Of Decimal)
    Public Property estado As Nullable(Of Integer)
    Public Property vigencia As Nullable(Of Date)
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property detalleitems As detalleitems

End Class
