'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class detalleitemequivalencia_precios
    Public Property precio_id As Integer
    Public Property idCatalogo As Integer
    Public Property codigodetalle As Integer
    Public Property equivalencia_id As Integer
    Public Property tipoPrecio As String
    Public Property tipoConfiguracion As String
    Public Property rango_inicio As Nullable(Of Decimal)
    Public Property rango_final As Nullable(Of Decimal)
    Public Property precioCode As String
    Public Property precio As Nullable(Of Decimal)
    Public Property precioUSD As Nullable(Of Decimal)
    Public Property precioCredito As Nullable(Of Decimal)
    Public Property precioCreditoUSD As Nullable(Of Decimal)
    Public Property estado As Nullable(Of Integer)
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property detalleitemequivalencia_catalogos As detalleitemequivalencia_catalogos

End Class
