'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class distribucionComponente
    Public Property idDistribucionComponente As Integer
    Public Property idComponente As Integer
    Public Property idEmpresa As String
    Public Property idEstablecimiento As Integer
    Public Property descripcionDistribucion As String
    Public Property tipo As String
    Public Property dimension As String
    Public Property primeraCarateristica As String
    Public Property segundaCaracteristica As String
    Public Property imagenUbicacion As String
    Public Property estado As String
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property componente As componente
    Public Overridable Property componenteXDistribucion As ICollection(Of componenteXDistribucion) = New HashSet(Of componenteXDistribucion)

End Class
