'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class distribucionInfraestructura
    Public Property idDistribucion As Integer
    Public Property idEmpresa As String
    Public Property idEstablecimiento As Nullable(Of Integer)
    Public Property idComponente As Integer
    Public Property codigoServicio As Nullable(Of Integer)
    Public Property idInfraestructura As Nullable(Of Integer)
    Public Property idTipoServicio As Nullable(Of Integer)
    Public Property descripcionDistribucion As String
    Public Property glosario As String
    Public Property estado As String
    Public Property tipo As String
    Public Property numeracion As String
    Public Property directorio As String
    Public Property logoID As Nullable(Of Integer)
    Public Property aforo As Nullable(Of Integer)
    Public Property idServicioInfraestructura As Nullable(Of Integer)
    Public Property idDetalleItem As Nullable(Of Integer)
    Public Property idActivo As Nullable(Of Integer)
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property comercioEspecializado_Precio As ICollection(Of comercioEspecializado_Precio) = New HashSet(Of comercioEspecializado_Precio)
    Public Overridable Property componente As componente
    Public Overridable Property infraestructura As infraestructura
    Public Overridable Property tipoServicioInfraestructura As tipoServicioInfraestructura
    Public Overridable Property ocupacionInfraestructura As ICollection(Of ocupacionInfraestructura) = New HashSet(Of ocupacionInfraestructura)
    Public Overridable Property vehiculoAsiento_Precios As ICollection(Of vehiculoAsiento_Precios) = New HashSet(Of vehiculoAsiento_Precios)

End Class
