'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class distritos
    Public Property id As String
    Public Property name As String
    Public Property province_id As String
    Public Property region_id As String
    Public Property created_at As String
    Public Property updated_at As String

    Public Overridable Property provincias As provincias

End Class
