'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class distribucionNumeracionAO
    Public Property idDistribucionNumeracion As Integer
    Public Property IdEnumeracion As Integer
    Public Property idCargo As Integer
    Public Property idRol As Integer
    Public Property idCentroCosto As Nullable(Of Integer)
    Public Property estado As String
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property numeracionBoletas As numeracionBoletas
    Public Overridable Property perfilAnexo As perfilAnexo

End Class
