'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class documentoLibroDiario
    Public Property idDocumento As Integer
    Public Property idEmpresa As String
    Public Property idEstablecimiento As Nullable(Of Integer)
    Public Property tipoRegistro As String
    Public Property fecha As Nullable(Of Date)
    Public Property fechaPeriodo As String
    Public Property infoReferencial As String
    Public Property tipoRazonSocial As String
    Public Property razonSocial As Nullable(Of Integer)
    Public Property tipoDoc As String
    Public Property nroDoc As String
    Public Property tipoOperacion As String
    Public Property moneda As String
    Public Property tipoCambio As Nullable(Of Decimal)
    Public Property importeMN As Nullable(Of Decimal)
    Public Property importeME As Nullable(Of Decimal)
    Public Property idReferencia As Nullable(Of Integer)
    Public Property tieneCosto As String
    Public Property idCosto As Nullable(Of Integer)
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)
    Public Property fechaVct As Nullable(Of Date)
    Public Property modulo As String
    Public Property idDocReferencia As Nullable(Of Integer)
    Public Property estado As String

    Public Overridable Property documento As documento
    Public Overridable Property documentoLibroDiarioDetalle As ICollection(Of documentoLibroDiarioDetalle) = New HashSet(Of documentoLibroDiarioDetalle)

End Class
