'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class documentoNotasAbarrotes
    Public Property idDocumento As Integer
    Public Property idEmpresa As String
    Public Property idEstablecimiento As Nullable(Of Integer)
    Public Property tipoNota As String
    Public Property detalle As String
    Public Property tipoDoc As String
    Public Property periodo As String
    Public Property fechaProceso As Nullable(Of Date)
    Public Property serie As String
    Public Property numero As String
    Public Property tipoCambio As Nullable(Of Decimal)
    Public Property importeNacional As Nullable(Of Decimal)
    Public Property importeExtranjero As Nullable(Of Decimal)
    Public Property moneda As String
    Public Property documentoAfectado As Nullable(Of Integer)
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property documento As documento

End Class
