'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class documentoOperacionesPrestamo
    Public Property idDocumento As Integer
    Public Property idEmpresa As String
    Public Property idEstablecimiento As Integer
    Public Property cuentaContable As String
    Public Property idBeneficiario As Nullable(Of Integer)
    Public Property tipoBeneficiario As String
    Public Property tipoMovimiento As String
    Public Property tipoDocumento As String
    Public Property numeroDocumento As String
    Public Property fechaOperacion As Nullable(Of Date)
    Public Property fechaCobro As Nullable(Of Date)
    Public Property glosa As String
    Public Property entidadFinanciera As String
    Public Property numeroOperacion As String
    Public Property moneda As String
    Public Property tipoCambio As Nullable(Of Decimal)
    Public Property montoSoles As Nullable(Of Decimal)
    Public Property montoDolares As Nullable(Of Decimal)
    Public Property montoInteresSoles As Nullable(Of Decimal)
    Public Property montoInteresUSD As Nullable(Of Decimal)
    Public Property montoITFSoles As Nullable(Of Decimal)
    Public Property montoITFUSD As Nullable(Of Decimal)
    Public Property entregado As String
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property documento As documento

End Class
