'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class documentoguiaDetalle
    Public Property idDocumento As Integer
    Public Property secuencia As Integer
    Public Property idItem As String
    Public Property tipoExistencia As String
    Public Property descripcionItem As String
    Public Property destino As String
    Public Property unidadMedida As String
    Public Property cantidad As Nullable(Of Decimal)
    Public Property precioUnitario As Nullable(Of Decimal)
    Public Property precioUnitarioUS As Nullable(Of Decimal)
    Public Property importeMN As Nullable(Of Decimal)
    Public Property importeME As Nullable(Of Decimal)
    Public Property almacenRef As Nullable(Of Integer)
    Public Property idDocumentoPadre As Nullable(Of Integer)
    Public Property secuenciaRef As Nullable(Of Integer)
    Public Property estado As String
    Public Property puntoLlegada As String
    Public Property observaciones As String
    Public Property ubigeo As String
    Public Property nombreRecepcion As String
    Public Property dniRecepcion As String
    Public Property usuarioModificacion As String
    Public Property fechaModificacion As Nullable(Of Date)
    Public Property nombreComercial As String
    Public Property contenido_neto As Nullable(Of Decimal)

    Public Overridable Property documentoGuia As documentoGuia
    Public Overridable Property documentoguiaDetalleCondicion As ICollection(Of documentoguiaDetalleCondicion) = New HashSet(Of documentoguiaDetalleCondicion)

End Class
