'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class documentocompradetalle
    Public Property idDocumento As Integer
    Public Property secuencia As Integer
    Public Property idItem As String
    Public Property descripcionItem As String
    Public Property tipoExistencia As String
    Public Property destino As String
    Public Property unidad1 As String
    Public Property monto1 As Nullable(Of Decimal)
    Public Property equivalencia_id As Nullable(Of Integer)
    Public Property unidad2 As String
    Public Property monto2 As String
    Public Property precioUnitario As Nullable(Of Decimal)
    Public Property precioUnitarioUS As Nullable(Of Decimal)
    Public Property importe As Nullable(Of Decimal)
    Public Property importeUS As Nullable(Of Decimal)
    Public Property montokardex As Nullable(Of Decimal)
    Public Property montoIsc As Nullable(Of Decimal)
    Public Property montoIgv As Nullable(Of Decimal)
    Public Property otrosTributos As Nullable(Of Decimal)
    Public Property montokardexUS As Nullable(Of Decimal)
    Public Property montoIscUS As Nullable(Of Decimal)
    Public Property montoIgvUS As Nullable(Of Decimal)
    Public Property otrosTributosUS As Nullable(Of Decimal)
    Public Property preEvento As String
    Public Property cantidadCredito As Nullable(Of Decimal)
    Public Property cantidadDebito As Nullable(Of Decimal)
    Public Property notaCreditoMN As Nullable(Of Decimal)
    Public Property notaCreditoME As Nullable(Of Decimal)
    Public Property notaDebitoMN As Nullable(Of Decimal)
    Public Property notaDebitoME As Nullable(Of Decimal)
    Public Property percepcionMN As Nullable(Of Decimal)
    Public Property percepcionME As Nullable(Of Decimal)
    Public Property bonificacion As String
    Public Property nrolote As String
    Public Property almacenRef As Nullable(Of Integer)
    Public Property almacenDestino As Nullable(Of Integer)
    Public Property situacion As String
    Public Property idPadreDTCompra As Nullable(Of Integer)
    Public Property entregable As String
    Public Property fechaEntrega As Nullable(Of Date)
    Public Property estadoPago As String
    Public Property usuarioCaja As Nullable(Of Integer)
    Public Property operacionNota As String
    Public Property categoria As Nullable(Of Integer)
    Public Property idCosto As Nullable(Of Integer)
    Public Property tipoCosto As String
    Public Property ItemEntregadototal As String
    Public Property codigoLote As Nullable(Of Integer)
    Public Property tipoRecaudo As String
    Public Property porcRecaudo As Nullable(Of Decimal)
    Public Property valorRecaudo As Nullable(Of Decimal)
    Public Property usuarioModificacion As String
    Public Property fechaModificacion As Nullable(Of Date)
    Public Property idLote As Nullable(Of Integer)
    Public Property idLoteDetalle As Nullable(Of Integer)

    Public Overridable Property documentocompra As documentocompra
    Public Overridable Property inventarioTransito As ICollection(Of inventarioTransito) = New HashSet(Of inventarioTransito)
    Public Overridable Property recursoCosto_compraDetalle As ICollection(Of recursoCosto_compraDetalle) = New HashSet(Of recursoCosto_compraDetalle)

End Class
