'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class documentoventaAbarrotes
    Public Property idDocumento As Integer
    Public Property tipoOperacion As String
    Public Property codigoLibro As String
    Public Property idEmpresa As String
    Public Property idEstablecimiento As Integer
    Public Property tipoDocumento As String
    Public Property fechaLaboral As Nullable(Of Date)
    Public Property fechaDoc As Nullable(Of Date)
    Public Property fechaVcto As Nullable(Of Date)
    Public Property horaVenta As String
    Public Property fechaConfirmacion As Nullable(Of Date)
    Public Property fechaPeriodo As String
    Public Property serie As String
    Public Property numeroDoc As Integer
    Public Property numeroDocNormal As String
    Public Property serieVenta As String
    Public Property numeroVenta As Nullable(Of Integer)
    Public Property idClientePedido As Nullable(Of Integer)
    Public Property nombrePedido As String
    Public Property idCliente As Nullable(Of Integer)
    Public Property moneda As String
    Public Property tipoCambio As Nullable(Of Decimal)
    Public Property tasaIgv As Nullable(Of Decimal)
    Public Property bi01 As Nullable(Of Decimal)
    Public Property bi02 As Nullable(Of Decimal)
    Public Property isc01 As Nullable(Of Decimal)
    Public Property isc02 As Nullable(Of Decimal)
    Public Property igv01 As Nullable(Of Decimal)
    Public Property igv02 As Nullable(Of Decimal)
    Public Property otc01 As Nullable(Of Decimal)
    Public Property otc02 As Nullable(Of Decimal)
    Public Property bi01us As Nullable(Of Decimal)
    Public Property bi02us As Nullable(Of Decimal)
    Public Property isc01us As Nullable(Of Decimal)
    Public Property isc02us As Nullable(Of Decimal)
    Public Property igv01us As Nullable(Of Decimal)
    Public Property igv02us As Nullable(Of Decimal)
    Public Property otc01us As Nullable(Of Decimal)
    Public Property otc02us As Nullable(Of Decimal)
    Public Property ImporteNacional As Nullable(Of Decimal)
    Public Property ImporteExtranjero As Nullable(Of Decimal)
    Public Property importeCostoMN As Nullable(Of Decimal)
    Public Property importeCostoME As Nullable(Of Decimal)
    Public Property estadoCobro As String
    Public Property establecimientoCobro As Nullable(Of Integer)
    Public Property entidadFinanciera As String
    Public Property glosa As String
    Public Property terminos As String
    Public Property notaCredito As String
    Public Property tipoVenta As String
    Public Property modulo As String
    Public Property idPadre As String
    Public Property notificacionAsiento As String
    Public Property estado As String
    Public Property estadoEntrega As String
    Public Property nroImpresion As Nullable(Of Integer)
    Public Property EnvioSunat As String
    Public Property ticketElectronico As String
    Public Property numeracionElectronica As Nullable(Of Long)
    Public Property nroGuia As String
    Public Property nroOrdenVenta As String
    Public Property icbper As Nullable(Of Decimal)
    Public Property icbperus As Nullable(Of Decimal)
    Public Property descripcionVenta As String
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property documento As documento
    Public Overridable Property documentoAnticipoConciliacion As List(Of documentoAnticipoConciliacion) = New HashSet(Of documentoAnticipoConciliacion)().ToList
    Public Overridable Property documentoventaAbarrotesDet As List(Of documentoventaAbarrotesDet) = New HashSet(Of documentoventaAbarrotesDet)().ToList
    Public Overridable Property ventaDetalle_oferta As List(Of ventaDetalle_oferta) = New HashSet(Of ventaDetalle_oferta)().ToList

End Class
