'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class documentoconsumodirecto
    Public Property idDocumento As Integer
    Public Property idProductoPadre As Integer
    Public Property secuencia As Integer
    Public Property almacen As Nullable(Of Integer)
    Public Property idMateriaPrima As Nullable(Of Integer)
    Public Property descripcion As String
    Public Property tipoexistencia As String
    Public Property unidad As String
    Public Property cant As Nullable(Of Decimal)
    Public Property costo As Nullable(Of Decimal)

    Public Overridable Property documentoventaAbarrotesDet As documentoventaAbarrotesDet

End Class
