'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class documentoEntregaDetalle
    Public Property idDocumento As Integer
    Public Property secuencia As Integer
    Public Property idItem As Nullable(Of Integer)
    Public Property destino As String
    Public Property nombreItem As String
    Public Property ImporteMN As Nullable(Of Decimal)
    Public Property ImporteME As Nullable(Of Decimal)
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property documentoEntregaProductos As documentoEntregaProductos

End Class
