'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class documentoAnticipo
    Public Property idDocumento As Integer
    Public Property idEmpresa As String
    Public Property idEstablecimiento As Integer
    Public Property tipoDocumento As String
    Public Property numeroDoc As String
    Public Property fechaDoc As Nullable(Of Date)
    Public Property fechaPeriodo As String
    Public Property tipoOperacion As String
    Public Property tipoAnticipo As String
    Public Property razonSocial As Nullable(Of Integer)
    Public Property TipoCambio As Nullable(Of Decimal)
    Public Property Moneda As String
    Public Property baseImponible As Nullable(Of Decimal)
    Public Property iva As Nullable(Of Decimal)
    Public Property importeMN As Nullable(Of Decimal)
    Public Property importeME As Nullable(Of Decimal)
    Public Property idEntidadFinanciera As Nullable(Of Integer)
    Public Property estado As String
    Public Property movimiento As String
    Public Property tipoMovimiento As String
    Public Property codigoLibro As String
    Public Property codigoProveedor As Nullable(Of Integer)
    Public Property usuarioModificacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property documento As documento
    Public Overridable Property documentoAnticipoDetalle As ICollection(Of documentoAnticipoDetalle) = New HashSet(Of documentoAnticipoDetalle)

End Class
