'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class documentoCaja
    Public Property idDocumento As Integer
    Public Property idEmpresa As String
    Public Property idEstablecimiento As Nullable(Of Integer)
    Public Property codigoLibro As String
    Public Property tipoMovimiento As String
    Public Property codigoProveedor As Nullable(Of Integer)
    Public Property idPersonal As Nullable(Of Integer)
    Public Property tipoPersona As String
    Public Property fechaProceso As Nullable(Of Date)
    Public Property periodo As String
    Public Property fechaCobro As Nullable(Of Date)
    Public Property tipoDocPago As String
    Public Property formapago As String
    Public Property serieDoc As String
    Public Property numeroDoc As String
    Public Property moneda As String
    Public Property entidadFinanciera As String
    Public Property entidadFinancieraDestino As Nullable(Of Integer)
    Public Property tipoOperacion As String
    Public Property numeroOperacion As String
    Public Property tipoCambio As Nullable(Of Decimal)
    Public Property montoSoles As Nullable(Of Decimal)
    Public Property montoUsd As Nullable(Of Decimal)
    Public Property glosa As String
    Public Property entregado As String
    Public Property bancoEntidad As String
    Public Property ctaCorrienteDeposito As String
    Public Property ctaIntebancaria As String
    Public Property movimientoCaja As String
    Public Property idcosto As Nullable(Of Integer)
    Public Property asientoCosto As Nullable(Of Integer)
    Public Property estado As String
    Public Property estadopago As Nullable(Of Integer)
    Public Property idCajaUsuario As Nullable(Of Integer)
    Public Property idCajaUsuarioDestino As Nullable(Of Integer)
    Public Property tipoEntidadFinanciera As String
    Public Property usuarioModificacion As String
    Public Property fechaModificacion As Nullable(Of Date)
    Public Property fechaProcesoDestino As Nullable(Of Date)
    Public Property IdUsuarioTransaccion As Nullable(Of Integer)
    Public Property idRol As Nullable(Of Integer)
    Public Property confirmacionOperacion As String
    Public Property fechaconfirmacionOperacion As Nullable(Of Date)

    Public Overridable Property documento As documento
    Public Overridable Property documentoCajaDetalle As ICollection(Of documentoCajaDetalle) = New HashSet(Of documentoCajaDetalle)
    Public Overridable Property movimientocajaextranjera As ICollection(Of movimientocajaextranjera) = New HashSet(Of movimientocajaextranjera)

End Class
