'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class documentoGuia
    Public Property idDocumento As Integer
    Public Property idDocumentoPadre As Nullable(Of Integer)
    Public Property codigoLibro As String
    Public Property idEmpresa As String
    Public Property idCentroCosto As Integer
    Public Property fechaDoc As Nullable(Of Date)
    Public Property fechaTraslado As Nullable(Of Date)
    Public Property periodo As String
    Public Property tipoDoc As String
    Public Property serie As String
    Public Property numeroDoc As String
    Public Property idEntidad As Nullable(Of Integer)
    Public Property monedaDoc As String
    Public Property tasaIgv As Nullable(Of Decimal)
    Public Property tipoCambio As Nullable(Of Decimal)
    Public Property importeMN As Nullable(Of Decimal)
    Public Property importeME As Nullable(Of Decimal)
    Public Property direccionPartida As String
    Public Property glosa As String
    Public Property idUnidad As Nullable(Of Integer)
    Public Property estado As String
    Public Property ubigeo As String
    Public Property puntoPartida As String
    Public Property puntoLlegada As String
    Public Property tipoMovimiento As String
    Public Property motivoTraslado As String
    Public Property tipoVehiculo As String
    Public Property marcaVehiculo As String
    Public Property placaVehiculo As String
    Public Property placaRemolque As String
    Public Property idEntidadTransporte As Nullable(Of Integer)
    Public Property nroBrevete As String
    Public Property certificado As String
    Public Property estadoGuia As String
    Public Property OtroTipoOperacion As String
    Public Property OtroCantidad As Nullable(Of Integer)
    Public Property DescripcionMotivo As String
    Public Property DAM As String
    Public Property DireccionLlegada As String
    Public Property Trasbordo As Nullable(Of Boolean)
    Public Property AsignarOtraGuia As String
    Public Property RucTrasporte As String
    Public Property datosTrasporte As String
    Public Property fechaEntrega As Nullable(Of Date)
    Public Property nroDocTrasportista As String
    Public Property razonSocialTrasportista As String
    Public Property TipoDocDestinatario As String
    Public Property DocDestinatario As String
    Public Property nombreDestinatario As String
    Public Property TipoDocProveedor As String
    Public Property docProveedor As String
    Public Property DatosProveedor As String
    Public Property ObserTrasPublico As String
    Public Property PesoBruTotal As Nullable(Of Decimal)
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)
    Public Property EnvioSunat As String
    Public Property tipoTransporte As String
    Public Property NroDocumentoConductor As String

    Public Overridable Property documento As documento
    Public Overridable Property documentoguiaDetalle As List(Of documentoguiaDetalle) = New HashSet(Of documentoguiaDetalle)().ToList
    Public Overridable Property documentoGuiaProperties As List(Of documentoGuiaProperties) = New HashSet(Of documentoGuiaProperties)().ToList

End Class
