'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class documento
    Public Property idDocumento As Integer
    Public Property idEmpresa As String
    Public Property idCentroCosto As Integer
    Public Property idProyecto As Nullable(Of Integer)
    Public Property tipoDoc As String
    Public Property fechaProceso As Date
    Public Property moneda As String
    Public Property idEntidad As Integer
    Public Property entidad As String
    Public Property tipoEntidad As String
    Public Property nrodocEntidad As String
    Public Property nroDoc As String
    Public Property idOrden As Nullable(Of Integer)
    Public Property tipoOperacion As String
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property anticipos As anticipos
    Public Overridable Property asiento As ICollection(Of asiento) = New HashSet(Of asiento)
    Public Overridable Property cierreCaja As ICollection(Of cierreCaja) = New HashSet(Of cierreCaja)
    Public Overridable Property cierrecontable As ICollection(Of cierrecontable) = New HashSet(Of cierrecontable)
    Public Overridable Property cierreCostoVenta As ICollection(Of cierreCostoVenta) = New HashSet(Of cierreCostoVenta)
    Public Overridable Property cierreEntregables As ICollection(Of cierreEntregables) = New HashSet(Of cierreEntregables)
    Public Overridable Property cierreinventario As ICollection(Of cierreinventario) = New HashSet(Of cierreinventario)
    Public Overridable Property cierreResultados As ICollection(Of cierreResultados) = New HashSet(Of cierreResultados)
    Public Overridable Property compraexterna_sc As compraexterna_sc
    Public Overridable Property comprasexternas_cc As comprasexternas_cc
    Public Overridable Property Cronograma As ICollection(Of Cronograma) = New HashSet(Of Cronograma)
    Public Overridable Property documentocompra As documentocompra
    Public Overridable Property documentoventa As documentoventa
    Public Overridable Property documentoAnticipo As documentoAnticipo
    Public Overridable Property documentoAportes As documentoAportes
    Public Overridable Property documentoCaja As documentoCaja
    Public Overridable Property documentocompra_sc As documentocompra_sc
    Public Overridable Property documentoEntregaProductos As documentoEntregaProductos
    Public Overridable Property documentoGuia As documentoGuia
    Public Overridable Property documentoLibroDiario As documentoLibroDiario
    Public Overridable Property documentoNotas As documentoNotas
    Public Overridable Property documentoNotasAbarrotes As documentoNotasAbarrotes
    Public Overridable Property documentoObligacionTributaria As documentoObligacionTributaria
    Public Overridable Property documentoOperacionesPrestamo As documentoOperacionesPrestamo
    Public Overridable Property documentoPedido As documentoPedido
    Public Overridable Property documentoPrestamos As ICollection(Of documentoPrestamos) = New HashSet(Of documentoPrestamos)
    Public Overridable Property documentoVenta_sc As documentoVenta_sc
    Public Overridable Property documentoventaAbarrotes As documentoventaAbarrotes
    Public Overridable Property documentoVentaExterna As documentoVentaExterna
    Public Overridable Property documentoVentaExterna_sc As documentoVentaExterna_sc
    Public Overridable Property documentoventaTransporte As documentoventaTransporte
    Public Overridable Property Entidadmembresia_Gym As Entidadmembresia_Gym
    Public Overridable Property inventario As ICollection(Of inventario) = New HashSet(Of inventario)
    Public Overridable Property notificacionAlmacen As notificacionAlmacen
    Public Overridable Property otrasEntradas As otrasEntradas
    Public Overridable Property otrasSalidas As otrasSalidas
    Public Overridable Property registrocomision_usuarios As ICollection(Of registrocomision_usuarios) = New HashSet(Of registrocomision_usuarios)
    Public Overridable Property saldoInicio As saldoInicio

End Class
