'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class documentoventaAbarrotesDet
    Public Property idDocumento As Integer
    Public Property secuencia As Integer
    Public Property idAlmacenOrigen As Nullable(Of Integer)
    Public Property establecimientoOrigen As Nullable(Of Integer)
    Public Property cuentaOrigen As String
    Public Property idItem As String
    Public Property nombreItem As String
    Public Property fechaVcto As Nullable(Of Date)
    Public Property tipoExistencia As String
    Public Property destino As String
    Public Property equivalencia_id As Nullable(Of Integer)
    Public Property catalogo_id As Nullable(Of Integer)
    Public Property unidad2 As String
    Public Property unidad1 As String
    Public Property monto1 As Nullable(Of Decimal)
    Public Property monto2 As String
    Public Property precioUnitario As Nullable(Of Decimal)
    Public Property precioUnitarioUS As Nullable(Of Decimal)
    Public Property importeMN As Nullable(Of Decimal)
    Public Property importeME As Nullable(Of Decimal)
    Public Property importeMNK As Nullable(Of Decimal)
    Public Property importeMEK As Nullable(Of Decimal)
    Public Property descuentoMN As Nullable(Of Decimal)
    Public Property descuentoME As Nullable(Of Decimal)
    Public Property montokardex As Nullable(Of Decimal)
    Public Property montoIsc As Nullable(Of Decimal)
    Public Property montoIgv As Nullable(Of Decimal)
    Public Property otrosTributos As Nullable(Of Decimal)
    Public Property montokardexUS As Nullable(Of Decimal)
    Public Property montoIscUS As Nullable(Of Decimal)
    Public Property montoIgvUS As Nullable(Of Decimal)
    Public Property otrosTributosUS As Nullable(Of Decimal)
    Public Property salidaCostoMN As Nullable(Of Decimal)
    Public Property salidaCostoME As Nullable(Of Decimal)
    Public Property cantidadCredito As Nullable(Of Decimal)
    Public Property cantidadDebito As Nullable(Of Decimal)
    Public Property notaCreditoMN As Nullable(Of Decimal)
    Public Property notaCreditoME As Nullable(Of Decimal)
    Public Property notaDebitoMN As Nullable(Of Decimal)
    Public Property notaDebitoME As Nullable(Of Decimal)
    Public Property preEvento As String
    Public Property idPadreDTVenta As Nullable(Of Integer)
    Public Property estadoMovimiento As String
    Public Property tipoVenta As String
    Public Property entregado As String
    Public Property estadoPago As String
    Public Property categoria As Nullable(Of Integer)
    Public Property estadoEntrega As String
    Public Property idCajaUsuario As Nullable(Of Integer)
    Public Property codigoLote As Nullable(Of Integer)
    Public Property idbeneficio As Nullable(Of Integer)
    Public Property tipobeneficio As String
    Public Property beneficiobase As Nullable(Of Decimal)
    Public Property bonificacion As Nullable(Of Boolean)
    Public Property montoIcbper As Nullable(Of Decimal)
    Public Property montoIcbperUS As Nullable(Of Decimal)
    Public Property tasaIcbper As Nullable(Of Decimal)
    Public Property detalleAdicional As String
    Public Property idDistribucion As Nullable(Of Integer)
    Public Property estadoDistribucion As String
    Public Property idPadre As Nullable(Of Integer)
    Public Property usuarioModificacion As String
    Public Property fechaModificacion As Nullable(Of Date)
    Public Property idLote As Nullable(Of Integer)
    Public Property idLoteDetalle As Nullable(Of Integer)

    Public Overridable Property CronogramaRepartos As ICollection(Of CronogramaRepartos) = New HashSet(Of CronogramaRepartos)
    Public Overridable Property documentoconsumodirecto As ICollection(Of documentoconsumodirecto) = New HashSet(Of documentoconsumodirecto)
    Public Overridable Property documentoventaAbarrotes As documentoventaAbarrotes
    Public Overridable Property ocupacionInfraestructura As ICollection(Of ocupacionInfraestructura) = New HashSet(Of ocupacionInfraestructura)
    Public Overridable Property personaBeneficio As ICollection(Of personaBeneficio) = New HashSet(Of personaBeneficio)

End Class
