'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class documentoObligacionDetalle
    Public Property idDocumento As Integer
    Public Property secuencia As Integer
    Public Property idDocumentoOrigen As Nullable(Of Integer)
    Public Property idItem As Nullable(Of Integer)
    Public Property descripcionItem As String
    Public Property destino As String
    Public Property unidadMedida As String
    Public Property cantidad As Nullable(Of Decimal)
    Public Property precioUnitario As Nullable(Of Decimal)
    Public Property precioUnitarioUS As Nullable(Of Decimal)
    Public Property porcTributo As String
    Public Property importeMN As Nullable(Of Decimal)
    Public Property importeME As Nullable(Of Decimal)
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property documentoObligacionTributaria As documentoObligacionTributaria

End Class
