'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class documentoGuiaProperties
    Public Property idproperty As Integer
    Public Property idDocumento As Integer
    Public Property tipo As String
    Public Property nameproperty As String
    Public Property property_value As String
    Public Property property_value2 As String
    Public Property usuarioModificacion As String
    Public Property fechaModificacion As Nullable(Of Date)

    Public Overridable Property documentoGuia As documentoGuia

End Class
