'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class documentocompra
    Public Property idDocumento As Integer
    Public Property codigoLibro As String
    Public Property idEmpresa As String
    Public Property idCentroCosto As Integer
    Public Property tipoDocInterno As String
    Public Property serieInterno As String
    Public Property numeroInterno As String
    Public Property fechaLaboral As Nullable(Of Date)
    Public Property fechaDoc As Nullable(Of Date)
    Public Property fechaVcto As Nullable(Of Date)
    Public Property fechaConstancia As Nullable(Of Date)
    Public Property fechaContable As String
    Public Property nroConstancia As String
    Public Property periodoTributo As String
    Public Property tipoDoc As String
    Public Property serie As String
    Public Property numeroDoc As String
    Public Property idProveedor As Nullable(Of Integer)
    Public Property idPersona As String
    Public Property monedaDoc As String
    Public Property tasaIgv As Nullable(Of Decimal)
    Public Property tcDolLoc As Nullable(Of Decimal)
    Public Property tipocambio As Nullable(Of Decimal)
    Public Property tipoRecaudo As String
    Public Property regimen As String
    Public Property tasaRegimen As Nullable(Of Decimal)
    Public Property nroRegimen As String
    Public Property bi01 As Nullable(Of Decimal)
    Public Property bi02 As Nullable(Of Decimal)
    Public Property bi03 As Nullable(Of Decimal)
    Public Property bi04 As Nullable(Of Decimal)
    Public Property isc01 As Nullable(Of Decimal)
    Public Property isc02 As Nullable(Of Decimal)
    Public Property isc03 As Nullable(Of Decimal)
    Public Property igv01 As Nullable(Of Decimal)
    Public Property igv02 As Nullable(Of Decimal)
    Public Property igv03 As Nullable(Of Decimal)
    Public Property otc01 As Nullable(Of Decimal)
    Public Property otc02 As Nullable(Of Decimal)
    Public Property otc03 As Nullable(Of Decimal)
    Public Property otc04 As Nullable(Of Decimal)
    Public Property bi01us As Nullable(Of Decimal)
    Public Property bi02us As Nullable(Of Decimal)
    Public Property bi03us As Nullable(Of Decimal)
    Public Property bi04us As Nullable(Of Decimal)
    Public Property isc01us As Nullable(Of Decimal)
    Public Property isc02us As Nullable(Of Decimal)
    Public Property isc03us As Nullable(Of Decimal)
    Public Property igv01us As Nullable(Of Decimal)
    Public Property igv02us As Nullable(Of Decimal)
    Public Property igv03us As Nullable(Of Decimal)
    Public Property otc01us As Nullable(Of Decimal)
    Public Property otc02us As Nullable(Of Decimal)
    Public Property otc03us As Nullable(Of Decimal)
    Public Property otc04us As Nullable(Of Decimal)
    Public Property percepcion As Nullable(Of Decimal)
    Public Property percepcionus As Nullable(Of Decimal)
    Public Property importeTotal As Nullable(Of Decimal)
    Public Property importeUS As Nullable(Of Decimal)
    Public Property destino As String
    Public Property estadoPago As String
    Public Property glosa As String
    Public Property referenciaDestino As String
    Public Property saldoMontoNota As Nullable(Of Decimal)
    Public Property saldoMontoNotaUSD As Nullable(Of Decimal)
    Public Property tipoCompra As String
    Public Property sustentado As String
    Public Property idPadre As Nullable(Of Integer)
    Public Property situacion As String
    Public Property aprobado As String
    Public Property apruebaPago As String
    Public Property tieneDetraccion As String
    Public Property asignacionPorcentaje As Nullable(Of Decimal)
    Public Property detraccionPorcentaje As Nullable(Of Decimal)
    Public Property estadoEntrega As String
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)
    Public Property notaCredito As String
    Public Property estado As String
    Public Property tipoOperacion As String

    Public Overridable Property documento As documento
    Public Overridable Property documentoAnticipoConciliacionCompra As List(Of documentoAnticipoConciliacionCompra) = New HashSet(Of documentoAnticipoConciliacionCompra)().ToList
    Public Overridable Property documentocompradetalle As List(Of documentocompradetalle) = New HashSet(Of documentocompradetalle)().ToList
    Public Overridable Property documentocompra1 As documentocompra
    Public Overridable Property documentocompra2 As documentocompra
    Public Overridable Property entidad As entidad
    Public Overridable Property documentoOtrosDatos As List(Of documentoOtrosDatos) = New HashSet(Of documentoOtrosDatos)().ToList

End Class
