'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class documentoObligacionTributaria
    Public Property idDocumento As Integer
    Public Property idDocumentoOrigen As Nullable(Of Integer)
    Public Property idEmpresa As String
    Public Property idCentroCosto As Integer
    Public Property codigoLibro As String
    Public Property fechaDoc As Nullable(Of Date)
    Public Property periodo As String
    Public Property tipoTributo As String
    Public Property idEntidad As Nullable(Of Integer)
    Public Property tipoOperacion As String
    Public Property idEntidadFinanciera As Nullable(Of Integer)
    Public Property tipoDesposito As String
    Public Property tipoDoc As String
    Public Property serieDoc As String
    Public Property numeroDoc As String
    Public Property moneda As String
    Public Property porcTributario As Nullable(Of Decimal)
    Public Property tipoCambio As Nullable(Of Decimal)
    Public Property importeTotal As Nullable(Of Decimal)
    Public Property importeUS As Nullable(Of Decimal)
    Public Property glosa As String
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property documento As documento
    Public Overridable Property documentoObligacionDetalle As ICollection(Of documentoObligacionDetalle) = New HashSet(Of documentoObligacionDetalle)

End Class
