'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class documentoAnticipoConciliacionCompra
    Public Property secuencia As Integer
    Public Property idDocumento As Integer
    Public Property idDocumentoPadre As Nullable(Of Integer)
    Public Property fechaRegistro As Nullable(Of Date)
    Public Property tipoOperacion As String
    Public Property idItem As Nullable(Of Integer)
    Public Property detalle As String
    Public Property importe As Nullable(Of Decimal)
    Public Property idCajaUsuario As Nullable(Of Integer)
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)
    Public Property idDetalle As Nullable(Of Integer)
    Public Property tipoConciliacion As String
    Public Property tipoDocumento As String
    Public Property numero As Nullable(Of Integer)
    Public Property serie As String

    Public Overridable Property documentocompra As documentocompra

End Class
