'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class documentoguiaDetalleCondicion
    Public Property idCondicion As Integer
    Public Property idDocumento As Integer
    Public Property secuencia As Integer
    Public Property cantConforme As Nullable(Of Integer)
    Public Property cantObservado As Nullable(Of Integer)
    Public Property nombreCondicion As String
    Public Property estadoCondcion As Nullable(Of Integer)
    Public Property descripcionCondicion As String
    Public Property nombreRececpcion As String
    Public Property dniRecepcion As Nullable(Of Integer)
    Public Property estado As String
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property documentoguiaDetalle As documentoguiaDetalle

End Class
