'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EmpresaEmail
    Public Property codigo As Integer
    Public Property idEmpresa As String
    Public Property nombreUsuario As String
    Public Property passUsuario As String
    Public Property email As String
    Public Property tipoCorreo As String
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property empresa As empresa

End Class
