'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class entesRegaludoresTC
    Public Property idRegulador As Integer
    Public Property desripción As String
    Public Property siglas As String
    Public Property usuarioModificacion As String
    Public Property fechaModificacion As Nullable(Of Date)

    Public Overridable Property tipoCambio As ICollection(Of tipoCambio) = New HashSet(Of tipoCambio)

End Class
