'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Entidadmembresia_Gym
    Public Property idMembresia As Integer
    Public Property idDocumento As Integer
    Public Property idEmpresa As String
    Public Property idEstablecimiento As Nullable(Of Integer)
    Public Property tipodoc As String
    Public Property serie As Nullable(Of Integer)
    Public Property serieAlfa As String
    Public Property numero As Nullable(Of Integer)
    Public Property tipoServicio As Nullable(Of Integer)
    Public Property idEntidad As Nullable(Of Integer)
    Public Property tipoEntidad As String
    Public Property fechaRegistro As Nullable(Of Date)
    Public Property periodo As String
    Public Property fechaInicio As Nullable(Of Date)
    Public Property fechaVcto As Nullable(Of Date)
    Public Property restriccion As Nullable(Of Boolean)
    Public Property diashabilesUso As Nullable(Of Integer)
    Public Property contract_mes As Nullable(Of Integer)
    Public Property contract_dia As Nullable(Of Integer)
    Public Property congela_mes As Nullable(Of Integer)
    Public Property congela_dia As Nullable(Of Integer)
    Public Property opGravado As Nullable(Of Decimal)
    Public Property opExonerada As Nullable(Of Decimal)
    Public Property opInafecta As Nullable(Of Decimal)
    Public Property iva As Nullable(Of Decimal)
    Public Property importe As Nullable(Of Decimal)
    Public Property statusMembresia As Nullable(Of Integer)
    Public Property statusPago As Nullable(Of Integer)
    Public Property vendedor As Nullable(Of Integer)
    Public Property comision As Nullable(Of Integer)
    Public Property instructor As Nullable(Of Integer)
    Public Property usuarioActualizacion As Nullable(Of Integer)
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property documento As documento
    Public Overridable Property entidad As entidad
    Public Overridable Property membresia_Gym As membresia_Gym
    Public Overridable Property membresia_congelamiento As ICollection(Of membresia_congelamiento) = New HashSet(Of membresia_congelamiento)

End Class
