'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EntidadAfiliacionBeneficio
    Public Property idEntidad As Integer
    Public Property fechaPedido As Nullable(Of Date)
    Public Property fechaAprobacion As Nullable(Of Date)
    Public Property notas As String
    Public Property status As Nullable(Of Integer)

    Public Overridable Property entidad As entidad

End Class
