'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class entidadBancaria
    Public Property idBanco As Integer
    Public Property codigoBanco As String
    Public Property idEmpresa As String
    Public Property nombreBanco As String
    Public Property cuenta As String
    Public Property tipoAsiento As String
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

End Class
