'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class entidad
    Public Property idEntidad As Integer
    Public Property idEmpresa As String
    Public Property idOrganizacion As Nullable(Of Integer)
    Public Property tipoEntidad As String
    Public Property tipoPersona As String
    Public Property tipoDoc As String
    Public Property nrodoc As String
    Public Property nombre As String
    Public Property appat As String
    Public Property apmat As String
    Public Property nombre1 As String
    Public Property nombre2 As String
    Public Property nombreCompleto As String
    Public Property direccion As String
    Public Property telefono As String
    Public Property celular As String
    Public Property nextel As String
    Public Property email As String
    Public Property estado As String
    Public Property cuentaAsiento As String
    Public Property nombreContacto As String
    Public Property huella As Byte()
    Public Property tieneBeneficio As Nullable(Of Boolean)
    Public Property usuarioModificacion As String
    Public Property fechaModificacion As Nullable(Of Date)

    Public Overridable Property activosFijos As List(Of activosFijos) = New HashSet(Of activosFijos)().ToList
    Public Overridable Property beneficio As List(Of beneficio) = New HashSet(Of beneficio)().ToList
    Public Overridable Property beneficioConsumo As List(Of beneficioConsumo) = New HashSet(Of beneficioConsumo)().ToList
    Public Overridable Property documentocompra As List(Of documentocompra) = New HashSet(Of documentocompra)().ToList
    Public Overridable Property EntidadAfiliacionBeneficio As EntidadAfiliacionBeneficio
    Public Overridable Property entidadAtributos As List(Of entidadAtributos) = New HashSet(Of entidadAtributos)().ToList
    Public Overridable Property Entidadmembresia_Gym As List(Of Entidadmembresia_Gym) = New HashSet(Of Entidadmembresia_Gym)().ToList

End Class
