'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class estadosFinancieros
    Public Property idestado As Integer
    Public Property idEmpresa As String
    Public Property idEstablecimiento As Integer
    Public Property idBanco As String
    Public Property cuenta As String
    Public Property codigo As String
    Public Property tipo As String
    Public Property descripcion As String
    Public Property nroCtaCorriente As String
    Public Property tipocambio As Nullable(Of Decimal)
    Public Property fechaBalance As Nullable(Of Date)
    Public Property importeBalanceMN As Nullable(Of Decimal)
    Public Property importeBalanceME As Nullable(Of Decimal)
    Public Property predeterminado As String
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)
    Public Property nroCtaInterbancaria As String
    Public Property modalidadCuenta As String

End Class
