'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class hojaPlaneamiento
    Public Property idEmpresa As String
    Public Property idEstablecimiento As Integer
    Public Property idProyecto As Integer
    Public Property idEvento As Integer
    Public Property secuencia As Integer
    Public Property proceso As String
    Public Property detalle As String
    Public Property unidad As String
    Public Property cantidad As Nullable(Of Decimal)
    Public Property ejecDiariaPersona As Nullable(Of Integer)
    Public Property inicioEjec As Nullable(Of Date)
    Public Property finEjec As Nullable(Of Date)
    Public Property estado As String
    Public Property orden As Nullable(Of Integer)
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

End Class
