'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ingresoSunat
    Public Property idIngresoSunat As Integer
    Public Property codigoSunat As String
    Public Property descripcion As String
    Public Property cuentaContable As String
    Public Property idPadre As Nullable(Of Integer)
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property ingresoSunat1 As ingresoSunat
    Public Overridable Property ingresoSunat2 As ingresoSunat

End Class
