'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class InventarioDetalleSalida
    Public Property idInventario As Long
    Public Property idSecuencia As Short
    Public Property idInventarioRef As Long
    Public Property cantidad As Nullable(Of Decimal)
    Public Property cantidad2 As Nullable(Of Decimal)
    Public Property monto As Nullable(Of Decimal)
    Public Property montoUSD As Nullable(Of Decimal)
    Public Property montoOther As Nullable(Of Decimal)

End Class
