'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class InventarioTotal
    Public Property idEmpresa As String
    Public Property idAlmacen As String
    Public Property tipoProducto As String
    Public Property idItem As String
    Public Property cantidad As Nullable(Of Decimal)
    Public Property unidad As String
    Public Property monto As Nullable(Of Decimal)
    Public Property precioUnitario As Nullable(Of Decimal)
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

End Class
