'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class jerarquia
    Public Property idCentroCosto As Integer
    Public Property nivel As Integer
    Public Property descripcion As String

    Public Overridable Property centrocosto As centrocosto

End Class
