'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LiquidacionPlaneacion
    Public Property IdLiquidacion As Integer
    Public Property idProyecto As Nullable(Of Integer)
    Public Property idTarea As Nullable(Of Integer)
    Public Property Tipo As String
    Public Property NombreTarea As String
    Public Property AjustesCf As Nullable(Of Decimal)
    Public Property IgvPorPagar As Nullable(Of Decimal)
    Public Property AjustesCf1 As Nullable(Of Decimal)
    Public Property AjustesCf2 As Nullable(Of Decimal)
    Public Property IgvPorPagar1 As Nullable(Of Decimal)
    Public Property IgvPorPagar2 As Nullable(Of Decimal)
    Public Property ImpuestoAlaRenta As Nullable(Of Decimal)
    Public Property ImpuestoAlaRenta1 As Nullable(Of Decimal)
    Public Property ImpuestoAlaRenta2 As Nullable(Of Decimal)
    Public Property ResulEjer As Nullable(Of Decimal)
    Public Property ResulEjer1 As Nullable(Of Decimal)
    Public Property ResulEjer2 As Nullable(Of Decimal)
    Public Property RetDeducAportTri As Nullable(Of Decimal)
    Public Property RetDeducAportTri1 As Nullable(Of Decimal)
    Public Property RetDeducAportTri2 As Nullable(Of Decimal)
    Public Property AjustCostoVenta As Nullable(Of Decimal)
    Public Property AjustCostoVenta1 As Nullable(Of Decimal)
    Public Property AjustCostoVenta2 As Nullable(Of Decimal)
    Public Property AjustCostoVentaMax As Nullable(Of Decimal)
    Public Property AjustCostoVentaMax1 As Nullable(Of Decimal)
    Public Property AjustCostoVentaMax2 As Nullable(Of Decimal)
    Public Property AjustCostoVentaMin As Nullable(Of Decimal)
    Public Property AjustCostoVentaMin1 As Nullable(Of Decimal)
    Public Property AjustCostoVentaMin2 As Nullable(Of Decimal)
    Public Property DscBon As Nullable(Of Decimal)
    Public Property DscBon1 As Nullable(Of Decimal)
    Public Property DscBon2 As Nullable(Of Decimal)
    Public Property IngreFin As Nullable(Of Decimal)
    Public Property IngreFin1 As Nullable(Of Decimal)
    Public Property IngreFin2 As Nullable(Of Decimal)
    Public Property OtroIngre As Nullable(Of Decimal)
    Public Property OtroIngre1 As Nullable(Of Decimal)
    Public Property OtroIngre2 As Nullable(Of Decimal)
    Public Property DistriLegal As Nullable(Of Decimal)
    Public Property DistriLegal1 As Nullable(Of Decimal)
    Public Property DistriLegal2 As Nullable(Of Decimal)
    Public Property RetenUtilidades As Nullable(Of Decimal)
    Public Property RetenUtilidades1 As Nullable(Of Decimal)
    Public Property RetenUtilidades2 As Nullable(Of Decimal)
    Public Property OtrosPagos As Nullable(Of Decimal)
    Public Property OtrosPagos1 As Nullable(Of Decimal)
    Public Property OtrosPagos2 As Nullable(Of Decimal)
    Public Property OtroGasto As Nullable(Of Decimal)
    Public Property OtroGasto1 As Nullable(Of Decimal)
    Public Property OtroGasto2 As Nullable(Of Decimal)
    Public Property Destraccion As Nullable(Of Decimal)
    Public Property Destraccion1 As Nullable(Of Decimal)
    Public Property Destraccion2 As Nullable(Of Decimal)
    Public Property OtroPagoA As Nullable(Of Decimal)
    Public Property OtroPagoA1 As Nullable(Of Decimal)
    Public Property OtroPagoA2 As Nullable(Of Decimal)
    Public Property AjustCrediFis As Nullable(Of Decimal)
    Public Property AjustCrediFis1 As Nullable(Of Decimal)
    Public Property AjustCrediFis2 As Nullable(Of Decimal)
    Public Property AjusteCfMin As Nullable(Of Decimal)
    Public Property AjusteCfMin1 As Nullable(Of Decimal)
    Public Property AjusteCfMin2 As Nullable(Of Decimal)

End Class
