'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class listadoPrecios
    Public Property autoCodigo As Long
    Public Property idEmpresa As String
    Public Property idEstablecimiento As Nullable(Of Integer)
    Public Property tipoExistencia As String
    Public Property destinoGravado As String
    Public Property idItem As Nullable(Of Integer)
    Public Property descripcion As String
    Public Property presentacion As String
    Public Property unidad As String
    Public Property fecha As Nullable(Of Date)
    Public Property vcmenor As Nullable(Of Decimal)
    Public Property vcmayor As Nullable(Of Decimal)
    Public Property vcgranmayor As Nullable(Of Decimal)
    Public Property vcmenorme As Nullable(Of Decimal)
    Public Property vcmayorme As Nullable(Of Decimal)
    Public Property vcgranmayorme As Nullable(Of Decimal)
    Public Property porcUtimenor As Nullable(Of Decimal)
    Public Property porcUtimayor As Nullable(Of Decimal)
    Public Property porcUtigranmayor As Nullable(Of Decimal)
    Public Property montoUtimenor As Nullable(Of Decimal)
    Public Property montoUtimayor As Nullable(Of Decimal)
    Public Property montoUtigranmayor As Nullable(Of Decimal)
    Public Property vvmenor As Nullable(Of Decimal)
    Public Property vvmayor As Nullable(Of Decimal)
    Public Property vvgranmayor As Nullable(Of Decimal)
    Public Property igvmenor As Nullable(Of Decimal)
    Public Property igvmayor As Nullable(Of Decimal)
    Public Property igvgranmayor As Nullable(Of Decimal)
    Public Property pvmenor As Nullable(Of Decimal)
    Public Property pvmayor As Nullable(Of Decimal)
    Public Property pvgranmayor As Nullable(Of Decimal)
    Public Property porcUtimenorme As Nullable(Of Decimal)
    Public Property porcUtimayorme As Nullable(Of Decimal)
    Public Property porcUtigranmayorme As Nullable(Of Decimal)
    Public Property montoUtimenorme As Nullable(Of Decimal)
    Public Property montoUtimayorme As Nullable(Of Decimal)
    Public Property montoUtigranmayorme As Nullable(Of Decimal)
    Public Property vvmenorme As Nullable(Of Decimal)
    Public Property vvmayorme As Nullable(Of Decimal)
    Public Property vvgranmayorme As Nullable(Of Decimal)
    Public Property igvmenormeme As Nullable(Of Decimal)
    Public Property igvmayormeme As Nullable(Of Decimal)
    Public Property igvgranmayorme As Nullable(Of Decimal)
    Public Property pvmenorme As Nullable(Of Decimal)
    Public Property pvmayorme As Nullable(Of Decimal)
    Public Property pvgranmayorme As Nullable(Of Decimal)
    Public Property valcompraIgvMN As Nullable(Of Decimal)
    Public Property valcompraSinIgvMN As Nullable(Of Decimal)
    Public Property valcompraIgvME As Nullable(Of Decimal)
    Public Property valcompraSinIgvME As Nullable(Of Decimal)
    Public Property tipoConfiguracion As String
    Public Property montoUtilidad As Nullable(Of Decimal)
    Public Property montoUtilidadME As Nullable(Of Decimal)
    Public Property utilidadsinIgvMN As Nullable(Of Decimal)
    Public Property valorVentaMN As Nullable(Of Decimal)
    Public Property igvMN As Nullable(Of Decimal)
    Public Property iscMN As Nullable(Of Decimal)
    Public Property otcMN As Nullable(Of Decimal)
    Public Property precioVentaMN As Nullable(Of Decimal)
    Public Property utilidadsinIgvME As Nullable(Of Decimal)
    Public Property valorVentaME As Nullable(Of Decimal)
    Public Property igvME As Nullable(Of Decimal)
    Public Property iscME As Nullable(Of Decimal)
    Public Property otcME As Nullable(Of Decimal)
    Public Property precioVentaME As Nullable(Of Decimal)
    Public Property PorDsctounitMenor As Nullable(Of Decimal)
    Public Property montoDsctounitMenorMN As Nullable(Of Decimal)
    Public Property montoDsctounitMenorME As Nullable(Of Decimal)
    Public Property precioVentaFinalMenorMN As Nullable(Of Decimal)
    Public Property precioVentaFinalMenorME As Nullable(Of Decimal)
    Public Property PorDsctounitMayor As Nullable(Of Decimal)
    Public Property montoDsctounitMayorMN As Nullable(Of Decimal)
    Public Property montoDsctounitMayorME As Nullable(Of Decimal)
    Public Property precioVentaFinalMayorMN As Nullable(Of Decimal)
    Public Property precioVentaFinalMayorME As Nullable(Of Decimal)
    Public Property PorDsctounitGMayor As Nullable(Of Decimal)
    Public Property montoDsctounitGMayorMN As Nullable(Of Decimal)
    Public Property montoDsctounitGMayorME As Nullable(Of Decimal)
    Public Property precioVentaFinalGMayorMN As Nullable(Of Decimal)
    Public Property precioVentaFinalGMayorME As Nullable(Of Decimal)
    Public Property detalleMenor As String
    Public Property cantidadMenor As Nullable(Of Decimal)
    Public Property detalleMayor As String
    Public Property cantidadMayor As Nullable(Of Decimal)
    Public Property detalleGMayor As String
    Public Property cantidadGMayor As Nullable(Of Decimal)
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

End Class
