'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LoteDetalle
    Public Property idDetalleLote As Integer
    Public Property codigoLote As Integer
    Public Property estado As String
    Public Property campo As String
    Public Property descripcion As String
    Public Property numeracion As Nullable(Of Integer)

    Public Overridable Property recursoCostoLote As recursoCostoLote

End Class
