'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class mascaraGeneralExistencia
    Public Property IDMascara As Integer
    Public Property tipoExistencia As String
    Public Property cuentaCompra As String
    Public Property descripcionCompra As String
    Public Property asientoCompra As String
    Public Property destinoCompra As String
    Public Property descripcionDestino As String
    Public Property asientoDestino As String
    Public Property destinoCompra2 As String
    Public Property descripcionDestino2 As String
    Public Property asientoDestino2 As String
    Public Property cuentaIngAlmacen As String
    Public Property nameIngAlmacen As String
    Public Property asientoIngAlmacen As String
    Public Property cuentaIngAlmacen2 As String
    Public Property nameIngAlmacen2 As String
    Public Property asientoIngAlmacen2 As String
    Public Property cuentaSalida As String
    Public Property descripcionSalida As String
    Public Property asientoSalida As String
    Public Property cuentaSalida2 As String
    Public Property descripcionSalida2 As String
    Public Property asientoSalida2 As String
    Public Property cuentaDestinocosto As String
    Public Property descripcionDestinocosto As String
    Public Property asientoDestinocosto As String
    Public Property cuentaDestinocosto2 As String
    Public Property descripcionDestinocosto2 As String
    Public Property asientoDestinocosto2 As String
    Public Property cuentaFinCosto As String
    Public Property nameFinCosto As String
    Public Property asientoFinCosto As String
    Public Property cuentaFinCosto2 As String
    Public Property nameFinCosto2 As String
    Public Property asientoFinCosto2 As String
    Public Property cuentaProduccion As String
    Public Property nameProduccion As String
    Public Property asientoProduccion As String
    Public Property cuentaProduccion2 As String
    Public Property nameProduccion2 As String
    Public Property asientoProduccion2 As String

End Class
