'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class mascaraGastosEmpresa
    Public Property idEmpresa As String
    Public Property cuentaCompra As String
    Public Property descripcionCompra As String
    Public Property cuentaCostoProcesoDebe As String
    Public Property descripcionCostoProcesoDebe As String
    Public Property cuentaCostoProcesoHaber As String
    Public Property descripcionCostoProcesoHaber As String
    Public Property cuentaConclusionProcesoDebe As String
    Public Property descripcionConclusionDebe As String
    Public Property cuentaConclusionProcesoHaber As String
    Public Property descripcionConclusionHaber As String
    Public Property cuentaDestinoDebe As String
    Public Property descripcionDestinoDebe As String
    Public Property cuentaDestinoHaber As String
    Public Property descripcionDestinoHaber As String
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

End Class
