'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class mascaraProdTerminado
    Public Property idProd As Integer
    Public Property tipoExistencia As String
    Public Property cuentaIngAlmacen As String
    Public Property nameIngAlmacen As String
    Public Property cuentaIngAlmacen2 As String
    Public Property nameIngAlmacen2 As String
    Public Property cuentaVenta As String
    Public Property nameVenta As String
    Public Property cuentaVentapt As String
    Public Property nameVentapt As String
    Public Property cuentaVentapt2 As String
    Public Property nameVentapt2 As String

End Class
