'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class mensajeriaGOP
    Public Property seuencia As Integer
    Public Property idActividad As Integer
    Public Property fechaMensaje As Nullable(Of Date)
    Public Property horaMensaje As String
    Public Property comentario As String
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property Actividades As Actividades

End Class
