'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class moduloConfiguracion
    Public Property idConfiguracion As Integer
    Public Property idEmpresa As String
    Public Property idEstablecimiento As Nullable(Of Integer)
    Public Property idModulo As String
    Public Property tipoConfiguracion As String
    Public Property tipoDoc As String
    Public Property descripcionModulo As String
    Public Property configComprobante As Nullable(Of Integer)
    Public Property configAlmacen As Nullable(Of Integer)
    Public Property ConfigentidadFinanciera As Nullable(Of Integer)

End Class
