'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class moduloApp
    Public Property idModulo As String
    Public Property tipo As String
    Public Property descripcionModulo As String
    Public Property IdPadre As String
    Public Property estado As String

End Class
