'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class negocioComercial
    Public Property IdNegocioComercial As Integer
    Public Property nombreRubro As String
    Public Property tipo As String
    Public Property estado As String
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property centroCostosXNComercial As ICollection(Of centroCostosXNComercial) = New HashSet(Of centroCostosXNComercial)
    Public Overridable Property negocioComercialDetalle As ICollection(Of negocioComercialDetalle) = New HashSet(Of negocioComercialDetalle)

End Class
