'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class oferta
    Public Property id As Integer
    Public Property idemprea As String
    Public Property idEstablecimiento As Nullable(Of Integer)
    Public Property codigo As String
    Public Property tipo As String
    Public Property fechaEmision As Nullable(Of Date)
    Public Property Vence As Nullable(Of Date)
    Public Property estado As String
    Public Property nombreCorto As String
    Public Property descripcion As String
    Public Property precioventa As Nullable(Of Decimal)
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property ofertadetalle As ICollection(Of ofertadetalle) = New HashSet(Of ofertadetalle)
    Public Overridable Property ventaDetalle_oferta As ICollection(Of ventaDetalle_oferta) = New HashSet(Of ventaDetalle_oferta)

End Class
