'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ofertadetalle
    Public Property id As Integer
    Public Property id_oferta As Integer
    Public Property idalmacen As Nullable(Of Integer)
    Public Property iditem As Nullable(Of Integer)
    Public Property lote As Nullable(Of Integer)
    Public Property detalle As String
    Public Property cantidad As Nullable(Of Decimal)
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property oferta As oferta

End Class
