'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class perfilAnexo
    Public Property idCargo As Integer
    Public Property idCentroCosto As Nullable(Of Integer)
    Public Property descripcion As String
    Public Property tipo As Integer
    Public Property estado As String
    Public Property idRol As String
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property centrocosto As centrocosto
    Public Overridable Property distribucionNumeracionAO As ICollection(Of distribucionNumeracionAO) = New HashSet(Of distribucionNumeracionAO)

End Class
