'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Persona
    Public Property codigo As Integer
    Public Property idEmpresa As String
    Public Property idPersona As String
    Public Property idOrganizacion As Nullable(Of Integer)
    Public Property idEntidad As Nullable(Of Integer)
    Public Property fechaNac As Nullable(Of Date)
    Public Property tipoPersona As String
    Public Property tipodoc As String
    Public Property appat As String
    Public Property apmat As String
    Public Property nombres As String
    Public Property nombreCompleto As String
    Public Property nivel As String
    Public Property edad As Nullable(Of Integer)
    Public Property email As String
    Public Property telefono As String
    Public Property localidad As String
    Public Property distrito As String
    Public Property cuentaContable As String
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

End Class
