'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PL_LiquidacionIgv
    Public Property secuencia As Integer
    Public Property idEmpresa As String
    Public Property idEstablecimiento As Integer
    Public Property idProyecto As Integer
    Public Property idEstrategia As Integer
    Public Property Fecha As Nullable(Of Date)
    Public Property LI_ib_ini As Nullable(Of Decimal)
    Public Property LI_cfAcum_ini As Nullable(Of Decimal)
    Public Property LI_ib_ns As Nullable(Of Decimal)
    Public Property LI_cfAcum_ns As Nullable(Of Decimal)
    Public Property LI_ib_adic As Nullable(Of Decimal)
    Public Property LI_afAcum_adic As Nullable(Of Decimal)
    Public Property LI_AjCfps_ini As Nullable(Of Decimal)
    Public Property LI_AjCfps_ns As Nullable(Of Decimal)
    Public Property LI_AjCfps_adic As Nullable(Of Decimal)
    Public Property LI_AjCfng_ini As Nullable(Of Decimal)
    Public Property LI_AjCfng_ns As Nullable(Of Decimal)
    Public Property LI_AjCfng_adic As Nullable(Of Decimal)

End Class
