'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class presupuesto
    Public Property empresa As String
    Public Property periodo As String
    Public Property cuenta As String
    Public Property tipo As String
    Public Property anio As String
    Public Property mes As String
    Public Property moneda As String
    Public Property monto As Nullable(Of Decimal)
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property empresa1 As empresa

End Class
