'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class prestamos
    Public Property codigo As Integer
    Public Property idDocumento As Nullable(Of Integer)
    Public Property idEmpresa As String
    Public Property idEstablecimiento As Integer
    Public Property tipoPrestamo As String
    Public Property DocPrestamo As String
    Public Property nroDoc As String
    Public Property periodo As String
    Public Property fechaPrestamo As Nullable(Of Date)
    Public Property fechaDesembolso As Nullable(Of Date)
    Public Property tipoBeneficiario As String
    Public Property idBeneficiario As Integer
    Public Property detalleGlosa As String
    Public Property moneda As String
    Public Property tipoCambio As Nullable(Of Decimal)
    Public Property interes As Nullable(Of Decimal)
    Public Property seguro As Nullable(Of Decimal)
    Public Property monto As Nullable(Of Decimal)
    Public Property montoUSD As Nullable(Of Decimal)
    Public Property tipoActivo As String
    Public Property entregaPendiente As String
    Public Property estado As String
    Public Property numCuotas As Nullable(Of Decimal)
    Public Property modoPago As String
    Public Property diaPago As Nullable(Of Integer)
    Public Property fechaInicio As Nullable(Of Date)
    Public Property plazoDias As Nullable(Of Integer)
    Public Property desembolso As String
    Public Property tipo As String
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)
    Public Property cuentaTipo As String
    Public Property cuentaDevengado As String
    Public Property tipoCuenta As String
    Public Property tipoDevengado As String
    Public Property interesUSD As Nullable(Of Decimal)

End Class
