'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class productoBeneficio
    Public Property id As Integer
    Public Property idalmacen As Nullable(Of Integer)
    Public Property iditem As Nullable(Of Integer)
    Public Property beneficio As String
    Public Property tipoasignacion As String
    Public Property valorInicio As Nullable(Of Decimal)
    Public Property valorFin As Nullable(Of Decimal)
    Public Property resultado As Nullable(Of Decimal)
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

End Class
