'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ProductoXAreaOperativa
    Public Property idRelacion As Integer
    Public Property idArea As Nullable(Of Integer)
    Public Property codigodetalle As Nullable(Of Integer)
    Public Property idEmpresa As String
    Public Property idCentroCosto As Nullable(Of Integer)
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property areaOperativa As areaOperativa
    Public Overridable Property detalleitems As detalleitems

End Class
