'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class proyectoDetalleInfo
    Public Property secuencia As Integer
    Public Property idProyecto As Integer
    Public Property idItem As String
    Public Property Item As String
    Public Property unidad As String
    Public Property cantidad As Nullable(Of Decimal)
    Public Property precUnitario As Nullable(Of Decimal)
    Public Property importe As Nullable(Of Decimal)
    Public Property importeME As Nullable(Of Decimal)
    Public Property fechaEntrega As Nullable(Of Date)
    Public Property observacionOtros As String
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

End Class
