'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class proyectoListaMateriales
    Public Property idProyecto As Integer
    Public Property idEvento As Integer
    Public Property idItem As Integer
    Public Property codigo As String
    Public Property descripcion As String
    Public Property clasificacion As Nullable(Of Integer)
    Public Property capacidad As String
    Public Property presion As String
    Public Property electricidad As String
    Public Property transmision As String
    Public Property rpm As String
    Public Property marcaRef As String
    Public Property nivelRuido As String
    Public Property Peso As String
    Public Property Filtros As String
    Public Property presentacion As String
    Public Property unidad1 As String
    Public Property tipoExistencia As String
    Public Property origenProducto As String

End Class
