'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ProyectoPlaneacion
    Public Property idProyecto As Integer
    Public Property idEmpresa As String
    Public Property idEstablecimiento As Integer
    Public Property nombreProyecto As String
    Public Property fechaEmision As Nullable(Of Date)
    Public Property objetivo As String
    Public Property fechaInicio As Nullable(Of Date)
    Public Property fechaFinal As Nullable(Of Date)
    Public Property responsable As String
    Public Property fechaEstadoCobro As Nullable(Of Date)
    Public Property estadoCosto As String
    Public Property anotacionEstado As String
    Public Property refDocAprobacion As String
    Public Property FechaInicioAprob As Nullable(Of Date)
    Public Property FechaFinAprob As Nullable(Of Date)
    Public Property modalidadServicio As String
    Public Property nroContrato As String
    Public Property ot As String
    Public Property pte As String
    Public Property usuarioModificacion As String
    Public Property fechaModificacion As Nullable(Of Date)

    Public Overridable Property Actividades As ICollection(Of Actividades) = New HashSet(Of Actividades)

End Class
