'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class recursoCostoDetalle
    Public Property secuencia As Integer
    Public Property idCosto As Integer
    Public Property fechaRegistro As Nullable(Of Date)
    Public Property iditem As Nullable(Of Integer)
    Public Property destino As String
    Public Property descripcion As String
    Public Property um As String
    Public Property cant As Nullable(Of Decimal)
    Public Property puMN As Nullable(Of Decimal)
    Public Property puME As Nullable(Of Decimal)
    Public Property montoMN As Nullable(Of Decimal)
    Public Property montoME As Nullable(Of Decimal)
    Public Property documentoRef As Nullable(Of Integer)
    Public Property itemRef As Nullable(Of Integer)
    Public Property operacion As String
    Public Property procesado As String
    Public Property tipoCosto As String
    Public Property idProceso As Nullable(Of Integer)
    Public Property fechaTrabajo As Nullable(Of Date)
    Public Property Periodo As String
    Public Property idDocSalida As Nullable(Of Integer)
    Public Property idRecursoAfectado As Nullable(Of Integer)
    Public Property motivoCosto As String
    Public Property elementoCosto As String

    Public Overridable Property recursoCosto As recursoCosto
    Public Overridable Property recursoCosto_compraDetalle As ICollection(Of recursoCosto_compraDetalle) = New HashSet(Of recursoCosto_compraDetalle)

End Class
