'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class recursoCostoLote
    Public Property codigoLote As Integer
    Public Property nroLote As String
    Public Property idDocumento As Nullable(Of Integer)
    Public Property idproyecto As Nullable(Of Integer)
    Public Property codigoProducto As Nullable(Of Integer)
    Public Property moneda As String
    Public Property detalle As String
    Public Property cantidad As Nullable(Of Decimal)
    Public Property precioUnitarioIva As Nullable(Of Decimal)
    Public Property precioUnitarioIvaME As Nullable(Of Decimal)
    Public Property fechaentrada As Nullable(Of Date)
    Public Property fechaProduccion As Nullable(Of Date)
    Public Property fechaVcto As Nullable(Of Date)
    Public Property serie As String
    Public Property sku As String
    Public Property composicion As String
    Public Property productoSustentado As Nullable(Of Boolean)
    Public Property verificado As Nullable(Of Boolean)
    Public Property idCaracteristica As Nullable(Of Integer)

    Public Overridable Property detalleitems As detalleitems
    Public Overridable Property LoteDetalle As List(Of LoteDetalle) = New HashSet(Of LoteDetalle)().ToList
    Public Overridable Property recursoCostoLoteTalla As List(Of recursoCostoLoteTalla) = New HashSet(Of recursoCostoLoteTalla)().ToList

End Class
