'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class recursoCosto_compraDetalle
    Public Property secuencia As Integer
    Public Property idCosto As Integer
    Public Property idDocumento As Integer
    Public Property secuenciacosto As Integer
    Public Property secuenciaCompra As Integer
    Public Property cantidad As Nullable(Of Decimal)

    Public Overridable Property documentocompradetalle As documentocompradetalle
    Public Overridable Property recursoCostoDetalle As recursoCostoDetalle

End Class
