'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class registrocomision_usuarios_detalle
    Public Property idseguimiento As Integer
    Public Property idseguimientoDetalle As Integer
    Public Property idDocumentoRef As Integer
    Public Property IdUsuario As Nullable(Of Integer)
    Public Property tipoComision As String
    Public Property valorComision As Nullable(Of Decimal)
    Public Property idProducto As Nullable(Of Integer)
    Public Property unidadComercial As Nullable(Of Integer)
    Public Property unidadprincipal As String
    Public Property catalogo As Nullable(Of Integer)
    Public Property precioTotalVenta As Nullable(Of Decimal)
    Public Property precioComision As Nullable(Of Decimal)
    Public Property estadoVenta As String
    Public Property estadoComision As String

    Public Overridable Property registrocomision_autorizacion As ICollection(Of registrocomision_autorizacion) = New HashSet(Of registrocomision_autorizacion)
    Public Overridable Property registrocomision_usuarios As registrocomision_usuarios

End Class
