'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class registrocomision_usuarios
    Public Property idseguimiento As Integer
    Public Property idDocumentoRef As Integer
    Public Property idEmpresa As String
    Public Property unidadNegocio As Integer
    Public Property fechaRegistro As Nullable(Of Date)
    Public Property moneda As String
    Public Property importeTotalVenta As Nullable(Of Decimal)
    Public Property importeTotalGanadoMN As Nullable(Of Decimal)
    Public Property importeTotalGanadoME As Nullable(Of Decimal)
    Public Property estadoVenta As String
    Public Property estadoComision As String
    Public Property fechaVence As Nullable(Of Date)
    Public Property fechaprogramadaPago As Nullable(Of Date)
    Public Property otrosConceptos As Nullable(Of Decimal)

    Public Overridable Property documento As documento
    Public Overridable Property registrocomision_usuarios_detalle As ICollection(Of registrocomision_usuarios_detalle) = New HashSet(Of registrocomision_usuarios_detalle)

End Class
