'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class registroautorizacion_desembolso
    Public Property idDesembolso As Integer
    Public Property idAutorizacion As Integer
    Public Property idseguimiento As Integer
    Public Property idseguimientoDetalle As Integer
    Public Property idDocumentoRef As Integer
    Public Property IdDocumentoPago As Nullable(Of Integer)
    Public Property fechaRegistroPago As Nullable(Of Date)

    Public Overridable Property registrocomision_autorizacion As registrocomision_autorizacion

End Class
