'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class rutaTareoTripulantes
    Public Property tareo_id As Integer
    Public Property idVehiculo As Integer
    Public Property ruta_id As Integer
    Public Property horario_id As Integer
    Public Property programacion_id As Integer
    Public Property tripulante_id As Integer
    Public Property idPersona As Nullable(Of Integer)
    Public Property nombreCompleto As String
    Public Property numdoc As String
    Public Property nroLicencia As String
    Public Property usuarioActualizacion As Nullable(Of Integer)
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property rutaTareoAutos As rutaTareoAutos

End Class
