'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class rutaTareoAutos
    Public Property tareo_id As Integer
    Public Property idVehiculo As Integer
    Public Property ruta_id As Integer
    Public Property horario_id As Integer
    Public Property programacion_id As Integer
    Public Property fecha As Nullable(Of Date)
    Public Property nroPlaca As String
    Public Property tipoTareo As Nullable(Of Integer)
    Public Property fechaOperacion As Nullable(Of Date)
    Public Property nroPasajeros As Nullable(Of Integer)
    Public Property nroTripulantes As Nullable(Of Integer)
    Public Property estado As Nullable(Of Integer)
    Public Property usuarioActualizacion As Nullable(Of Integer)
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property rutaTareoDetalle As ICollection(Of rutaTareoDetalle) = New HashSet(Of rutaTareoDetalle)
    Public Overridable Property rutaTareoTripulantes As ICollection(Of rutaTareoTripulantes) = New HashSet(Of rutaTareoTripulantes)

End Class
