'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ruta_horarios
    Public Property ruta_id As Integer
    Public Property horario_id As Integer
    Public Property dias As String
    Public Property horaPartida As Nullable(Of Date)
    Public Property horaPartidaTolerancia As Nullable(Of Integer)
    Public Property horaLlegada As Nullable(Of Date)
    Public Property horaLlegadaTolerancia As Nullable(Of Integer)
    Public Property usuarioActualizacion As Nullable(Of Integer)
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property rutas As rutas
    Public Overridable Property ruta_HorarioServicios As ICollection(Of ruta_HorarioServicios) = New HashSet(Of ruta_HorarioServicios)

End Class
