'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class rutas
    Public Property ruta_id As Integer
    Public Property codigo As String
    Public Property km As Nullable(Of Decimal)
    Public Property ciudadOrigen As String
    Public Property ciudadOrigenUbigeo As String
    Public Property ciudadOrigenDomicilio As String
    Public Property ciudadDestino As String
    Public Property ciudadDestinoUbigeo As String
    Public Property ciudadDestinoDomicilio As String
    Public Property idpadre As Nullable(Of Integer)
    Public Property estado As Nullable(Of Integer)
    Public Property usuarioActualizacion As Nullable(Of Integer)
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property ruta_horarios As ICollection(Of ruta_horarios) = New HashSet(Of ruta_horarios)

End Class
