'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class rutaTareoEncomiendaDetalle
    Public Property tareo_id As Integer
    Public Property secuencia As Integer
    Public Property venta_id As Nullable(Of Integer)
    Public Property venta_detalle_id As Nullable(Of Integer)
    Public Property remitente As String
    Public Property consignado As String
    Public Property tipo As String
    Public Property cantidad As Nullable(Of Decimal)
    Public Property contenido As String
    Public Property costo As Nullable(Of Decimal)
    Public Property estado As Nullable(Of Integer)
    Public Property usuarioActualizacion As Nullable(Of Integer)
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property rutaTareoEncomienda As rutaTareoEncomienda

End Class
