'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class rutaProgramacionSalidas
    Public Property programacion_id As Integer
    Public Property ruta_id As Nullable(Of Integer)
    Public Property tipo As String
    Public Property fechaProgramacion As Nullable(Of Date)
    Public Property estado As Nullable(Of Integer)
    Public Property idActivo As Nullable(Of Integer)
    Public Property manifiesto As String
    Public Property usuarioActualizacion As Nullable(Of Integer)
    Public Property fechaActualizacion As Nullable(Of Date)

End Class
