'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class rutaTareoEncomienda
    Public Property tareo_id As Integer
    Public Property agenciaOrigen_id As Nullable(Of Integer)
    Public Property agenciaDestino_id As Nullable(Of Integer)
    Public Property idVehiculo As Integer
    Public Property fechaEnvio As Nullable(Of Date)
    Public Property tripulante1 As Nullable(Of Integer)
    Public Property tripulante2 As Nullable(Of Integer)
    Public Property chofer As String
    Public Property matriculaUnidad As String
    Public Property otros As Nullable(Of Integer)
    Public Property estado As Nullable(Of Integer)
    Public Property usuarioActualizacion As Nullable(Of Integer)
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property rutaTareoEncomiendaDetalle As ICollection(Of rutaTareoEncomiendaDetalle) = New HashSet(Of rutaTareoEncomiendaDetalle)

End Class
