'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class servicio
    Public Property idServicio As Integer
    Public Property idItemServicio As Nullable(Of Integer)
    Public Property idEmpresa As String
    Public Property idEstablecimiento As Nullable(Of Integer)
    Public Property idPadre As Nullable(Of Integer)
    Public Property fecha As Nullable(Of Date)
    Public Property descripcion As String
    Public Property unidadMedida As String
    Public Property tipo As String
    Public Property tipoExist As String
    Public Property tipoServicio As String
    Public Property idProveedor As String
    Public Property codigo As String
    Public Property costo As String
    Public Property valor As Nullable(Of Decimal)
    Public Property categoria As Nullable(Of Integer)
    Public Property subCategoria As String
    Public Property cuenta As String
    Public Property cuentaH As String
    Public Property cuentaDev As String
    Public Property cuentaDevH As String
    Public Property observaciones As String
    Public Property estado As String
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property composicion As ICollection(Of composicion) = New HashSet(Of composicion)
    Public Overridable Property itemServicio As itemServicio

End Class
