'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tabladetalle
    Public Property idtabla As Integer
    Public Property codigoDetalle As String
    Public Property codigoDetalle2 As String
    Public Property descripcion As String
    Public Property estadodetalle As String
    Public Property usuarioModificacion As String
    Public Property fechaModificacion As Nullable(Of Date)

    Public Overridable Property tabla As tabla

End Class
