'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class talla
    Public Property idtalla As Integer
    Public Property idcategoria As Nullable(Of Integer)
    Public Property genero As String
    Public Property estado As Nullable(Of Integer)

    Public Overridable Property talla_equivalencias As ICollection(Of talla_equivalencias) = New HashSet(Of talla_equivalencias)

End Class
