'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class talla_equivalencias
    Public Property id_equivalencia As Integer
    Public Property idtalla As Integer
    Public Property usa As String
    Public Property uk As String
    Public Property eur As String
    Public Property cm As String
    Public Property ot As String

    Public Overridable Property talla As talla

End Class
