'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tipoCambio
    Public Property idEmpresa As String
    Public Property idCentroCosto As Integer
    Public Property fechaIgv As Date
    Public Property idRegulador As Integer
    Public Property idOrganizacion As Nullable(Of Integer)
    Public Property compra As Nullable(Of Decimal)
    Public Property venta As Nullable(Of Decimal)
    Public Property usuarioModificacion As String
    Public Property fechaModificacion As Nullable(Of Date)

    Public Overridable Property entesRegaludoresTC As entesRegaludoresTC

End Class
