'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class totalesLiquidacion
    Public Property secuencia As Integer
    Public Property idEmpresa As String
    Public Property idEstablecimiento As Integer
    Public Property idActividad As Integer
    Public Property tipoLiquidacion As String
    Public Property modulo As String
    Public Property Fecha As Nullable(Of Date)
    Public Property LI_ib_ini As Nullable(Of Decimal)
    Public Property LI_cfAcum_ini As Nullable(Of Decimal)
    Public Property LI_ib_ns As Nullable(Of Decimal)
    Public Property LI_cfAcum_ns As Nullable(Of Decimal)
    Public Property LI_ib_adic As Nullable(Of Decimal)
    Public Property LI_afAcum_adic As Nullable(Of Decimal)
    Public Property LR_ventan_ini As Nullable(Of Decimal)
    Public Property LR_costov_ini As Nullable(Of Decimal)
    Public Property LR_ventan_ns As Nullable(Of Decimal)
    Public Property LR_costov_ns As Nullable(Of Decimal)
    Public Property LR_inc_ns As Nullable(Of Decimal)
    Public Property LR_ventan_adic As Nullable(Of Decimal)
    Public Property LR_costov_adic As Nullable(Of Decimal)
    Public Property LR_inc_adic As Nullable(Of Decimal)
    Public Property LOO_ReDeAp_ini As Nullable(Of Decimal)
    Public Property LOO_ReDeAp_ns As Nullable(Of Decimal)
    Public Property LOO_ReDeAp_adic As Nullable(Of Decimal)
    Public Property detraccion_ini As Nullable(Of Decimal)
    Public Property detraccion_ns As Nullable(Of Decimal)
    Public Property detraccion_adic As Nullable(Of Decimal)
    Public Property AF_EjecucionIng_ini As Nullable(Of Decimal)
    Public Property AF_EjecucionIng_ns As Nullable(Of Decimal)
    Public Property AF_EjecucionIng_adic As Nullable(Of Decimal)
    Public Property AF_Percepcion_ini As Nullable(Of Decimal)
    Public Property AF_Percepcion_ns As Nullable(Of Decimal)
    Public Property AF_Percepcion_adic As Nullable(Of Decimal)
    Public Property AF_Otrosps_ini As Nullable(Of Decimal)
    Public Property AF_Otrosps_ns As Nullable(Of Decimal)
    Public Property AF_Otrosps_adic As Nullable(Of Decimal)
    Public Property AF_Detraccion_ini As Nullable(Of Decimal)
    Public Property AF_Detraccion_ns As Nullable(Of Decimal)
    Public Property AF_Detraccion_adic As Nullable(Of Decimal)
    Public Property AF_Retencion_ini As Nullable(Of Decimal)
    Public Property AF_Retencion_ns As Nullable(Of Decimal)
    Public Property AF_Retencion_adic As Nullable(Of Decimal)
    Public Property AF_Otrosng_ini As Nullable(Of Decimal)
    Public Property AF_Otrosng_ns As Nullable(Of Decimal)
    Public Property AF_Otrosng_adic As Nullable(Of Decimal)
    Public Property AF_TotalPagoProvSust_ini As Nullable(Of Decimal)
    Public Property AF_TotalPagoProvSust_ns As Nullable(Of Decimal)
    Public Property AF_TotalPagoProvSust_adic As Nullable(Of Decimal)
    Public Property AF_RefGastoNoSust_ini As Nullable(Of Decimal)
    Public Property AF_RefGastoNoSust_ns As Nullable(Of Decimal)
    Public Property AF_RefGastoNoSust_adic As Nullable(Of Decimal)
    Public Property LP_TotalPagoProvCSSust_ini As Nullable(Of Decimal)
    Public Property LP_TotalPagoProvCSSust_ns As Nullable(Of Decimal)
    Public Property LP_TotalPagoProvCSSust_adic As Nullable(Of Decimal)
    Public Property LP_EgresoNoSustentado_ns As Nullable(Of Decimal)
    Public Property LP_EgresoNoSustentado_adic As Nullable(Of Decimal)
    Public Property LP_EgresoInciAdic_adic As Nullable(Of Decimal)
    Public Property totalIngresos As Nullable(Of Decimal)
    Public Property tipoPlan As String
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

End Class
