'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class totalesAlmacenOthers
    Public Property idMovimiento As Integer
    Public Property idDocumento As Nullable(Of Integer)
    Public Property idDocumento_detalle As Nullable(Of Integer)
    Public Property idProducto As Nullable(Of Integer)
    Public Property id_equivalencia As Nullable(Of Integer)
    Public Property idcategoria As Nullable(Of Integer)
    Public Property idalmacen As Nullable(Of Integer)
    Public Property genero As String
    Public Property cantidad As Nullable(Of Decimal)
    Public Property tipoRegistro As String
    Public Property status As Nullable(Of Integer)

End Class
