'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class totalLiquidacionUtilidades
    Public Property secuencia As Integer
    Public Property idLiquidacion As Integer
    Public Property NomSocio As String
    Public Property tasaProcentaje As Nullable(Of Decimal)
    Public Property monto_ini As Nullable(Of Decimal)
    Public Property monto_ns As Nullable(Of Decimal)
    Public Property monto_adic As Nullable(Of Decimal)
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

End Class
