'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class totalinventario
    Public Property idEmpresa As String
    Public Property idCentroCosto As String
    Public Property idAlmacen As String
    Public Property idItem As String
    Public Property secuencia As Integer
    Public Property ingresoID As String
    Public Property cantidad As Nullable(Of Decimal)
    Public Property costoUnitario As Nullable(Of Decimal)
    Public Property idInventario As String
    Public Property tipoCosteo As String
    Public Property usuarioModificacion As String
    Public Property fechaModificacion As Nullable(Of Date)

End Class
