'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Trabajador_PL
    Public Property idEmpresa As String
    Public Property idEstablecimiento As Integer
    Public Property codTrabajdor As String
    Public Property idProyecto As Nullable(Of Integer)
    Public Property nombres As String
    Public Property appat As String
    Public Property apmat As String
    Public Property tipoDoc As String
    Public Property fecNacimiento As Date
    Public Property sexo As String
    Public Property codPais As String
    Public Property codNivelEducativo As String
    Public Property condDomicilio As String
    Public Property domicilio As String
    Public Property IsDiscapacidad As String
    Public Property regPensionario As String
    Public Property FecInscripcion As Nullable(Of Date)
    Public Property CUSPP As String
    Public Property SCTR As String
    Public Property Salud As String
    Public Property Pension As String
    Public Property OtroIngresos5ta As String
    Public Property estado As String

End Class
