'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UsuariosEmpresa
    Public Property dni As String
    Public Property idEmpresa As String
    Public Property appat As String
    Public Property apmat As String
    Public Property nombres As String
    Public Property pass As String
    Public Property direccion As String
    Public Property fono As String
    Public Property email As String
    Public Property nivelUsuario As String

End Class
