'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vehiculoAsientos
    Public Property idActivo As Integer
    Public Property codigo As Integer
    Public Property codeAlfanumerico As String
    Public Property descripcion As String
    Public Property tipo As Nullable(Of Integer)
    Public Property ubicacion As String
    Public Property costoEstimado As Nullable(Of Decimal)
    Public Property estado As Nullable(Of Integer)

End Class
