'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vehiculoAsiento_Precios
    Public Property ruta_id As Integer
    Public Property horario_id As Integer
    Public Property codigoServicio As Integer
    Public Property precio_id As Integer
    Public Property idDistribucion As Integer
    Public Property idComponente As Nullable(Of Integer)
    Public Property idEmpresa As String
    Public Property idEstablecimiento As Nullable(Of Integer)
    Public Property tareo_id As Nullable(Of Integer)
    Public Property idDocumentoVenta As Nullable(Of Integer)
    Public Property idActivo As Nullable(Of Integer)
    Public Property programacion_id As Nullable(Of Integer)
    Public Property fechaProgramada As Nullable(Of Date)
    Public Property vence As Nullable(Of Date)
    Public Property origen As Nullable(Of Integer)
    Public Property moneda As String
    Public Property numeracion As String
    Public Property precioAsientoMN As Nullable(Of Decimal)
    Public Property precioAsientoME As Nullable(Of Decimal)
    Public Property sexo As String
    Public Property abreviaturaReserva As String
    Public Property colorReserva As String
    Public Property horaReserva As Nullable(Of Date)
    Public Property idConfiguracion As Nullable(Of Integer)
    Public Property idItem As Nullable(Of Integer)
    Public Property descripcionItem As String
    Public Property destino As Nullable(Of Integer)
    Public Property estado As String
    Public Property usuarioActualizacion As String
    Public Property fechaActualizacion As Nullable(Of Date)

    Public Overridable Property distribucionInfraestructura As distribucionInfraestructura

End Class
