Imports Helios.Cont.Business.Entity

'Imports Helios.Planilla.Business.Entity

Imports Helios.Seguridad.Business.Entity
Imports Helios.Cont.WCFService.ServiceAccess
'Imports Helios.Planilla.WCFService.ServiceAccess
Imports Helios.Seguridad.WCFService.ServiceAccess
Module Module1

    Public AutenticacionUsuario As AutenticacionUsuario
    Public AutorizacionRolList As List(Of AutorizacionRol)
    Public UsuariosList As List(Of Usuario)

    Public usuario As New AutenticacionUsuario



    Public Function validarPermisos(idaseg As Integer, lista As List(Of AutorizacionRol)) As Integer

        Dim consulta = (From i In lista
                        Where i.IDAsegurable = idaseg).Count

        Return consulta
    End Function


    Public Enum PermisosDelSistema

        LOGISTICA_ = 1
        COMERCIAL_ = 2
        FINANZAS_ = 3
        MODULO_DE_USUARIOS_ = 4
        MODULO_DE_MANTENIMIENTO_ = 5
        INGRESO_DE_COMPRAS_ = 13
        VENTA_ = 21
        GESTION_DE_PRECIOS_ = 22
        INGRESO_DE_EFECTIVO_ = 31
        SALIDA_DE_EFECTIVO_ = 32
        CAJA_ = 23
        APERTURA_DE_CAJA_ = 33
        CIERRE_DE_CAJA_ = 34
        ENTRADA_INVENTARIO_ = 11
        SALIDA_DE_INVENTARIO_ = 12
        CIERRE_DE_PERIODO_ = 52
        CONFIGURAR_CAJAS_ = 51

        CLIENTES_ = 36 ' FALTA
        PROVEEDORES_ = 8 ' FALTA
        CONTROL_KARDEX_ = 10 ' FALTA
        KARDEX_ = 37 ' FALTA
        INVENTARIO_INICIAL_ = 15 ' FALTA
        MOVIMIENTO_KARDEX_ = 16 ' FALTA
        CUENTAS_POR_PAGAR_ = 17 ' FALTA
        CUENTAS_POR_COBRAR_ = 18 ' FALTA
        MOVIMIENTO_FINANZAS_ = 19 ' FALTA
        CAJA_CENTRAL_ = 20 ' FALTA
        ARQUEO_CAJA_ = 25 ' FALTA
        HISTORIAL_CAJA_ = 26 ' FALTA
        CONTROL_CAJA_ = 27 ' FALTA
        CAJA_POR_ARQUEAR_ = 28 ' FALTA
        CONTROL_USUARIOS_ = 29 ' FALTA
        ASIGNAR_RESPONSABLE_ = 30 ' FALTA
        IMPRESION = 35 ' NUEVO

        TRANSFERENCIA_ENTRE_ALMACENES_ = 14
        PEDIDOS_ = 24


        MANTENIMIENTO_ALAMACEN_ = 61
        ALMACEN_ = 6


    End Enum

    Public Enum AsegurablesSistemaPOS

        'COMERCIAL_ = 1
        'LOGISTICA_ = 2
        'FINANZAS_ = 3
        'CAJA_CENTRALIZADA_ = 5
        'CIERRE_MENSUAL_ = 8
        'ADMINISTRAR_USUARIOS_ = 9
        'CIERRE_CAJA_ = 10


        ADMINISTRAR_CIERRES__ = 324
        RESUMEN_DIARIO__ = 325
        CONFIGURACION_VARIABLES_GLOBALES__ = 326
        ENTREGA_DE_INVENTARIO__ = 327
        USUARIOS_DEL_SISTEMA__ = 328
        CENTRAL_DE_REPORTES__ = 329
        PANEL_LOGISTICA__ = 330
        PANEL_COMERCIAL__ = 331
        PANEL_FINANZAS__ = 332
        PRODUCTOS_POR_VENCER__ = 333
        NOTIFICACIÒN_Y_ALERTAS__ = 334
        PANEL_MANTENIMIENTO_DEL_SISTEMA__ = 335
        CAJA_CENTRALIZADA__ = 336
        CAJA_CENTRALIZADA_Sin_inventario___ = 337
        ADMINISTRAR_PRECIOS__ = 338
        COMPRAS_Pestaña___ = 339
        INVENTARIO_Pestaña___ = 340
        NUEVA_COMPRA_Formulario___ = 341
        REGISTRO_DE_COMPRAS_Formulario___ = 342
        EDITAR_Botón___ = 343
        ELIMINAR_ANULAR_Botón___ = 344
        ASIGNAR_NOTA_DE_CREDITO_Botón___ = 345
        ASIGNAR_NOTA_DE_DEBITO_Botón___ = 346
        COMPRA_VINCULADA_Botón___ = 347
        COPIAR_COMPROBANTE_Botón___ = 348
        NUEVA_NOTA_Formulario___ = 349
        REGISTRO_DE_NOTA_Formulario___ = 350
        VER_NOTA_Botón___ = 351
        ELIMINAR_ANULAR_NOTA_Botón___ = 352
        NOTA_DE_CREDITO_Formulario___ = 353
        NOTA_DE_DEBITO_Formulario___ = 354
        PROVEEDORES_Formulario___ = 355
        INVENTARIO_EN_TRÀNSITO_Formulario___ = 356
        ENVIAR_A_ALMACEN_Botón___ = 357
        INVENTARIO_VIGENTE_Formulario___ = 358
        INVENTARIO_HISTORIAL_Formulario___ = 359
        KARDEX_Formulario___ = 360
        OTRAS_ENTRADAS_Formulario___ = 361
        NUEVA_ENTRADA_Botón___ = 362
        NUEVO_APORTE_Botón___ = 363
        EDITAR_ENTRADA_Botón___ = 364
        ANULAR_ENTRADA_Botón___ = 365
        OTRAS_SALIDAS_Formulario___ = 366
        NUEVO_SALIDA_Botón___ = 367
        EDITAR_SALIDA_Botón___ = 368
        ANULAR_SALIDA_Botón___ = 369
        ALMACEN_Formulario___ = 370
        NUEVO_ALMACEN_Botón___ = 371
        EDITAR_ALMACEN_Botón___ = 372
        ESTADO_ALMACEN_Botón___ = 373
        TRANSFERENCIAS_Formulario___ = 374
        NUEVA_TRANSFERENCIA_Botón___ = 375
        EDITAR_TRANSFERENCIA_Botón___ = 376
        VENTAS_Pestaña___ = 377
        VENTAS_SIN_INVENTARIO_Pestaña___ = 378
        OFERTAS_Y_PROMOCIONES_Pestaña___ = 379
        COTIZACION_PROFORMA_Formulario___ = 380
        ADMINISTRAR_PROFORMA_Formulario___ = 381
        NUEVA_PROFORMA_Botón___ = 382
        EDITAR_PROFORMA_Botón___ = 383
        ELIMINAR_PROFORMA_Botón___ = 384
        REIMPRIMIR_PROFORMA_Botón___ = 385
        VENTA_GENERAl_Formulario___ = 386
        VENTA_POR_LOTES_Formulario___ = 387
        VER_REGISTRO_DE_VENTAS_Formulario___ = 388
        EDITAR_VENTA_Botón___ = 389
        ANULAR_VENTA_Botón___ = 390
        VENTA_ELECTRONICA_Formulario___ = 391
        VENTA_FORMATO_FISICO_Formulario___ = 392
        CLIENTES_Formulario___ = 393
        NUEVO_CLIENTE_Botón___ = 394
        EDITAR_CLIENTE_Botón___ = 395
        VER_NOTA_DE_VENTA_Formulario___ = 396
        NUEVO_PEDIDO_SI_Formulario___ = 397
        PEDIDOS_PENDIENTES_SI_Formulario___ = 398
        NUEVA_PROFORMAS_SI_Formulario___ = 399
        GESTIONAR_PROFORMAS_SI_Formulario___ = 400
        NUEVA_PROFORMA_SI_Botón___ = 401
        EDITAR_PROFORMA_SI_Botón___ = 402
        ELIMINAR_PROFORMA_SI_Botón___ = 403
        REIMPRIMIR_PROFORMA_SI_Botón___ = 404
        VENTA_ELECTRONICAS_SI_Formulario___ = 405
        VENTA_FORMATO_FISICO_SI_Formulario___ = 406
        VER_REGISTRO_DE_VENTA_Formulario___ = 407
        EDITAR_VENTA_SI_Botón___ = 408
        ELIMINAR__ANULAR_SI_Botón___ = 409
        REGISTRO_DE_CLIENTES_Formulario___ = 410
        NUEVO_CLIENTES_Formulario___ = 411
        BUSCAR_CLIENTES_Formulario___ = 412
        NOTAS_DE_VENTA_Formulario___ = 413
        CUENTAS_FINANCIERAS_Formulario___ = 414
        ADMINISTRAR_CUENTAS_FINANCIERAS_Formulario___ = 415
        EDITAR_CUENTA_FINANCIERA_Botón___ = 416
        MOVIMIENTOS_Formulario___ = 417
        ABRIR_CAJA_Formulario___ = 418
        HISTORIAL_DE_CAJA_Formulario___ = 419
        EDITAR_CAJA_Botón___ = 420
        CERRAR_CAJA_Botón___ = 421
        OTROS_INGRESOS_Formulario___ = 422
        NUEVO_INGRESO_Botón___ = 423
        EDITAR_INGRESO_Botón___ = 424
        ELIMINAR_ANULAR_INGRESO_Botón___ = 425
        OTROS_GASTOS_Formulario___ = 426
        NUEVA_SALIDA_CAJA_Botón___ = 427
        EDITAR_SALIDA_CAJA_Botón___ = 428
        ANULAR_SALIDA_CAJA_Botón___ = 429
        TABLA_GENERALES_Pestaña___ = 430
        PRODUCTOS_Y_ARTICULOS_Pestaña___ = 431
        NUEVO_CATALOGO_Formulario___ = 432
        LISTA_CATALOGO_Formulario___ = 433
        EDITAR_ITEM_Botón___ = 434
        ESTADO_ITEM_Botón___ = 435
        TIPO_CAMBIO_Formulario___ = 436
        TIPO_CAMBIO_2_Formulario___ = 437
        NUEVO_PRODUCTO_Formulario___ = 438
        LISTA_PRODUCTO_Formulario___ = 439
        EDITAR_PRODUCTO_Botón___ = 440
        ESTADO_PRODUCTO_Botón___ = 441
        AGRUPAR_PRODUCTOS_Formulario___ = 442
        NUEVO_USUARIO_Formulario___ = 443
        VER_USUARIO_Formulario___ = 444
        EDITAR_USUARIO_PERFIL_Botón___ = 445
        ESTADO_USUARIO_Botón___ = 446
        ASIGNAR_CODIGO_VENDEDOR_Botón___ = 447
        USUARIO_PASSWORD_Formulario___ = 448
        CAMBIAR_PASSWORD_Botón___ = 449
        NUEVO_PERFIL_USUARIO_Formulario___ = 450
        VER_PERFILES_Formulario___ = 451
        EDITAR_USUARIO_Botón___ = 452
        VER_PERFILES_X_USUARIO_Formulario___ = 453
        NUEVO_MODULOS_Formulario___ = 454
        VER_RESUMEN_MODULOS_Formulario___ = 455
        FACTURACION_ELECTRONICA___ = 456
    End Enum

    Public Enum AsegurablesSistema

        INFORMACION_GERENCIAL_Dashword__ = 1
        CONFIGURACION_SISTEMA__ = 2
        CONFIGURACION_DE_INICIO__ = 3
        PERMISO_Y_ROLES_DE_USUARIO__ = 4
        HOJA_DE_TRABAJO__ = 5
        CENTRO_DE_COSTOS__ = 6
        QUITAR_ASIGNACION_Botón__ = 7
        CENTRAL_DE_REPORTES__ = 8
        CUENTAS_FINANCIERAS__ = 9
        CIERRE_DE_PERIODOS__ = 10
        USUARIOS_DE_CAJA__ = 11
        PANEL_LOGISTICA__ = 12
        PANEL_COMERCIAL__ = 13
        PANEL_FINANZAS__ = 14
        CONTROL_PATRIMONIAL__ = 15
        PANEL_CONTABILIDAD__ = 16
        REGISTRO_DE_ASIENTOS_MANUALES__ = 17
        CONSULTAR_ASIENTOS_MANUALES_POR_PERIORO_Botón__ = 18
        NUEVO_ASIENTO_MANUAL_Formulario__ = 19
        EDITAR_ASIENTO_MANUAL_Formulario__ = 20
        ELIMINAR_ASIENTO_MANUAL_Formulario__ = 21
        CAMBIAR_PERIODO_ASIENTO_MANUAL_Formulario__ = 22
        ASIENTO_POR_CONCILIAR__ = 23
        CONSULTAR_INVENTARIO_Botón__ = 24
        CONSULTAR_FINANZAS_Botón__ = 25
        GRABAR_ASIENTOS_Botón__ = 26
        ASIENTO_MANUAL_Botón__ = 27
        ASIENTO_SUGERIDO_Botón__ = 28
        ELIMINAR_ASIENTO_Botón__ = 29
        REGISTRO_CONTABILIDAD_DE_ASIENTO_APERTURA__ = 30
        CUENTAS_POR_PAGAR_Registrar_pagos_Botón__ = 31
        CUENTAS_FINANCIERAS_Agregar_cuentas_Botón__ = 32
        CUENTAS_POR_COBRAR_Agregar_Botón__ = 33
        EXISTENCIA_DE_INICIO_Agregar_árticulo_Botón__ = 34
        CUENTAS_CONTABLES_Agregar_Cuenta_Botón__ = 35
        REGISTRO_DE_ASIENTOS_DE_CIERRE__ = 36
        LIBRO_ELECTRONICO__ = 37
        ESTADOS_FINANCIEROS__ = 38
        HOJA_DE_TRABAJO_PRINCIPAL_ = 39
        CENTRO_DE_GASTOS__ = 40
        NUEVO_CENTRO_DE_GASTOS_Formulario__ = 41
        EDITAR_CENTRO_DE_GASTOS_Formulario__ = 42
        ELIMINAR_CENTRO_DE_GASTOS_Botón__ = 43
        PANEL_PLANILLA__ = 44
        PLANTILLAS_PLANILLA__ = 45
        REGISTRO_INICIO_DE_ASISTENCIAS__ = 46
        REGISTRO_CONTROL_DE_PERSONAL__ = 47
        CONSULTAR_ASISTENCIA_POR_PERIDO_Botón__ = 48
        MANTENIMIENTO_PERSONAL__ = 49
        HORARIOS_Formulario__ = 50
        NUEVO_PERSONAL_Formulario__ = 51
        EDITAR_PERSONAL_Formulario__ = 52
        INACTIVO_PERSONAL_Botón__ = 53
        CONCEPTOS_POR_PLANILLA__ = 54
        CONSULAR_TIPO_PLANILLA_Botón__ = 55
        NUEVO_TIPO_PLANILLA_Formulario__ = 56
        EDITAR_TIPO_PLANILLA_Formulario__ = 57
        INACTIVO__Botón__ = 58
        CALCULO_PLANILLA__ = 59
        PANEL_PROYECTOS__ = 60
        PROYECTOS_PROYECTOS_ACTIVOS__ = 61
        NUEVO_PROYECTO_Botón__ = 62
        EDITAR_PROYECTO_Formulario__ = 63
        ABRIR_PROYECTO_Botón__ = 64
        CERRAR_PROYECTO_Botón__ = 65
        AGREGAR_EDT__S_Formulario__ = 66
        PROYECTO_GENERAL_Formulario__ = 67
        GESTION_PMBOK_Formulario__ = 68
        PROYECTOS_CULMINADOS__ = 69
        DETALLE_PROYECTO_CULMINADO_Formulario__ = 70
        REABRIR_Botón__ = 71
        AGREGAR_EDTS_PROYECTO_CULMINADO_Formulario__ = 72
        GESTION_PMBOK_PROYECTO_CULMINADO_Formulario__ = 73
        MERCADERIAS__ = 74
        PRODUCTOS_TERMINADOS__ = 75
        PRESTACION_DE_SERVICIOS__ = 76
        ORDENES_DE_PRODUCCION__ = 77
        NUEVA_ORDEN_Formulario__ = 78
        EDITAR_ORDEN_Formulario__ = 79
        ELIMINAR_ORDEN_Botón__ = 80
        ORDEN_EN_PROCESO_Botón__ = 81
        VER_CULMINADOS__Botón__ = 82
        ORDEN_OBSERVADOS__Botón__ = 83
        ORDEN_ERRONEOS__Botón__ = 84
        CERRAR_PRODUCCION_Botón__ = 85
        BORRAR_CIERRE__Botón__ = 86
        MOSTRAR_ENTREGAS_Botón__ = 87
        NUEVA_ENTREGA_Formulario__ = 88
        ELIMINAR_ENTREGA__Botón__ = 89
        ENVIAR_A_ALMACEN_Formulario__ = 90
        ELIMINAR_ENVIO_Botón__ = 91
        INFORMACION_PRESUPUESTO__ = 92
        AGREGAR_EDTS_INFORMACION_PRESUPUESTO_Formulario__ = 93
        ELIMINAR_EDT__S_Botón__ = 94
        LIBROS_ELECTRONICOS__ = 95
        ASIGNACION_DE_COSTOS_Y_GASTOS__ = 96
        RECONOCIMIENTO_Y_ASIGNACIÓN_DE_INGRESOS__ = 97
        CIERRES__ = 98
        CIERRES_DE_MES_Formulario__ = 99
        ELIMINAR_CIERRE_Botón__ = 100
        REGISTRO_DE_COTIZACIONES__ = 101
        REGISTRO_DE_ORDEN_DE_COMPRA__ = 102
        REGISTRO_DE_ORDEN_DE_SERVICIO__ = 103
        REGISTRO_DE_COMPRAS__ = 104
        COMPRA_AL_CREDITO_Existencias_servicios_y_otros_Formulario__ = 105
        COMPRA_AL_CREDITO_Servicios_públicos_Formulario__ = 106
        COMPRA_AL_CREDITO_Honorarios_Formulario__ = 107
        COMPRA_AL_CREDITO_Importaciones_Formulario__ = 108
        COMPRA_AL_CONTADO_Existencias_servicios_y_otros_Formulario__ = 109
        COMPRA_AL_CONTADO_Servicios_públicos_Formulario__ = 110
        COMPRA_AL_CONTADO_Honorarios_Formulario__ = 111
        COMPRA_AL_CONTADO_Anticipo_por_compras_Formulario__ = 112
        BONIFICACION_RECIBIDAS_Formulario__ = 113
        NOTA_DE_CREDITO_ESPECIAL_Nuevo_Formulario__ = 114
        NOTA_DE_DEBITO_ESPECIAL_Nuevo_Formulario__ = 115
        ANULACION_DE_GASTOS_FINANCIEROS_Formulario__ = 116
        NOTA_DE_DEBITO_Formulario__ = 117
        NOTA_DE_CREDITO_Formulario__ = 118
        PROVEEDOR_Formulario__ = 119
        DETRACCION_Formulario__ = 120
        VER_COMPROBANTE_Formulario__ = 121
        COLOCAR_EN_OBSERVACION_Botón__ = 122
        COLOCAR_EN_ESTADO_NORMAL_Botón__ = 123
        COPIAR_COMPROBANTE_Botón__ = 124
        CONSULTAR_COMPRA_POR_PERIODO_Botón__ = 125
        REGISTRO_PROVEEDOR__ = 126
        NUEVO_PROVEEDOR_Formulario__ = 127
        EDITAR_PROVEEDOR_Formulario__ = 128
        CAMBIAR_ACTIVO_INACTIVO_Botón__ = 129
        REGISTRO_DE_DETRACCIONES__ = 130
        CONSULTAR_DETRACCION_POR_PERIODO_Botón__ = 131
        ELIMINAR_DETRACCION_Botón__ = 132
        REGISTRO_DE_COMPRAS_OBSERVADAS__ = 133
        ACTIVAR_COMPROBANTE_DE_COMPRA_Botón__ = 134
        NOTA_DE_CREDITO_COMPROBANTE_OBSERVADAS_Formulario__ = 135
        NOTA_DE_CREDITO_ESPECIAL_COMPROB_OBSERVADAS_Formulario__ = 136
        REGISTRO_RESUMEN_CONTABLE_DE_COMPRAS__ = 137
        REGISTRO_INVENTARIOS_EN_TRANSITO_X_COMPRA__ = 138
        SELECCIONAR_ITEMS_Botón__ = 139
        ENVIAR_A_ALMACEN_Botón__ = 140
        CONSULTAR_INVENTARIO_EN_TRANSITO_POR_PERIODO_Botón__ = 141
        REGISTRO_INVENT_EN_TRANS_TRANSF_ENTRE_ALMACENES__ = 142
        CONSULTAR_ITEMS_EN_TRANSITO_POR_PERIODO_Botón__ = 143
        CONFIRMAR_RECEPCION_Formulario__ = 144
        HISTORIAL_DE_RECEPCION_Formulario__ = 145
        REGISTRO_OTROS_MOVIMIENTOS_Formulario__ = 146
        MOVIMIENTO_INVENTARIO_OTRAS_ENTRADAS_Consignaciones_Formulario__ = 147
        MOVIMIENTO_INVENTARIO_OTRAS_ENTRADAS_Promoción_Formulario__ = 148
        MOVIMIENTO_INVENTARIO_OTRAS_ENTRADAS_Premios_Formulario__ = 149
        MOVIMIENTO_INVENTARIO_OTRAS_ENTRADAS_Donación_Formulario__ = 150
        MOVIMIENTO_INVENTARIO_OTRAS_ENTRADAS_Productos_terminados_Formulario__ = 151
        MOVIMIENTO_INVENTARIO_OTRAS_ENTRADAS_Sub_productos__y_desperdicios_Formulario__ = 152
        MOVIMIENTO_INVENTARIO_OTRAS_ENTRADAS_Productos_en_proceso_Formulario__ = 153
        MOVIMIENTO_INVENTARIO_OTRAS_ENTRADAS_Devoluciones_Formulario__ = 154
        MOVIMIENTO_INVENTARIO_OTRAS_ENTRADAS_Otros_Formulario__ = 155
        MOVIMIENTO_INVENTARIO_OTRAS_SALIDAS_Consignaciones_Formulario__ = 156
        MOVIMIENTO_INVENTARIO_OTRAS_SALIDAS_Promoción_Formulario__ = 157
        MOVIMIENTO_INVENTARIO_OTRAS_SALIDAS_Premios_Formulario__ = 158
        MOVIMIENTO_INVENTARIO_OTRAS_SALIDAS_Donación_Formulario__ = 159
        MOVIMIENTO_INVENTARIO_OTRAS_SALIDAS_Productos_terminados_Formulario__ = 160
        MOVIMIENTO_INVENTARIO_OTRAS_SALIDAS_Sub_productos__y_desperdicios_Formulario__ = 161
        MOVIMIENTO_INVENTARIO_OTRAS_SALIDAS_Productos_en_proceso_Formulario__ = 162
        MOVIMIENTO_INVENTARIO_OTRAS_SALIDAS_Devoluciones_Formulario__ = 163
        MOVIMIENTO_INVENTARIO_OTRAS_SALIDAS_Otros_Formulario__ = 164
        SALIDA_A_PRODUCCION_Botón__ = 165
        RETORNO_A_PRODUCCION_Botón__ = 166
        INGRESO_DE_PRODUCTOS_TERMINADOS_Formulario__ = 167
        EDITAR_MOVIMIENTO_Botón__ = 168
        ELIMINAR_MOVIMIENTO_Botón__ = 169
        REVERSION_Formulario__ = 170
        PANEL_DE_ASIENTO_CONTABLE_Formulario__ = 171
        REGISTRO_LISTA_CAMBIO_INVENTARIO__ = 172
        CONSULTAR_LISTA_POR_PERIODO_Botón__ = 173
        REGISTRO_TRANSFERENCIA_ENTRE_ALMACENES__ = 174
        NUEVA_TRANSFERENCIA_Formulario__ = 175
        EDITAR_TRANSFERENCIA_Formulario__ = 176
        ELIMINAR_TRANSFERENCIA_Botón__ = 177
        CONSULTAR_TRANSFERENCIA_POR_PERIODO_Botón__ = 178
        REGISTRO_CAMBIO_TIPO_DE_INVENTARIO__ = 179
        NUEVA_CAMBIO_TIPO_DE_INVENTARIO_Formulario__ = 180
        EDITAR_CAMBIO_TIPO_DE_INVENTARIO_Formulario__ = 181
        ELIMINAR_CAMBIO_TIPO_DE_INVENTARIO_Botón__ = 182
        CONSULTAR_CAMBIO_TIPO_DE_INVENTARIO_POR_PERIODO_Botón__ = 183
        REGISTRO_PENDIENTE_DE_ENTREGAS_POR_VENTAS__ = 184
        CONFIRMACION_DE_ENTREGAS_Formulario__ = 185
        INVENTARIOS_VALORIZADOS__ = 186
        CONSULTA_INVENTARIO_POR_PERIODO_Botón__ = 187
        EXPORTAR_EXCEL_Botón__ = 188
        CAMBIO_DE_INVENTARIO_Botón__ = 189
        KARDEX__ = 190
        CONSULTAR_KARDEX_POR_PERIODO_Botón__ = 191
        CORREGIR_INVENTARIO_Botón__ = 192
        CV_Botón__ = 193
        CONSULTA_KARDEX_POR_INVENTARIO_Botón__ = 194
        EXPORTAR_EXCEL_KARDEX_Botón__ = 195
        COSTO_DE_VENTAS_Botón__ = 196
        REGISTRO_ROTACION_DE_EXISTENCIAS__ = 197
        REGISTRO_ORDEN_DE_COMPRA_CONOCIMIENTO__ = 198
        VER_DETALLE_ORDEN_Formulario__ = 199
        REGISTRO_ALMACENES__ = 200
        NUEVO_ALMACEN_Formulario__ = 201
        EDITAR_ALMACEN_Formulario__ = 202
        CAMBIAR_ACTIVO_INACTIVO_ALMACEN_Botón__ = 203
        REGISTRO_PRECIOS_EXISTENCIAS__ = 204
        CONSULTAR_PRECIOS_EXISTENCIAS_Botón__ = 205
        ASIGNAR_PRECIOS_Formulario__ = 206
        ELIMINAR_ASIGNACION_Botón__ = 207
        MASTER__PRECIOS_SERVICIOS__ = 208
        ASIGNAR_PRECIOS_SERVICIOS_Formulario__ = 209
        ELIMINAR_ASIGNACION_SERVICIOS_Botón__ = 210
        CREAR_SERVICIO_Formulario__ = 211
        MASTER_ARTICULOS_SIN_PRECIOS__ = 212
        ASIGNAR_PRECIOS_ARTICULOS_Formulario__ = 213
        MASTER_PRECIOS_OBSERVADOS__ = 214
        ASIGNAR_PRECIOS_OBSERVADOS_Formulario__ = 215
        MASTER_CONFIGURACION_DE_PRECIOS__ = 216
        CREAR_PRECIOS_Formulario__ = 217
        EDITAR_PRECIOS_Formulario__ = 218
        REGISTRO_PEDIDOS__ = 219
        NUEVO_PEDIDO_Formulario__ = 220
        EDITAR_PEDIDO_Formulario__ = 221
        ELIMINAR_PEDIDO_Botón__ = 222
        CONSULTAR_PEDIDO_POR_PERIODO_Funcion__ = 223
        REGISTRO_PEDIDOS_RESERVADOS__ = 224
        REGISTRO_COTIZACION__ = 225
        NUEVA_COTIZACION_Formulario__ = 226
        EDITAR_COTIZACION_Formulario__ = 227
        ELIMINAR_COTIZACION_Botón__ = 228
        IMPRIMIR_Botón__ = 229
        PEDIDOS_RESERVADOS_Formulario__ = 230
        REALIZAR_VENTA_Formulario__ = 231
        CONSULTAR_COTIZACION_POR_PERIODO_Formulario__ = 232
        REGISTRO_SEGUIMIENTO__ = 233
        REGISTRO_DE_VENTAS__ = 234
        PUNTO_DE_VENTA_MULTIUSO_Formulario_POS__ = 235
        PUNTO_DE_VENTA_MULTIUSO_Formulario_GENERAL__ = 236
        VENTA_FORMATO_GENERAL_MULTIUSO_Formulario__ = 237
        VENTA_POS_CONTADO_Entrega_total_Formulario__ = 238
        VENTA_POS_CONTADO_Entrega_parcial_Formulario__ = 239
        VENTA_POS_CREDITO_Entrega_total_Formulario__ = 240
        VENTA_POS_CREDITO_Entrega_parcial_Formulario__ = 241
        VENTA_AL_CONTADO_Form_General_Entrega_total_Formulario__ = 242
        VENTA_AL_CONTADO_Form_General_Entrega_parcial_Formulario__ = 243
        VENTA_AL_CREDITO_Form_General_Entrega_total_Formulario__ = 244
        VENTA_AL_CREDITO_Form_General_Entrega_parcial_Formulario__ = 245
        VENTA_AL_CONTADO_ANTICIPOS_POR_VENTA_Formulario__ = 246
        CAJA_CENTRALIZADA_Formulario__ = 247
        PRE_VENTA_Formulario__ = 248
        AGREGAR_CLIENTE_Formulario__ = 249
        NOTAS_DE_CREDITO_Formulario__ = 250
        NOTA_DE_CREDITO_ESPECIAL_Formulario__ = 251
        REGISTRO_CLIENTES__ = 252
        NUEVO_CLIENTE_Formulario__ = 253
        EDITAR_CLIENTE_Formulario__ = 254
        ELIMINAR_CLIENTE_Botón__ = 255
        CONSULTAR_CLIENTE_Botón__ = 256
        REGISTRO_VENTA_ANULADA__ = 257
        CONSULTAR_ENTREGAS_POR_PERIODO_Botón__ = 258
        REGISTRO_RESUMEN_CONTABLES_DE_VENTAS__ = 259
        REGISTRO_CUENTAS_FINANCIERAS__ = 260
        NUEVA_CUENTA_FINANCIERA_Formulario____ = 261
        EDITAR_CUENTA_FINANCIERA_Formulario__ = 262
        MOVIMIENTO_MN__ = 263
        MOVIMIENTO_POR_DOCUMENTO_MN__ = 264
        MOVIMIENTO_ME__ = 265
        REGISTRO_TRANSFERENCIA_ENTRE_CAJAS__ = 266
        NUEVA_TRANSFERENCIA_ENTRE_CAJA_Formulario__ = 267
        EDITAR_TRANSFERENCIA_ENTRE_CAJA_Formulario__ = 268
        ENTREGAS_A_RENDIR_CUENTAS__ = 269
        COMPRA_Y_VENTA_MONEDA_EXTRANJERA__ = 270
        REGISTRO_OTROS_INGRESOS_MN_Me__ = 271
        NUEVO__Formulario_OTROS_INGRESOS__ = 272
        EDITAR__Formulario_OTROS_INGRESOS__ = 273
        REVERSION__Formulario_OTROS_INGRESOS__ = 274
        REGISTRO_OTROS_SALIDAS_MN_Me__ = 275
        NUEVO_Formulario__ = 276
        EDITAR_Formulario__ = 277
        REVERSION_Formulario_OTRAS_SALIDAS__ = 278
        REGISTRO_APORTES_MN_Me__ = 279
        NUEVO_APORTE_Formulario__ = 280
        EDITAR_APORTE_Formulario__ = 281
        REVERSION_APORTE_Formulario__ = 282
        REGISTRO_INGRESO_POR_ANTICIPOS__ = 283
        NUEVO_Formulario_INGRESO_x_ANTICIPO__ = 284
        EDITAR__Formulario_INGRESO_X_ANTICIPO__ = 285
        REVERSION_Formulario_INGRESO_x_ANTICIPO__ = 286
        REGISTRO_SALIDAS_POR_ANTICIPOS__ = 287
        NUEVO_Formulario_SALIDA_ANTICIPO__ = 288
        EDITAR_Formulario_SALIDA_ANTICIPO__ = 289
        REVERSION_Formulario_SALIDA_ANTICIPO__ = 290
        MOVIMIENTOS_POR_OPERACIÓN__ = 291
        REGISTRO_DE_CUENTAS_POR_COBRAR__ = 292
        COBRAR_Formulario__ = 293
        VER_HISTORIAL_Formulario__ = 294
        COMPENSACION_Formulario__ = 295
        OTRAS_CUENTAS_POR_PAGAR__ = 296
        REGISTRO_DE_ANTICIPOS_OTORGADOS__ = 297
        RECLAMACIONES__ = 298
        CRONOGRAMA_DE_CREEENCIAS__ = 299
        TABLA_DE_CONTROL_DE_PAGOS_Formulario__ = 300
        MASTER_CUENTAS_POR_PAGAR__ = 301
        PAGAR_Formulario_CUENTAS_POR_PAGAR__ = 302
        VER_HISTORIAL_CUENTAS_POR_PAGAR_Formulario__ = 303
        REVERSION_CUENTAS_POR_PAGAR_Formulario__ = 304
        APLICAR_AJUSTES_Formulario__ = 305
        ELIMINAR_PROGRAMACION_Botón__ = 306
        CONDONACION_DE_CUENTAS_POR_PAGAR_Formulario__ = 307
        COMPENSACION_CUENTAS_POR_PAGAR_Formulario__ = 308
        REGISTRO_DE_OTRAS_CUENTAS_POR_PAGAR__ = 309
        CONSULTAR_OTRAS_CUENTAS_POR_PERIODO_Botón__ = 310
        PAGAR_OTRAS_CUENTAS__Formulario__ = 311
        ELIMINAR_OTRAS_CUENTAS_Botón__ = 312
        REGISTRO_DE_ANTICIPOS_RECIBIDOS__ = 313
        REGISTRO_DE_RECLAMACIONES__ = 314
        REGISTRO_DE_CRONOGRAMA_DE_OBLIGACIONES__ = 315
        TABLA_DE_CONTROL_DE_PAGOS_CO_Formulario__ = 316
        ADMINISTRACION_DE_USUARIOS__ = 317
        CAJA_ABRIR_CERRAR_Formulario__ = 318
        NUEVA_CAJA_Formulario__ = 319
        EDITAR_CAJA_Formulario__ = 320
        CONSULTAR_CAJAS_Botón__ = 321
        CERRAR_CAJA_Formulario__ = 322
        HISTORIAL_DE_CAJAS_Formulario__ = 323
        REPORTES_DE_CAJA_Formulario__ = 324
        CUENTAS_POR_COBRAR_Acreencias__ = 325
        PROGRAMACION_DE_CUENTAS_POR_COBRAR_Acreencias__ = 326
        CUENTAS_POR_PAGAR_Obligaciones__ = 327
        PROGRAMACION_DE_CUENTAS_POR_PAGAR_Acreencias__ = 328
        ESTADO_DE_SITUACION_FINANCIERA__ = 329
        ESTADO_DE_RESULTADOS__ = 330

    End Enum

    Public Enum ModuloAsegurable 'Los códigos son los que están asignados en la BD
        'OrdenesCompra = 11
        'Inventario = 12
        'Comercial = 13
        'Finanzas = 14
        'Contabilidad = 15
        'Compras = 18

        ORDENES = 11
        INVENTARIO = 12
        COMERCIAL = 13
        FINANZAS = 14
        CONTABILIDAD = 15
        RECUROS_HUMANOS = 16
        PLANEAMIENTO = 17
        COMPRAS = 18
        COMPRAS_AL_CONTADO_CON_RECEPCION = 19
        COMPRAS_AL_CREDITO_CON_RECEPCION = 20
        REGISTRO_DE_COMPRAS = 21
        PROVEEDORES = 22
        PRODUCTOS_EN_TRANSITO = 23
        LISTA_INVENTARIO = 24
        KARDEX = 25
        OTROS_MOVIMINTOS = 26
        PRE_VENTA = 27
        VENTA_TICKET_DIRECTA = 28
        VENTA_AL_CREDITO = 29
        VENTA_AL_CONTADO = 30
        VENTA_SERVICIO_AL_CREDITO = 31
        VENTA_SERVICIO_AL_CONTADO = 32
        CLIENTE = 33
        REGISTRO_VENTAS = 34
        COMPRAS_AL_CONTADO_SIN_RECEPCION = 35
        COMPRAS_AL_CREDITO_SIN_RECEPCION = 36
        LISTA_PRECIOS = 37
        CONFIG_INICIO = 38
        APERTURAR_CAJA = 40
        CERRAR_CAJA = 41
    End Enum

End Module
